### ISSUE TITLE
Comment on "acquireTriggersWithinLock" property

### ISSUE THREAD

**Issue by ruslan-sverchkov** [quartz-scheduler/quartz#1]
/**
     \* Whether or not the query and update to acquire a Trigger for firing
     \* should be performed after obtaining an explicit DB lock (to avoid 
     \* possible race conditions on the trigger's db row).  This is the
     \* behavior prior to Quartz 1.6.3, but is considered unnecessary for most
     \* databases (due to the nature of the SQL update that is performed), 
     \* and therefore a superfluous performance hit.  
     */
    public boolean isAcquireTriggersWithinLock() {
        return acquireTriggersWithinLock;
    }

The property must be set for databases where simple SELECTs are never blocked (for ex. Oracle), it would be very helpful if this information was reflected somewhere in documentation.

**Comment by zemian** [comment]
Do you mean only in Non-Cluster mode? Because if you are in clustered mode, we automatically use the DB lock already.

**Comment by zemian** [comment]
Closing outdated, unresolved issues. Please, reopen if still relevant.
