### ISSUE TITLE
Hello, quartz support or not support the sqlite database?

### ISSUE THREAD

**Issue by xuxueli** [quartz-scheduler/quartz#10]
Hello, quartz support or not support the sqlite database?

**Comment by jhouserizer** [comment]
Not explicitly.  Have you tried the StdJDBCDelegate ?   It works with many sql-compliant databases.

**Comment by xuxueli** [comment]
OK. Thank you.
I based on quartz encapsulates a distributed task scheduling platform, called "XXL-JOB"。
The purpose is to contribute to open source, welcome you all to use。
https://github.com/xuxueli/xxl-job
