### ISSUE TITLE
Quartz simple trigger runs 23 secs earlier than expected

### ISSUE THREAD

**Issue by srampv** [quartz-scheduler/quartz#100]
I have simple_trigger which has start time 1484159100000  i.e : Wed Jan 11 2017 18:25:00 UTC , it supposed to be fired at this time . but it got fired at Wed Jan 11 2017 18:24:37 which is 23 seconds earlier . could you pls explain why does this happen ?

**Comment by srampv** [comment]
does this property "org.quartz.scheduler.batchTriggerAcquisitionMaxCount
" cause this issue?

**Comment by zemian** [comment]
Hello @srampv , this is not a bug. Please use the mailing list for questions.

Please read http://www.quartz-scheduler.org/documentation/quartz-2.2.x/configuration/ConfigMain.html

Perhaps you have set the following to non-zero.
org.quartz.scheduler.batchTriggerAcquisitionFireAheadTimeWindow

**Comment by peng-heng** [comment]
I also have the same issue. I confirm that org.quartz.scheduler.batchTriggerAcquireFireAhead TimeWindow=0,
I checked the source code and found that the call to JobStoreSupport # acquireNextTriggers will add DEFAULT-IDLEVNet to the current time

**Comment by peng-heng** [comment]
Additionally, this issue only occurs when the trigger result obtained is greater than 1
