### ISSUE TITLE
Close connection in `JobStoreCMT`

### ISSUE THREAD

**Issue by oleghailenko** [quartz-scheduler/quartz#101]
Hello, guys.
I have looked through code, and found one strange algorithm in `JobStoreCMT`.
In the method `executeInLock` You get connection, execute callback and and finally cleanup connection. In the method `cleanupConnection` You restore connection attributes and close connection. But, If I understand correct, `JobStoreCMT` can share the same connection with client code. Should connection be closed, If some one are going to use it? Is it bug or no?

**Comment by jhouserizer** [comment]
The connection is expected to come from a DataSource, and in such cases, calling close() on the connection simply returns it to the DataSource, it does not actually close the socket connection to the db.

**Comment by dmitrymurashenkov** [comment]
I've ran into this issue when using JobStoreCMT which takes connection from hibernate+c3p0+H2 SessionFactory. 

Although there is a PoolBackedDataSource that gives connection away - commit() cannot be called on it after close() was called. So this seems to be implementation dependent.
