### ISSUE TITLE
Quartz Scheduler stopped working after DB restart > misfireThreshold  Threshold

### ISSUE THREAD

**Issue by rahulkumarfpl** [quartz-scheduler/quartz#105]
We are using Quartz api to meet our application requirement and referring Quartz-2.1.7.jar and Quartz-Oracle 2.1.7.jar API.
The application running in cluster mode with 4 application servers configured and We have configured 4 quartz jobs which is epcected to get executed with below configuration.
Job 1 - every 5 minutes
Job 2 - every 4 minutes
Job 3 - every minute
Job 4 - every minute
Threadpool count - 3
misfireThreshold = 600000
quartz.misfire.instruction-2
clusterCheckinInterval- 20000

**Issue** - After bringing down databse for more that 10 minutes, none of the 4 schedulers are not up/running once database is brought up.
The issue is not observed, if the database is down < 10 minutes.

We tried below approach with details as below
1. Cleanup Qaurtz configuration - Clean up the exisitng configuration from database and re-run the sceanrio. The issue still persist.
2. change job 3 and job 4 scheduler frequency not keeping same configuration as below
Job 3 - every 2 minute
Job 4 - every minute
This helps with resolving the issue , however not sure if the above configuration causing issue anu issues with quartz API.

Appreciate any help resolving the issue.

**Comment by zemian** [comment]
This is not an issue/bug. Please using mailing list for question. My recommendation is to turn on debug logging and monitor the output to see why server won't start. I don't see any good reason why quartz will not start.
