### ISSUE TITLE
Typo tables_postgres.sql

### ISSUE THREAD

**Issue by Dartypier** [quartz-scheduler/quartz#1067]
There is a typo in the file `tables_postgres.sql` in `quartz-2.3.0-SNAPSHOT\src\org\quartz\impl\jdbcjobstore` folder distribuited with the .tar.gz archive in http://www.quartz-scheduler.org/downloads/files/quartz-2.3.0-distribution.tar.gz

In the 6th line there is a tick character, that shouldn't be there.

**Comment by melloware** [comment]
@jhouserizer this can be closed it was fixed long ago with: https://github.com/quartz-scheduler/quartz/issues/159
