### ISSUE TITLE
Trigger not firing 2.5.0-rc1 with JobStoreCMT

### ISSUE THREAD

**Issue by x-c4mp3r** [quartz-scheduler/quartz#1068]
I'm using Quartz 2.5.0-rc1 with JobStoreCMT & nonManagedTXDataSource

```
org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreCMT
org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate
org.quartz.jobStore.dataSource=quartzDataSource
org.quartz.dataSource.quartzDataSource.jndiURL=java:jboss/datasources/QuartzDs

org.quartz.jobStore.nonManagedTXDataSource=qzDS
org.quartz.dataSource.qzDS.jndiURL=java:jboss/datasources/QuartzNonManagedDs
```
the datasources setted in wildfly 29 standalone.
QuartzDs points to: jdbc:mysql://localhost:3406/dev_quartz
QuartzNonManagedDs points to: jdbc:mysql://localhost:3406/dev_quartz_non_managed

When I schedule a trigger with startNow() it didn't want to fire.
I debugged the quartz lib and I found that the trigger persisted in the QuartzDs in StdScheduler.java.scheduleJob() step,
but when the next trigger is acquired in QuartzSchedulerThread.java.run() it's executed in executeInNonManagedTXLock() method which creating a select statement in the QuartzNonManagedDs which is empty, because the previous step inserts into QuartzDs

```
SELECT TRIGGER_NAME, TRIGGER_GROUP, NEXT_FIRE_TIME, PRIORITY
FROM CLIP_TRIGGERS
WHERE SCHED_NAME = 'clip'
AND TRIGGER_STATE = 'WAITING'
AND NEXT_FIRE_TIME <= 1695644717428
AND (MISFIRE_INSTR = -1 OR (MISFIRE_INSTR <> -1 AND NEXT_FIRE_TIME >= 1695644638328))
ORDER BY NEXT_FIRE_TIME ASC, PRIORITY DESC
```
what am I doing wrong?
is QuartzDs and QuartzNonManagedDs need to point to the same database and same schema?
Thank you in advance!

**Comment by jhouserizer** [comment]
> is QuartzDs and QuartzNonManagedDs need to point to the same database and same schema?

Yes, this is mandatory for these to be the same.

**Comment by t-beckmann** [comment]
Even if both datasources are configured properly there is an issue with notifying the scheduler thread, see <https://github.com/quartz-scheduler/quartz/issues/1084>.
