### ISSUE TITLE
quartz fires duplicated job when the job running for more than 12 hours

### ISSUE THREAD

**Issue by wallacepeng** [quartz-scheduler/quartz#1070]
I have one job that can run for more than 12 hours while it is scheduled to run every 12 hours . It seems it always fires duplicated job even the job is annotated as @DisallowConcurrentExecution .

**Comment by wallacepeng** [comment]
it seems the job got recovered as the pod restarted sometimes, the recovered trigger can run at the same time as the cron trigger .

**Comment by jhouserizer** [comment]
Yes, recovering jobs can (unfortunately) run concurrently.  Job Recovery feature is not (very) compatible with Disallow Concurrent Execution feature.  See #1097
