### ISSUE TITLE
commit only if need commit

### ISSUE THREAD

**Issue by qxo** [quartz-scheduler/quartz#1077]
There no need connection commit for  misfireCount == 0 on doRecoverMisfires
https://github.com/quartz-scheduler/quartz/blob/a5c4d27e963f51097f9b2777489d310a88897ca4/quartz/src/main/java/org/quartz/impl/jdbcjobstore/JobStoreSupport.java#L3267

And if the no job triggered then no need commit:
https://github.com/quartz-scheduler/quartz/blob/a5c4d27e963f51097f9b2777489d310a88897ca4/quartz/src/main/java/org/quartz/impl/jdbcjobstore/JobStoreSupport.java#L3866

**Comment by jhouserizer** [comment]
The problem is that even though no rows were altered, the transaction is open (when the connection was first obtained and row locked) and needs a commit or rollback or it will hold others up and/or eventually timeout.
