### ISSUE TITLE
Make Quartz Kubernetes Friendly

### ISSUE THREAD

**Issue by sig-piskule** [quartz-scheduler/quartz#1079]
Quartz is inefficient when it comes to running on the cloud. The answers that I've seen around Quartz involve autoscaling, but that doesn't work well for me: what if there is a job that takes 8 hours to run, and in the middle of it, my Quartz pod autoscales down? What if I need 12GB RAM to ensure the job runs? And what if I need 3 of these to ensure peak load can be accomodated? There is no good solution for this.

Asking our developers to re-architect the entire application to use something cloud-friendly would mean waiting for various stakeholders to agree and schedule the work, and wait possibly years to have this done, while not delivering on customer features.

I was wondering how feasible it would be to make it so that rather than running Jobs on the same instance as Quartz is running, it merely asks Kubernetes to spin up a Pod that runs the job instead.

This drastically improves our scalability and bottom line, since rather than requiring multiple heavyweight Quartz managers that also run jobs, we could have a lightweight Quartz manager that instead schedules the jobs on Kubernetes.

I was *hoping* that this could be a simple fix; I was hoping that some core part of Quartz could be altered, such that rather than running the job in a thread, it could launch the pod instead. Scheduling, versus running the job could perhaps be temporarily hacked in by having a system property at startup to decide if this particular quartz instance is a job-runner, and if not all it does is launch pods.

This sounds easy to me, but I am not familiar with quartz. Can someone enlighten me on the viability of this feature, and perhaps point me to what would need to be changed to hack this in myself?

**Comment by ecki** [comment]
You can very easily implement a trigger which calls a web service or sends a jms message, already. For example starting a Kubernetes job or maybe more aproperiate start a FaaS payload.

**Comment by jhouserizer** [comment]
Previous comment is spot-on.
