### ISSUE TITLE
RAMJobStore.triggersFired where will let trigger be replaced between acquiring and firing？

### ISSUE THREAD

**Issue by UncleJuJu** [quartz-scheduler/quartz#1080]
i read source at RAMJobStore.triggersFired()，find a tip "in case trigger was replaced between acquiring and firing"，but i don't know where will let trigger be replaced.
storeTrigger() will replaced trigger, but the tw.state is STATE_WAITING, the triggersFired() will determine tw.state == STATE_ACQUIRED.
the tw.state be STATE_ACQUIRED only in acquireNextTriggers(), but if it be STATE_ACQUIRED, the timeTrigger will removed.
so why in triggersFired() will remove again?
Thank for all.

**Comment by jhouserizer** [comment]
Sorry, i don't immediately see any case where the condition could be true. Perhaps it was only true in earlier versions of the code, or it is a more subtle case around internal updates/rescheduling.
