### ISSUE TITLE
acquireTriggersWithinLock required for notifySchedulerThread

### ISSUE THREAD

**Issue by t-beckmann** [quartz-scheduler/quartz#1084]
I found that **acquireTriggersWithinLock** must be set because `QuartzScheduler.notifySchedulerThread(..)` runs in a not yet committed transaction which wakes the scheduler thread that will see changes only if it gets blocked by the lock at the database level.

Without aquiring the lock, the scheduler thread won't see changes until the transaction committed and the thread woke up due to idle timeout. That is, by default it can take up to 30s for newly triggered jobs to run even if Quartz has nothing else to do.

This was found using Quartz 2.3.2 with JobStoreCMT against MariaDB database.

**Comment by jhouserizer** [comment]
Thanks.  I added a note in the doc for now.
