### ISSUE TITLE
SQL Server doCheckIn for update error

### ISSUE THREAD

**Issue by zxzzhange** [quartz-scheduler/quartz#1095]
When quartz 2.2.3 was used to adapt sql server, this error was found in jobStoreSupport when doCheckIn(), but not in acquireNextTrigger(). Is it because org. Quartz. Impl. StdSchedulerFactory initialization time and the result of the lock handler is not set。
![333333](https://github.com/quartz-scheduler/quartz/assets/12606322/69c90fd8-7022-425a-b62f-602cb348dc0c)

![22222](https://github.com/quartz-scheduler/quartz/assets/12606322/6a5973e2-158f-48fc-aad6-49a707eb856d)

**Comment by melloware** [comment]
cc @amergey

**Comment by amergey** [comment]
@melloware my comment for this one https://github.com/quartz-scheduler/quartz/issues/1101#issuecomment-2453081834 
probably applies here as well

**Comment by melloware** [comment]
so this fixes it `select-with-lock-sql=SELECT * FROM {0}LOCKS UPDLOCK WHERE LOCK_NAME = ?` so shouldn't this be the default for the SQL Server Delegate?

**Comment by amergey** [comment]
@melloware If I understand the code correctly, when properly configured the default for SQL Server Delegate is already changed to the correctl sql for sqlserver 
SELECT * FROM {0}LOCKS WITH (UPDLOCK,ROWLOCK) WHERE " + COL_SCHEDULER_NAME + " = {1} AND LOCK_NAME = ?

see org.quartz.impl.jdbcjobstore.JobStoreSupport.initialize(ClassLoadHelper, SchedulerSignaler) line 668

**Comment by melloware** [comment]
@amergey weird looking at Git Blame that code has been there for 11 years so its strange its not being picked up?   We are using Quartz 2.3.2 in clustered mode so `useDbLocks=true` by default in clustered mode?

**Comment by melloware** [comment]
nevermind I see the issue!

**Comment by zxzzhange** [comment]
The source code was modified in the application, replacing the lockSQL with the statement "SELECT * FROM {0}LOCKS WITH (UPDLOCK, ROWLOCK) WHERE LOCK_NAME = ?" The problem has been solved.
