### ISSUE TITLE
Support Kingbase.  (Error Couldn't obtain triggers for job: Cannot convert the column of type BYTEA to requested type long.)

### ISSUE THREAD

**Issue by a1643977841** [quartz-scheduler/quartz#1096]
***
quartz version: 2.3.2
Springboot: 2.5.12
***

Our project recently switched the database from Mysql to Kingbase, but the following error occurred occasionally when performing the task. After my preliminary analysis, I feel that there is an abnormality in quartz. I am not sure. Please help me look at it.
Please see the attachment for three errors

[error1.txt](https://github.com/quartz-scheduler/quartz/files/13986291/error1.txt)
[error2.txt](https://github.com/quartz-scheduler/quartz/files/13986292/error2.txt)
[error3.txt](https://github.com/quartz-scheduler/quartz/files/13986293/error3.txt)

**Comment by mengshixing** [comment]
搞定了么 bro ,好难处理呀

**Comment by jhouserizer** [comment]
Seems like someone needs to develop table definitions and perhaps a sqlDelegate implementation for Kingbase.

**Comment by a1643977841** [comment]
I switched Kingbase JDBC to PostgreSQL JDBC problem solved

**Comment by melloware** [comment]
@jhouserizer this can be closed as KingBase is just PostgresSQL variant.
