### ISSUE TITLE
Distribution tar may be using older tar tool.  Causes "There are data after end of archive" warning in 7-Zip

### ISSUE THREAD

**Issue by bkalbfus** [quartz-scheduler/quartz#110]
This warning caused my concern for a little while.  I downloaded it twice and was wondering if there was a virus being added to the file.  I didn't see a checksum listed anywhere on the download page.

I downloaded http://d2zwv9pap9ylyd.cloudfront.net/quartz-2.2.3-distribution.tar.gz.  The warning message is reported by 7-zip. 7-zip is displaying the size of the quartz-2.2.3 folder as 21736587 and packed size as 22009856.

There have been a few other open-source projects using older tar implementations that trigger this warning.   Please see the following discussion as to why this may be happening.  

https://sourceforge.net/p/sevenzip/discussion/45797/thread/4286f2d1/

**Comment by jhouserizer** [comment]
Thanks for the tip.
