### ISSUE TITLE
Is there any plan about a GA Version if 2.4.0 or 2.5.0？

### ISSUE THREAD

**Issue by SakuruLIU** [quartz-scheduler/quartz#1106]
Is there any plan to release a new version?

**Comment by mesondzh** [comment]
I have the same problem.

**Comment by WHYlazymoon** [comment]
also waiting for new verison

**Comment by jixiang8320216** [comment]
Same question  for   new verison

**Comment by hw207165** [comment]
same question

**Comment by hw207165** [comment]
still RC version，any plan about GA version for jdk8 ?

**Comment by jhouserizer** [comment]
See https://github.com/quartz-scheduler/quartz/discussions/1166
