### ISSUE TITLE
I have two jobs set up daily at 7AM and 5PM. 7 AM job triggers as expected but 5PM Job is not triggering.

### ISSUE THREAD

**Issue by anilk-pws** [quartz-scheduler/quartz#1107]
Used this.

   public static async System.Threading.Tasks.Task StartAsync()
   {
       try
       {
           var scheduler = await StdSchedulerFactory.GetDefaultScheduler();
           if (!scheduler.IsStarted)
           {
               await scheduler.Start();
           }
           var job = JobBuilder.Create<DailyTaskService>()
             .WithIdentity("ExecuteTaskServiceCallJob1", "group1")
             .Build();
           var trigger = TriggerBuilder.Create()
             .WithIdentity("ExecuteTaskServiceCallTrigger1", "group1")
//GMT 1:30 is IST 7AM, GMT 11:30 is 5PM IST
             .WithCronSchedule("0 30 1,11 1/1 * ? *")
             .Build();

           await scheduler.ScheduleJob(job, trigger);
       }
       catch (Exception ex)
       {
       }
   }

**Comment by jonnybecker** [comment]
Hi [anilk-pws](https://github.com/anilk-pws), this is the Java implementation fork of quartz. You're asking in the wrong repo. Please close this question and ask it in https://github.com/quartznet/quartznet. Thanks
