### ISSUE TITLE
org.quartz.CronExpression.getTimeBefore

### ISSUE THREAD

**Issue by sd4324530** [quartz-scheduler/quartz#111]
When can this method be used?

**Comment by jhouserizer** [comment]
It's a protected method - it's not intended for use.

**Comment by jhouserizer** [comment]
Please ask usage questions in the user forum.  This is an issue (bug) tracker.

**Comment by sd4324530** [comment]
Oh, sorry, but it's a public method in quartz 2.2.3
`public Date getTimeBefore(Date endTime) { 
        // FUTURE_TODO: implement QUARTZ-423
        return null;
    }`

**Comment by XUPTLiYipeng** [comment]
CronExpression.getTimeBefore() method has been merged into main branch 
refer: https://github.com/quartz-scheduler/quartz/pull/1350
