### ISSUE TITLE
Package statements that do not correspond to the project directory structure

### ISSUE THREAD

**Issue by e210** [quartz-scheduler/quartz#1116]
The classes in the directory `quartz/src/main/java/org/quartz/ee/jboss` are referencing a package that does not match the actual structure. 
While not strictly mandated by the Java language, it's considered good practice.

**Comment by jhouserizer** [comment]
That's just weird and yucky.  Many years of precedence of it now for those files... will ponder about correcting it.

**Comment by bcode2** [comment]
Yeaa, quite strange that the bug is so old. I have just push a PR regarding this issue
