### ISSUE TITLE
Deadlock observed in quartz scheduler

### ISSUE THREAD

**Issue by devansatpat** [quartz-scheduler/quartz#112]
Hi,
I have configured quartz scheduler in a JBOSS 6.X EAP. 
I ran a sample program to create one job and three triggers that will run repeatedly every 5s.
When the quartz scheduler is running, repeated deadlock messages are seen in the log file sometime leading to BLOCKED state or ERROR state in quartz tables.

i am using mariadb and i have created the quartz tables with indexes using the db schema provided in the quartz/docs/dbtables.

quartz.properties:
--------------------
#============================================================================
# Configure Main Scheduler Properties
#============================================================================

org.quartz.scheduler.instanceName = MyScheduler
org.quartz.scheduler.instanceId = quartzsampler1

org.quartz.plugin.shutdownHook.class=org.quartz.plugins.management.ShutdownHookPlugin
org.quartz.plugin.shutdownHook.cleanShutdown = true

org.quartz.scheduler.userTransactionURL=java:jboss/UserTransaction

#============================================================================
# Configure ThreadPool
#============================================================================

org.quartz.threadPool.class = org.quartz.simpl.SimpleThreadPool
org.quartz.threadPool.threadCount = 1

#============================================================================
# Configure JobStore
# http://quartz-scheduler.org/documentation/quartz-2.2.x/configuration/ConfigJobStoreCMT
#============================================================================

org.quartz.jobStore.class = org.quartz.impl.jdbcjobstore.JobStoreTX
org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate
org.quartz.jobStore.useProperties = false
#org.quartz.jobStore.dataSource = JtaMySqlDS
#org.quartz.jobStore.nonManagedTXDataSource = MySqlDS
org.quartz.jobStore.dataSource = MySqlDS
org.quartz.jobStore.isClustered = true
org.quartz.jobStore.clusterCheckinInterval = 20000
org.quartz.jobStore.txIsolationLevelSerializable = true
#org.quartz.jobStore.txIsolationLevelReadCommitted = true
org.quartz.jobStore.lockHandler.class = org.quartz.impl.jdbcjobstore.UpdateLockRowSemaphore
#org.quartz.jobStore.acquireTriggersWithinLock = true
org.quartz.scheduler.skipUpdateCheck=true
org.quartz.jobStore.misfireThreshold = 60000

#============================================================================
# Configure data source
#============================================================================

#org.quartz.dataSource.JtaMySqlDS.jndiURL = java:/jdbc/MySqlDS
org.quartz.dataSource.MySqlDS.jndiURL = java:/jdbc/MySqlDS

show engine status
----------------------
| InnoDB |      |
=====================================
2017-03-16 02:10:06 7f7e69b6fb00 INNODB MONITOR OUTPUT
=====================================
Per second averages calculated from the last 41 seconds
-----------------
BACKGROUND THREAD
-----------------
srv_master_thread loops: 60439 srv_active, 0 srv_shutdown, 197721 srv_idle
srv_master_thread log flush and writes: 258159
----------
SEMAPHORES
----------
OS WAIT ARRAY INFO: reservation count 99595
OS WAIT ARRAY INFO: signal count 96180
Mutex spin waits 129082, rounds 2281507, OS waits 48367
RW-shared spins 46624, rounds 1373018, OS waits 45159
RW-excl spins 1541, rounds 148914, OS waits 4686
Spin rounds per wait: 17.67 mutex, 29.45 RW-shared, 96.63 RW-excl
------------------------
LATEST DETECTED DEADLOCK
------------------------
2017-03-15 03:09:20 7f7e69b6fb00
*** (1) TRANSACTION:
TRANSACTION 128959, ACTIVE 0 sec starting index read
mysql tables in use 1, locked 1
LOCK WAIT 4 lock struct(s), heap size 1184, 2 row lock(s)
MySQL thread id 28, OS thread handle 0x7f7e654b4b00, query id 2417169 172.29.39.183 root updating
UPDATE QRTZ_TRIGGERS SET TRIGGER_STATE = ? WHERE SCHED_NAME = 'MyScheduler' AND TRIGGER_NAME = ? AND TRIGGER_GROUP = ? AND TRIGGER_STATE = ?
*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 71 page no 3 n bits 112 index `PRIMARY` of table `quartz`.`QRTZ_TRIGGERS` trx table locks 2 total table locks 3  trx id 128959 lock_mode X locks rec but not gap waiting lock hold time 0 wait time before grant 0
*** (2) TRANSACTION:
TRANSACTION 128957, ACTIVE 0 sec starting index read
mysql tables in use 1, locked 1
9 lock struct(s), heap size 1184, 7 row lock(s)
MySQL thread id 29, OS thread handle 0x7f7e69b6fb00, query id 2417170 172.29.39.183 root updating
UPDATE QRTZ_TRIGGERS SET TRIGGER_STATE = ? WHERE SCHED_NAME = 'MyScheduler' AND TRIGGER_NAME = ? AND TRIGGER_GROUP = ? AND TRIGGER_STATE = ?
*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 71 page no 3 n bits 112 index `PRIMARY` of table `quartz`.`QRTZ_TRIGGERS` trx table locks 4 total table locks 3  trx id 128957 lock mode S lock hold time 0 wait time before grant 0
*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 71 page no 3 n bits 112 index `PRIMARY` of table `quartz`.`QRTZ_TRIGGERS` trx table locks 4 total table locks 3  trx id 128957 lock_mode X locks rec but not gap waiting lock hold time 0 wait time before grant 0
*** WE ROLL BACK TRANSACTION (1)
------------
TRANSACTIONS
------------
Trx id counter 184583
Purge done for trx's n:o < 184583 undo n:o < 0 state: running but idle
History list length 1998
LIST OF TRANSACTIONS FOR EACH SESSION:
---TRANSACTION 184580, not started
MySQL thread id 33, OS thread handle 0x7f7e69b0eb00, query id 2501242 172.29.39.183 root cleaning up
---TRANSACTION 183636, not started
MySQL thread id 32, OS thread handle 0x7f7e69b6fb00, query id 2501243 172.29.39.183 root init
SHOW ENGINE INNODB STATUS
---TRANSACTION 184579, not started
MySQL thread id 2, OS thread handle 0x7f7e69c24b00, query id 2501231 committed 82421
--------
FILE I/O
--------
I/O thread 0 state: waiting for completed aio requests (insert buffer thread)
I/O thread 1 state: waiting for completed aio requests (log thread)
I/O thread 2 state: waiting for completed aio requests (read thread)
I/O thread 3 state: waiting for completed aio requests (read thread)
I/O thread 4 state: waiting for completed aio requests (read thread)
I/O thread 5 state: waiting for completed aio requests (read thread)
I/O thread 6 state: waiting for completed aio requests (write thread)
I/O thread 7 state: waiting for completed aio requests (write thread)
I/O thread 8 state: waiting for completed aio requests (write thread)
I/O thread 9 state: waiting for completed aio requests (write thread)
Pending normal aio reads: 0 [0, 0, 0, 0] , aio writes: 0 [0, 0, 0, 0] ,
 ibuf aio reads: 0, log i/o's: 0, sync i/o's: 0
Pending flushes (fsync) log: 0; buffer pool: 0
308 OS file reads, 558774 OS file writes, 338859 OS fsyncs
0.00 reads/s, 0 avg bytes/read, 15.39 writes/s, 4.80 fsyncs/s
-------------------------------------
INSERT BUFFER AND ADAPTIVE HASH INDEX
-------------------------------------
Ibuf: size 1, free list len 0, seg size 2, 0 merges
merged operations:
 insert 0, delete mark 0, delete 0
discarded operations:
 insert 0, delete mark 0, delete 0
36.24 hash searches/s, 172.14 non-hash searches/s
---
LOG
---
Log sequence number 111089099
Log flushed up to   111089099
Pages flushed up to 111089099
Last checkpoint at  111089099
Max checkpoint age    80826164
Checkpoint age target 78300347
Modified age          0
Checkpoint age        0
0 pending log writes, 0 pending chkp writes
188198 log i/o's done, 2.80 log i/o's/second
----------------------
BUFFER POOL AND MEMORY
----------------------
Total memory allocated 140771328; in additional pool allocated 0
Total memory allocated by read views 424
Internal hash tables (constant factor + variable factor)
    Adaptive hash index 2250336         (2213368 + 36968)
    Page hash           139112 (buffer pool 0 only)
    Dictionary cache    761736  (554768 + 206968)
    File system         827504  (812272 + 15232)
    Lock system         333952  (332872 + 1080)
    Recovery system     0       (0 + 0)
Dictionary memory allocated 206968
Buffer pool size        8191
Buffer pool size, bytes 134201344
Free buffers            7198
Database pages          991
Old database pages      345
Modified db pages       0
Percent of dirty pages(LRU & free pages): 0.000
Max dirty pages percent: 75.000
Pending reads 0
Pending writes: LRU 0, flush list 0, single page 0
Pages made young 0, not young 0
0.00 youngs/s, 0.00 non-youngs/s
Pages read 162, created 829, written 321315
0.00 reads/s, 0.00 creates/s, 12.27 writes/s
Buffer pool hit rate 1000 / 1000, young-making rate 0 / 1000 not 0 / 1000
Pages read ahead 0.00/s, evicted without access 0.00/s, Random read ahead 0.00/s
LRU len: 991, unzip_LRU len: 0
I/O sum[0]:cur[52], unzip sum[0]:cur[0]
--------------
ROW OPERATIONS
--------------
0 queries inside InnoDB, 0 queries in queue
0 read views open inside InnoDB
0 RW transactions active inside InnoDB
0 RO transactions active inside InnoDB
0 out of 1000 descriptors used
Main thread process no. 7532, id 140179973068544, state: sleeping
Number of rows inserted 4325, updated 100418, deleted 4199, read 163067
0.59 inserts/s, 6.05 updates/s, 0.59 deletes/s, 10.78 reads/s
Number of system rows inserted 0, updated 0, deleted 0, read 0
0.00 inserts/s, 0.00 updates/s, 0.00 deletes/s, 0.00 reads/s
----------------------------
END OF INNODB MONITOR OUTPUT
============================

jboss console.log
-----------------------

[Server:server1] [0m[0m02:06:44,495 INFO  [MyJob] (MyScheduler_Worker-1) Trigger: my-jobs.trigger1, Fired at: 02:06:44, Instance: newquartz[0m
[Server:server1] [0m[0m02:06:44,506 INFO  [pl.codeleak.quartzdemo.ejb.SimpleEjb] (MyScheduler_Worker-1) Inside an EJB[0m
[Server:server1] [0m[31m02:06:44,553 ERROR [org.quartz.impl.jdbcjobstore.JobStoreTX] (MyScheduler_QuartzSchedulerThread) Couldn't rollback jdbc connection. Deadlock found when trying to get lock; try restarting transaction[0m
[Server:server1] [31mQuery is : set @@SQL_SELECT_LIMIT=DEFAULT: java.sql.SQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction[0m
[Server:server1] [31mQuery is : set @@SQL_SELECT_LIMIT=DEFAULT[0m
[Server:server1] [31m	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:127)[0m

**Comment by jhouserizer** [comment]
Which version of Quartz was this?

There has been no confirmed deadlock (caused by quartz) for several releases/versions (years now).   I'm not saying it isn't possible there isn't a bug -  I'm just saying that most often reports of deadlock are the result of either  1) some databases eagerly (and falsely) report "deadlock" if lock acquisition times out  2) some users write their own code that fiddle with quartz tables and create problems.

**Comment by ngaya-ll** [comment]
Seeing this as well in a legacy system using quartz 1.6.6 and mysql 5.5.

I think this may be due to a MySQL/InnoDB bug.
* https://bugs.mysql.com/bug.php?id=48652
* https://stackoverflow.com/questions/41015813/avoiding-mysql-deadlock-when-upgrading-shared-to-exclusive-lock

**Comment by ngaya-ll** [comment]
Setting `org.quartz.jobStore.acquireTriggersWithinLock=true` seems to prevent this issue.

**Comment by zemian** [comment]
Closing outdated, unresolved issues. Please, reopen if still relevant.

**Comment by praveensingh81** [comment]
> The query is SELCT * FROM QUARTZ_LOCKS WHERE SCHED_NAME = ? AND LOCK_NAME = ? FOR UPDATE

@zemian

**Comment by bharadwajturlapati** [comment]
I am facing the same issue. We are not sure what is causing deadlocks on the tables.

**Comment by zhuxindong** [comment]
so do i, when i  using oracle 11g, i have the same question,and i also find "segments by row lock waits" in oracle awr report:
| Object Name | Obj.Type | Row lock Waits |
| :--------------: | :---------: | :---------------: |
| QRTZ_LOCKS | TABLE | 2343 |

**Comment by PoonamAgarwalNews** [comment]
I face this issue when using a service in clustered mode (6 pods) where each service tries to initialize the schema with always. Each time innodb sql tries to drop few tables, create new tables and create indexes on tables. So, deadlock varies on which table we get. 
Invocation of init method failed; nested exception is org.quartz.JobPersistenceException: Couldn't store trigger.....
Deadlock found when trying to get lock; try restarting transaction [See nested exception: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction]

**Comment by rdomingonl** [comment]
Issue still exists, we also get a 'Deadlock found when trying to get lock; try restarting transaction' in clustered mode using mysql

**Comment by droni1234** [comment]
A workaround might be doing a release with a trigger name like 'trigger1' and when this gets locked rename it to 'trigger2' and do a new release. Another Idea I did have is that maybe setting the transactionIsolation level on the connection that is doing the initialization of the instance or pod to something more restrictive.
Maybe something like 'TRANSACTION_SERIALIZABLE' or 'TRANSACTION_REPEATABLE_READ' might help idk just an idea...

**Comment by pouring638** [comment]
@jhouserizer https://stackdev.space/questions/choosing-a-random-2-percent-of-rows-in-mysql-a-simple-guide

**Comment by LudBjork** [comment]
Issue still prevalent, we use a postgres database running on Postgres17 in the cloud. According to our cloud provider's stats the query
```SQL
SELECT * FROM qrtz_LOCKS WHERE SCHED_NAME = ? AND LOCK_NAME = ? FOR UPDATE
```
spends over 80% of the time waiting for the lock to be made available.
