### ISSUE TITLE
Broken links in the wiki

### ISSUE THREAD

**Issue by JP95Git** [quartz-scheduler/quartz#1123]
There are some links in the wiki/repo, which do not work:

https://github.com/quartz-scheduler/quartz/wiki
- Quartz 3.x Ideas -> You do not have permission to update this wiki. 

https://github.com/quartz-scheduler/quartz/wiki/Quartz-News-and-Blogs
- Both blogs are unavailable.

https://github.com/quartz-scheduler/quartz/blob/main/CONTRIBUTING.md
- Start your journey by reading here: Contributing -> This link points to CONTRIBUTING.md -> useless link

**Comment by jhouserizer** [comment]
Thanks!  (Each of these have had one thing or another done with them)
