### ISSUE TITLE
Wrong location of the SQL scripts for the jdbcjobstore in the documentation

### ISSUE THREAD

**Issue by JP95Git** [quartz-scheduler/quartz#1124]
The documentation at https://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/tutorial-lesson-09.html says

> You can find table-creation SQL scripts in the “docs/dbTables” directory of the Quartz distribution.

But this directory does not exists in any distribution of Quartz. The correct location can be found in GitHub:

https://github.com/quartz-scheduler/quartz/wiki/How-to-Setup-Databases

> The SQL files are located in quartz-core/src/main/resources/org/quartz/impl/jdbcjobstore directory.

This location is the correct one and works.

As with the other broken links in #1123 and #938, this issue exists since 2020.

**Comment by jhouserizer** [comment]
Fixed, thanks.
