### ISSUE TITLE
2.5.0-RC1: ClassCastException: org.quartz.plugins.xml.XMLSchedulingDataProcessorPlugin cannot be cast to org.quartz.jobs.FileScanListener

### ISSUE THREAD

**Issue by cstsw** [quartz-scheduler/quartz#1125]
I'm trying to port our quartz jobs to a recent version of Wildfly (31 under Java 17) and get the following error for a job declared in an XML-file:

`ERROR [org.quartz.core.JobRunShell] Job JobSchedulingDataLoaderPlugin.JobSchedulingDataLoaderPlugin_jobInitializer_hfdb-metax-schedule_xml threw an unhandled Exception: : java.lang.ClassCastException: class org.quartz.plugins.xml.XMLSchedulingDataProcessorPlugin cannot be cast to class org.quartz.jobs.FileScanListener (org.quartz.plugins.xml.XMLSchedulingDataProcessorPlugin and org.quartz.jobs.FileScanListener are in unnamed module of loader 'org.quartz@2.5.0-rc1' @1b4c3620)
        at org.quartz@2.5.0-rc1//org.quartz.plugins.xml.FileScanJob.execute(FileScanJob.java:101)
        at org.quartz@2.5.0-rc1//org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz@2.5.0-rc1//org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)`

Some background:
- In the past we have defined a custom Wildfly Module consisting of quartz-all-2.1.6.jar (along with dependency declarations to other Wildfly modules like javax.transaction.api etc.)
- For Wildfly 31 I created an updated Wildfly Module consisting of quartz-2.5.0-rc1.jar and quartz-jobs-2.5.0-rc1.jar. This is the first version containing Jakarta EE adaptions as of commit 217d1724e0fae72263b090219197818c775ad71e. (Recent Wildfly releases no longer feature the javax-namespaces of Java EE.)
- I obtained the JAR-Files from Maven Central.

My questions are:
- Have the JAR-Files quartz-2.5.0-rc1.jar and quartz-jobs-2.5.0-rc1.jar been produced by the same build and are they intended to be used together?
- Is the approach we took feasible from your perspective or do you see any obstacles?
- Is there a chance to release a fully Jakarta EE compatible*, final version of quartz? (*The aforementioned commit speaks only of an "initial set of changes to move to jakarta namespace".)

**Comment by cstsw** [comment]
A quick follow-up: the issue regarding the `FileScanListener` was (probably unintendedly) introduced in commit 6f37e295eeb474a2beb4d48e893014903599e703: since that commit the class `XMLSchedulingDataProcessorPlugin` implements `org.quartz.plugins.xml.FileScanListener` whereas formerly it implemented `org.quartz.jobs.FileScanListener`. Hence, the ClassCastException as printed in the stacktrace in the post above occurs when using quartz jobs defined in XML-files.

**Comment by j-blandford** [comment]
Same issue here. Our logs have been destroyed by this!

**Comment by jhouserizer** [comment]
I'm working on a fix for this.

**Comment by j-blandford** [comment]
Thank you @jhouserizer !
