### ISSUE TITLE
Special characters are unsupported

### ISSUE THREAD

**Issue by benjaminclauss** [quartz-scheduler/quartz#1132]
https://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html

A `CronTrigger` cannot be created containing special characters such as `L`, `W`, or `#`.

**Comment by jhouserizer** [comment]
?  what problem do you encounter?  do you have code to reproduce the issue?

**Comment by benjaminclauss** [comment]
At this point, I do not recall.
