### ISSUE TITLE
Quartz Scheduler is abandoned?

### ISSUE THREAD

**Issue by lprimak** [quartz-scheduler/quartz#1134]
Update: Quartz Scheduler was abandoned. - But not any longer.
---
Can anyone with knowledge shine light on this?
To me, it looks abandoned. No commits this year at all, CVEs not fixed, no issues answered, etc

Thank you

**Comment by Yannis-01** [comment]
the same inquiry

**Comment by IOhacker** [comment]
x3

**Comment by lprimak** [comment]
@RichardBradley Thank you for pointing this out. Looks more and more abandoned to me.

**Comment by lprimak** [comment]
2 weeks with no response?
I think the conclusion is obvious. Quartz Schedule is abandoned.

**Comment by bmertens911** [comment]
@lprimak @RichardBradley @Yannis-01 @IOhacker @Yannis-01 @vmptk @cunhaax - we've switched to https://github.com/jobrunr/jobrunr years ago and could not have been happier. Better performance, new features, an integrated dashboard and if you take a Pro version (which we needed for workflow support), you also get awesome support.

**Comment by pbartoszek** [comment]
[bmertens911](https://github.com/bmertens911) jobrunr looks very nice. However open source free version doesn't seem to support transactional jobs :(. Pro version does support @Transactional and costs only $15k per year...

**Comment by lprimak** [comment]
Please stay on topic.
The fact that jobrunr folks want to get paid for their work is not applicable to this particular discussion.
This post isn't really meant as a recommendation for other projects or products in the space please.

**Comment by melloware** [comment]
@lprimak i agree the lack of a release cadence from a corporate back library is disappointing. However if you look at the branches there is a 2.4x branch they have been working on that supports Jakarta and has had more recent commits than 5 years ago.

**Comment by lprimak** [comment]
There hasn't been a commit to any branches in a year and 3 months.
Sorry, but it's clearly abandoned and I just don't see this being resurrected at all.
Anybody can make a fork I guess, but I just don't see this happening

**Comment by melloware** [comment]
@lprimak i agree its dissapointing.  I have Quartz in a few mission critical applications since 2014.

If you are looking for an alternative this one is Open Source but not as full featured as Quartz: https://github.com/lukas-krecan/ShedLock

**Comment by bcode2** [comment]
I have been used version 2.4.0-rc2 without any issue almost for a year, but I agree, it seems the project updates goes very slowly.
I just ask myself why those companies that use it do not contribute to the project. (Donations or code updates)

**Comment by lprimak** [comment]
@melloware I feel your pain. I know this sucks. We have the same issue with Apache Shiro.
However, with security framework, we can't have dependencies where CVEs are not fixed.

Just to make my point clearer for others reading this:

Unfortunately, thinking that Quartz Scheduler will have **any** updates or releases in the future is just wishful thinking.

According to my (and others) research, maintainers were (are?) employed by Software AG,
who is no longer sponsoring this project. It is clear that all maintainers moved on for over a year.
If there was another company / entity who was interested in hiring the maintainers to work on this,
it would have happened already.
I also don't see the maintainers transferring ownership to anyone else to avoid the "xz" security issue, it's just too much risk.

If this was Apache project (I am Apache PMC member) this would have been long in the Attic.
However, GitHub doesn't have such provisions, so if maintainers don't touch the project, nor will they archive it,
it'll just sit there without any hint of it's "abandonment"

This is why I created this issue in the first place, to hopefully inform people of the facts of where Quartz stands.

All of this is unfortunate, and I don't like it anymore than anyone else, but facts need to be stated.

**Comment by melloware** [comment]
As a note I volunteered years ago to be a committer and also perform releases for Quartz and they rejected the idea. I know they said they were looking for help but I guess they were not serious about it. 

Also the fact that it was purchased by Terracotta and then it looks like purchased by Software AG it seems they don't care. It's not mentioned anywhere on the software AG site.

**Comment by melloware** [comment]
OK some good news.  I know someone who is in contact with Software AG and we may have some progress on this in the near-ish future.

**Comment by bcode2** [comment]
Excellent!!!!,. If the project goes ahead and there will be someone reviewing  and accepting pull requests count on me to do some contributions.

**Comment by lprimak** [comment]
While I am hopeful that @melloware gets somewhere with this,
I would urge caution until the actual CVEs are fixed.

**Comment by gklijs** [comment]
https://github.com/kagkarlsson/db-scheduler is another nice alternative..

**Comment by lprimak** [comment]
And let's not forget that Jakarta EE has robust scheduling features built in.

**Comment by jcputney** [comment]
It has scheduling features, but I don't know if I would go so far as to call them robust

**Comment by melloware** [comment]
Expect an update soon-ish...

**Comment by linghengqian** [comment]
> we've switched to https://github.com/jobrunr/jobrunr years ago and could not have been happier. Better performance, new features, an integrated dashboard and if you take a Pro version (which we needed for workflow support), you also get awesome support.

- At least on the ASF project side, it is not possible to use `jobrunr/jobrunr`. `jobrunr/jobrunr` uses `LGPL-3.0-only`, which means that for ASF projects, it can only be used in unit tests and build processes. See https://www.apache.org/legal/resolved.html .

**Comment by wilx** [comment]
I see that some work towards the Jakarta namespace has been done on `main`. What is missing for a new release to happen?

**Comment by melloware** [comment]
@wilx i think there are some steps that need to happen.

1. Release the current 2.4.0 as an official release.
2. Then work on a 2.5.0 release for Jakarta.
3. Review all PR's and create a 3.0 on JDK21 and VirtualThreads.

That is just my two cents.

**Comment by dellagustin-sap** [comment]
I found this recently: https://github.com/quartz-scheduler/quartz-scheduler.org-site/commit/ca9b8a38757ddd1df5cb18e8f4547525362ba3f6
It seems that quartz was transferred to IBM, together with other IPs (see https://newsroom.ibm.com/2024-07-01-IBM-Completes-Acquisition-of-StreamSets-and-webMethods,-Bolstering-its-Automation,-Data-and-AI-Portfolios).

**Comment by jhouserizer** [comment]
Yes, IBM has acquired a group of products from Software AG , of which Quartz comes along in the collection.   The past years within SAG have led to some legal stalemates around contributions and other matters that stifled progress.  Once we have policy/procedures/re-copyrighting, etc. (e.g. for CLA/DCO, etc.) in place we should be able to get Quartz moving again.

**Comment by jhouserizer** [comment]
Questions were answered/clarified.  Contribution terms, dco, etc. and PR template was updated.

I have closed all open PRs with the comment "Unfortunately, due to the change of ownership of this project, the terms of contribution have been updated, and this PR will need to be re-created, agreeing to the new terms."

**Comment by jhouserizer** [comment]
There is a weird situation where currently copyright ownership is set (in file headers etc.) to "Copyright Super iPaaS Integration LLC, an IBM Company 2024", and on January 1st it will need to be changed to "Copyright IBM 2025".   Fun!

**Comment by jhouserizer** [comment]
I have started a discussion areas for those of you anxious to get official 2.4.0 and 2.5.0 releases out - help us identify what needs to be done.  My time is still limited and there's a lot of open stuff to wade through - not so easy to quickly identify what matters.   Also feel free to indicate volunteering to tackle something.

**Comment by melloware** [comment]
@lprimak probably safe to close this ticket as we know its not abandoned anymore

**Comment by lprimak** [comment]
I think so... I think the release can be made :) which is a real test

**Comment by bcode2** [comment]
I am not agree there is a bunch of things to migrate and refactoring, I guess with the current speed of PR approved,in a couple of weeks would be fine
