### ISSUE TITLE
Unable to scrape metrics using JMX exporter

### ISSUE THREAD

**Issue by ganesh-arkalgud** [quartz-scheduler/quartz#1137]
Some commonly used metric scraper like [JMX Exporter](https://github.com/prometheus/jmx_exporter) also rely on implementation of MBean to help gather metrics. Quartz already has support for the same.

However, they further rely on data structures like [TabularData](https://cr.openjdk.org/~jlaskey/java.management/javax/management/openmbean/TabularData.html) and [CompositeData](https://cr.openjdk.org/~jlaskey/java.management/javax/management/openmbean/CompositeData.html) from the management package itself to scrape metrics. Some of the methods exposed in the QuartzMBean including the [getPerformanceMetrics](https://www.quartz-scheduler.org/api/2.1.7/org/quartz/core/QuartzSchedulerMBeanImpl.html#getPerformanceMetrics()) and [getAllTriggers](https://www.quartz-scheduler.org/api/2.1.7/org/quartz/core/QuartzSchedulerMBeanImpl.html#getAllTriggers()) cannot be scraped since scraping a List or Map is not supported by JMX.

**Comment by lprimak** [comment]
This project is abandoned. See #1134

**Comment by jhouserizer** [comment]
This would be a feature enhancement, feel free to submit a PR if you wish.
