### ISSUE TITLE
IsSatisfiedBy in sql

### ISSUE THREAD

**Issue by samer1977** [quartz-scheduler/quartz#1139]
Hi,
I'm interested in running the IsSatisfiedBy function in ms sql. I tried to implement sql clr functiion using .net code however when I try to import the quartz dll as external assembly it turns out it's dependent on a lot of references wither directly or through other dependencies.is there another way where I can transfer this function to sql?

**Comment by samer1977** [comment]
Can someone help me with this please?

**Comment by lprimak** [comment]
This project is abandoned. See #1134

**Comment by jhouserizer** [comment]
Based on your question, you're in the wrong place - this is not Quartz .NET
