### ISSUE TITLE
PostgreSQL SQL Migration Documentation Issue

### ISSUE THREAD

**Issue by esetnik** [quartz-scheduler/quartz#114]
The `table_postgres.sql` should use `DROP TABLE IF EXISTS` syntax so that initial migration can be run on a new database.

```
DROP TABLE IF EXISTS qrtz_fired_triggers;
DROP TABLE IF EXISTS QRTZ_PAUSED_TRIGGER_GRPS;
DROP TABLE IF EXISTS QRTZ_SCHEDULER_STATE;
DROP TABLE IF EXISTS QRTZ_LOCKS;
DROP TABLE IF EXISTS qrtz_simple_triggers;
DROP TABLE IF EXISTS qrtz_cron_triggers;
DROP TABLE IF EXISTS qrtz_simprop_triggers;
DROP TABLE IF EXISTS QRTZ_BLOB_TRIGGERS;
DROP TABLE IF EXISTS qrtz_triggers;
DROP TABLE IF EXISTS qrtz_job_details;
DROP TABLE IF EXISTS qrtz_calendars;
```

**Comment by jhouserizer** [comment]
fine suggestion, thanks.

**Comment by esetnik** [comment]
Sorry about not submitting a PR. I didn't realize these scripts were contained in the repo. Thanks for the fix @jhouserizer.

**Comment by Ramblurr** [comment]
I think there was a typo in that commit: https://github.com/quartz-scheduler/quartz/pull/128/files#r115279504

**Comment by esetnik** [comment]
good catch @Ramblurr looks like it's a typo

**Comment by rraziel** [comment]
Hello, that typo noticed by @Ramblurr went into the 2.3.0 release.
