### ISSUE TITLE
Quartz Scheduler not working running for a specific time period

### ISSUE THREAD

**Issue by AshwinSM** [quartz-scheduler/quartz#1150]
We have a quartz scheduler which has a repeat interval of 5 mins that has been running in production for more than 7years. Suddenly we noticed the schedular doesn't trigger at a particular interval from 6am to 10am. After few days the interval got bigger and now it doesn't run between 12:30am to 10:30am. 
The Interesting part is this scheduler works perfectly fine in one of the server and the above issue in noted only in other server.

Your insights would be of great help

**Comment by jhouserizer** [comment]
My only guess is that the problem is with the locale/tz settings on the machine (os) that is having problems.   Have never heard of anyone having any remotely similar problem.
