### ISSUE TITLE
MisfireHandler cannot recover any triggers if one misfired trigger has errors

### ISSUE THREAD

**Issue by dzhg** [quartz-scheduler/quartz#1152]
This is similar to #48.

In JobStoreSupport.java, `recoverMisfiredJobs` method has a loop:

```
        for (TriggerKey triggerKey: misfiredTriggers) {
            
            OperableTrigger trig = 
                retrieveTrigger(conn, triggerKey);

            if (trig == null) {
                continue;
            }

            doUpdateOfMisfiredTrigger(conn, trig, false, STATE_WAITING, recovering);

            if(trig.getNextFireTime() != null && trig.getNextFireTime().getTime() < earliestNewTime)
                earliestNewTime = trig.getNextFireTime().getTime();
        }
```

It calls `retrieveTrigger` and might throw an exception due to an invalid cron expression, for example.

Then, the entire transaction will be rolled back as there is no error/exception handling in the loop.

It will result in a defunct misfire recovery. It will run into an infinite state that tries to recover the same misfired triggers without success. All other valid triggers will not be recovered and will be stuck forever.

Questions:
1. Is this a known issue and by design?
2. If so, could you please share the background and the reason behind the decision?
3. Can we handle the `retrieveTrigger` exception in the loop and unblock the other valid triggers by skipping the erroneous ones?

Thank you!

**Comment by lahma** [comment]
In .NET version we made such changes to ensure more robust handling: https://github.com/quartznet/quartznet/pull/1040

**Comment by jhouserizer** [comment]
I think this is known and intentional, but probably can be improved as noted.

**Comment by ohksj77** [comment]
Fix PR: https://github.com/quartz-scheduler/quartz/pull/1260
