### ISSUE TITLE
Implement CronExpression.getTimeBefore() method

### ISSUE THREAD

**Issue by amichair** [quartz-scheduler/quartz#1155]
There's PR https://github.com/quartz-scheduler/quartz/pull/777 implementing it that's been waiting around for 2.5 years... no maintainer ever responded to it, and then the stale bot closed it for 'lack of activity' :-/

Please merge it, or respond to it if there's any reason not to.

**Comment by jhouserizer** [comment]
See new comment on the PR - it will need to be recreated.

**Comment by amichair** [comment]
Please re-open, the PR has been re-created as PR #1350.
