### ISSUE TITLE
Job is executed more then specified repeat count

### ISSUE THREAD

**Issue by nitulkukadia** [quartz-scheduler/quartz#1160]
I have scheduled a job for 2 time execution only. But it is executed 3 times.

```
package org.example;

import org.quartz.JobDetail;
import org.quartz.Scheduler;
import org.quartz.SimpleScheduleBuilder;
import org.quartz.Trigger;
import org.quartz.impl.StdSchedulerFactory;

import java.util.Calendar;
import java.util.Date;

import static org.quartz.JobBuilder.newJob;
import static org.quartz.SimpleScheduleBuilder.simpleSchedule;
import static org.quartz.TriggerBuilder.newTrigger;

public class MainWithIssue {
    public static void main(String[] args) {
        try {
            Scheduler scheduler = StdSchedulerFactory.getDefaultScheduler();
            scheduler.start();
            JobDetail job = newJob(HelloJob.class)
                    .withIdentity("job1", "group1")
                    .build();

            Calendar cal = Calendar.getInstance();
            cal.add(Calendar.SECOND , 5);
            SimpleScheduleBuilder schedBuilder = simpleSchedule()
                    .withIntervalInSeconds(1)
                    .withRepeatCount(2);

            Trigger trigger = newTrigger()
                    .withIdentity("trigger1", "group1")
                    .startAt(cal.getTime())
                    .withSchedule(schedBuilder)
                    .build();
            scheduler.scheduleJob(job, trigger);
            System.out.println("Scheduled a job " + new Date());
            Thread.sleep(30000);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

package org.example;

import org.quartz.Job;
import org.quartz.JobExecutionContext;
import org.quartz.JobExecutionException;

import java.util.Date;

public class HelloJob implements Job {

    public static Integer i = 0;

        @Override
        public void execute(JobExecutionContext context) throws JobExecutionException {
            System.out.println("Executing the task " + new Date() + " ==" + ++i);
        }
    }

```

Logs:

`
[main] INFO org.quartz.impl.StdSchedulerFactory - Using default implementation for ThreadExecutor
[main] INFO org.quartz.core.SchedulerSignalerImpl - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
[main] INFO org.quartz.core.QuartzScheduler - Quartz Scheduler v2.5.0-rc1 created.
[main] INFO org.quartz.simpl.RAMJobStore - RAMJobStore initialized.
[main] INFO org.quartz.core.QuartzScheduler - Scheduler meta-data: Quartz Scheduler (v2.5.0-rc1) 'MyScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 3 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

[main] INFO org.quartz.impl.StdSchedulerFactory - Quartz scheduler 'MyScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
[main] INFO org.quartz.impl.StdSchedulerFactory - Quartz scheduler version: 2.5.0-rc1
[main] INFO org.quartz.core.QuartzScheduler - Scheduler MyScheduler_$_NON_CLUSTERED started.
Scheduled a job Thu Oct 03 16:34:22 IST 2024
Executing the task Thu Oct 03 16:34:27 IST 2024 ==1
Executing the task Thu Oct 03 16:34:28 IST 2024 ==2
Executing the task Thu Oct 03 16:34:29 IST 2024 ==3

`

Version:
```
<dependency>
            <groupId>org.quartz-scheduler</groupId>
            <artifactId>quartz</artifactId>
            <version>2.5.0-rc1</version>
        </dependency>
```

**Comment by konopka** [comment]
Works as expected, you've scheduled it to run once + 2 more repetitions.
See documentation: https://github.com/quartz-scheduler/quartz/blob/9035cb472a15f34b378e8e0c41aa428350b0188b/quartz/src/main/java/org/quartz/SimpleScheduleBuilder.java#L329

But the javadoc is also not entirely correct and should be fixed, i.e this line https://github.com/quartz-scheduler/quartz/blob/9035cb472a15f34b378e8e0c41aa428350b0188b/quartz/src/main/java/org/quartz/SimpleScheduleBuilder.java#L331 is wrong

**Comment by nitulkukadia** [comment]
Hi @konopka  Why it is one more time instead of specified. 
I think need to correct the execution count instead of documentation.

**Comment by konopka** [comment]
Hi @nitulkukadia 
do read the javadoc again on `withRepeatCount` function. It is doing exactly what it is supposed to do, i.e add additional repetitions.
Even in the sample code you provided you have this comment 
```
// Trigger the job to run now, and then repeat every 2 seconds
SimpleScheduleBuilder schedBuilder = simpleSchedule()
    .withIntervalInSeconds(1)
    .withRepeatCount(2);
```
i.e. run now and then repeat two times.
btw. I guess this `withIntervalInSeconds(1)` should have 2 as a parameter to match the expectation in the comment above ...
and if your expectation is that the job runs twice in total, then use `withRepeatCount(1)`

**Comment by nitulkukadia** [comment]
Hi @konopka  Thanks for the correction, 
1. I have updated the code to run every 1 second for 2 times
2. I understand the javadoc, as you said there will be an additional repetition, so if I specify 2 it will get executed 3 times.  I can set to withRepeatCount(1) to make it 2. 

But, why there is an additional repetition?  Should it be same as what is specified.

**Comment by konopka** [comment]
@nitulkukadia There is no additional repetition. Look at dictionary what the word repeat means: https://www.merriam-webster.com/dictionary/repeat
It is 1 execution + n repetitions, like the javadoc says ...

**Comment by nitulkukadia** [comment]
Hi @konopka  What is the reason of extra this 1 execution ? Why not only n repetitions.

**Comment by nitulkukadia** [comment]
This should be n repetitions.

**Comment by KenroLe** [comment]
With a grain of pedantic salt you could claim that the first run is not a repetition and only the subsequent runs are repetitions.
Whether it should be like this or not is a matter of taste.

**Comment by jhouserizer** [comment]
I think this is a matter of usage of english, at any rate, it is definitely working as expected/designed and documented.    For the vast majority of USA English speakers, if something happens once, it has repeated zero times.  If something happens twice, there has been one repeat of it.
 
Noted the tangential javadoc language issue, thanks @konopka
