### ISSUE TITLE
[Oracle 23] VARCHAR2(1) breaking change

### ISSUE THREAD

**Issue by dcdh** [quartz-scheduler/quartz#1161]
**Current behavior**

Job can no more be registered inside job detail table.

```
Caused by: org.quartz.JobPersistenceException: Couldn't store job: ORA-12899: valeur trop grande pour la colonne "QUARKUS"."QRTZ_JOB_DETAILS"."IS_DURABLE" (réelle : 5, maximum : 1)
```

**Expected behavior**

Job should be stored and next executed as expected.

**Additional information**

Oracle 23 has introduced a breaking change regarding the way a boolean is represented.
Before Oracle 23 a boolean used a **VARCHAR2(1)** and this way has been supported from many years by the oracle jdbc driver.

Now, Oracle 23 has introduced a new type **BOOLEAN** to represent a boolean type.
But, the driver is no more compatible - except if an additional property is used to deactivate the new way to handle boolean type.

Full story here with a reproducer : https://github.com/quarkusio/quarkus/issues/43720

**How to fix**

Provide an update script for Oracle database 23 and plus to update boolean columns **VARCHAR2(1)** to **BOOLEAN**
or
provide a new full initialization tables for Oracle database 23 and plus.

Multiples tables are impacted.

Regards,
Damien

**Comment by melloware** [comment]
@dcdh looking for a PR here...
