### ISSUE TITLE
@DisallowConcurrentExecution mis-interpretation on clustered Scheduler

### ISSUE THREAD

**Issue by rfelgent** [quartz-scheduler/quartz#117]
Hello people,

according to the documentation the @DisallowConcurrentExecution works based on JobKey definition:

> An annotation that marks a {@link Job} class as one that must not have multiple
> instances executed concurrently (where instance is based-upon a {@link JobDetail} 
> definition - or in other words based upon a {@link JobKey}).

I have one class implementing the Job interface which I create multiple instances of.
The creation makes sure, that the JobKey has different names within the same group.
(I verified the JobKeys persisted in the database). Also I configured 10 worker threads.

Anyway, the quartz does not execute the job multiple time in different threads. The logs contain a lot of "trigger misfire handle" messages.

I am afraid, that the the job class is interpreted and not the jobkey for the @DisallowConcurrentExecution. May be, this problem is specifically related to clustered jobstore and not the in-memory jobstore?

Best regards

**Comment by jhouserizer** [comment]
All the logic is certainly tied to the job key.   Which jobstore are you using specifically?

**Comment by rfelgent** [comment]
org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX

**Comment by jhouserizer** [comment]
Thanks for confirming.  No logic is based on job class / class name.  Only on keys.

I really have no solid guess at what might be happening in your case.  How long does the job take to execute, and while it is executing can you check if the triggers related to the other job detail instances go into the BLOCKED state  (this would be in the _triggers table).

The only other thing I can think of that would prevent them from firing is:  having been paused (triggers would be in PAUSED state),  or no available worker threads (but you said you have 10).

**Comment by rfelgent** [comment]
I could prepare a unit test/test case if you do not mind. 
Would you have a deeper look into it then?

**Comment by jhouserizer** [comment]
Yes, if it's readily reproducible then I would really like to have a look!

**Comment by rfelgent** [comment]
Hello @jhouserizer ,

I have set up an example project.

https://github.com/rfelgent/springboot-quartz-example

I am _afraid_, that your assumption is right. 
The scheduler is working correctly considering @DisallowConcurrentExecution. 
During my project setup, I realized, that the mistake in my production code is somewhere else...

We can close this issue. Thx for your help!

**Comment by svrolanski** [comment]
Some times you need to schedule the same job with different parameters at different times and you need to handle the overlapping yourself. @DisallowConcurrentExecution should cover such use case.
