### ISSUE TITLE
Job Execution Timeout

### ISSUE THREAD

**Issue by garrit-schroeder** [quartz-scheduler/quartz#118]
It would be absolutely fantastic if some kind of Job Execution Timeout would be implemented.
For example a job has a maximum lifetime of 30 Minuets or so.

Maybe someone has a great workaround for that.
At the moment i am opening another thread and use the Future.get() with a Timeout. 
Which is not soo great i guess.
Thx a lot.

**Comment by jhouserizer** [comment]
See PR #115 .

Note that there's no way that Quartz can kill a running job - the JVM doesn't provide a way to kill a thread.  All we can do is send an interrupt signal, and the job itself needs to periodically check for the signal and exit itself.
