### ISSUE TITLE
[Q] Plans to release new version?

### ISSUE THREAD

**Issue by grossws** [quartz-scheduler/quartz#119]
Previos release was quite long ago and there's still no release with commit which [removed updatechecker](https://github.com/quartz-scheduler/quartz/commit/e1f78465fae7d3e81d30487f7f47697ec9a30d87).

When do you plan to release new version or there's no such plans yet?

**Comment by jhouserizer** [comment]
Hi!  We plan to release 2.3.0 in about 2 weeks.

Also, please do not use the issue tracking system for questions.  This same topic has been getting coverage in the community group / mail list.

**Comment by grossws** [comment]
@jhouserizer, ok, thanks. 

I thought to search info there but it's closed for unregistered users and her we are.
