### ISSUE TITLE
ClassNotFoundException thrown when triggers are fired for two different jobs belonging to  two different EARs

### ISSUE THREAD

**Issue by devansatpat** [quartz-scheduler/quartz#120]
Hi,

I am using quartz scheduler clustering in a clustered jboss 6 eap. 

I have packaged the quartz libraries inside an ear and its deployed in clustered jboss. Now i have the ejb bean class (its singleton and initialized at start-up) that i am using to start, stop and schedule the quartz. This i have packaged as a ejb jar. 

Now I have app1.ear and app2.ear. The packaging in my app1.ear is 
app1.ear --> ejb jar 
                 --> myapp1.war ( this has a dependency on the ejb jar and has a job1 class)

The packaging in my app2.ear is 
app2.ear --> ejb jar
                 --> myapp2.war ( this has a dependency on the ejb jar and has its own job2 class)

when i deploy app1.ear and app2.ear, job1 and job2 are persisted and trigger are fired for couple of seconds for both the jobs. Then i get a classnotfoundexception where the quartz is looking for job1 class in app2.ear and job2 class in app1.ear

Please help how to resolve this classloading issue.

Quartz properties
#============================================================================
# Configure Main Scheduler Properties
#============================================================================

org.quartz.scheduler.instanceName = myscheduler
org.quartz.scheduler.instanceId = AUTO

org.quartz.plugin.shutdownHook.class=org.quartz.plugins.management.ShutdownHookPlugin
org.quartz.plugin.shutdownHook.cleanShutdown = true

org.quartz.scheduler.userTransactionURL = java:jboss/UserTransaction

#org.quartz.scheduler.rmi.export: false
#org.quartz.scheduler.rmi.proxy: false
#org.quartz.scheduler.wrapJobExecutionInUserTransaction: true
org.quartz.jobStore.dontSetAutoCommitFalse=true

#============================================================================
# Configure ThreadPool
#============================================================================

org.quartz.threadPool.class = org.quartz.simpl.SimpleThreadPool
org.quartz.threadPool.threadCount = 10
org.quartz.threadPool.threadPriority: 5
org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread: true
org.quartz.scheduler.threadsInheritContextClassLoaderOfInitializer = true

#============================================================================
# Configure JobStore
# http://quartz-scheduler.org/documentation/quartz-2.2.x/configuration/ConfigJobStoreCMT
#============================================================================

org.quartz.jobStore.class = org.quartz.impl.jdbcjobstore.JobStoreCMT
org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate
org.quartz.jobStore.useProperties = false
org.quartz.jobStore.dataSource = JtaQuartzDS
org.quartz.jobStore.nonManagedTXDataSource = QuartzDS
org.quartz.jobStore.isClustered = true
org.quartz.jobStore.clusterCheckinInterval = 5000
org.quartz.jobStore.txIsolationLevelSerializable = true
org.quartz.jobStore.txIsolationLevelReadCommitted = true
org.quartz.jobStore.misfireThreshold = 60000
org.quartz.scheduler.dbFailureRetryInterval = 3000

#============================================================================
# Configure data source
#============================================================================

org.quartz.dataSource.JtaQuartzDS.jndiURL = java:jboss/datasources/JtaQuartzDS
org.quartz.dataSource.QuartzDS.jndiURL = java:jboss/datasources/QuartzDS****

**Comment by jhouserizer** [comment]
This is a usage question and should be asked in the user forum.

You have a typical java class loader issue.   If you're creating the scheduler at a more global scope - so that both applications use the same instance, then you also need to put all the job classes (and their dependencies) at that same global scope.
