### ISSUE TITLE
Redundant check

### ISSUE THREAD

**Issue by e210** [quartz-scheduler/quartz#1209]
https://github.com/quartz-scheduler/quartz/blob/199c8f1111f2034f208300a8f9b372a9f37cf74f/quartz/src/main/java/org/quartz/impl/triggers/DailyTimeIntervalTriggerImpl.java#L875-L882

You have two checks that verify whether daysOfWeek is null or empty, but the second check (else if(daysOfWeek.isEmpty())) is redundant because you've already checked for the same condition in the previous line.

**Comment by jhouserizer** [comment]
Well, one has to be sure.  :D

**Comment by melloware** [comment]
PR submitted

**Comment by bcode2** [comment]
there is  a conversation exactly about this https://github.com/quartz-scheduler/quartz/pull/1206#discussion_r1803349355

**Comment by jhouserizer** [comment]
Fixed with #1211
