### ISSUE TITLE
Language-Dependent Test

### ISSUE THREAD

**Issue by e210** [quartz-scheduler/quartz#1213]
I discovered a trivial bug in the tests that makes them language-dependent. Specifically, the tests fail when the system language is not set to English. The issue arises from an assertion that checks an exception message, which changes based on the system's locale.

The problematic test is as follows:

https://github.com/quartz-scheduler/quartz/blob/199c8f1111f2034f208300a8f9b372a9f37cf74f/quartz/src/test/java/org/quartz/xml/XMLSchedulingDataProcessorTest.java#L379

In non-English locales (e.g., Italian and yes, I might be a little biased here 🇮🇹), the exception message might be localized, and the text "DOCTYPE is disallowed" would be translated to something like "DOCTYPE non è consentito". This causes the test to fail because the assertion is checking for the English message only.

To reproduce the issue, you can run the following command to trigger the test failure when the language is set to Italian:

```shell
./gradlew clean && ./gradlew :quartz:test --tests "org.quartz.xml.XMLSchedulingDataProcessorTest.testXmlParserConfiguration" -Duser.language=it
```

This will cause the test to fail because the error message in the exception is localized to Italian.

To make the test pass, you can switch back to English by running the following:

```shell
./gradlew clean && ./gradlew :quartz:test --tests "org.quartz.xml.XMLSchedulingDataProcessorTest.testXmlParserConfiguration" -Duser.language=en
```

## Proposed Solution:

To fix this issue and make the tests locale-independent, one approach is to configure the test environment to always use English as the language. This can be done by setting the `user.language` property during test execution

Alternatively, you can apply this globally by adding it to your gradle.properties file:

```
org.gradle.jvmargs=-Duser.language=en
```
Another option is to relax the test's assertion by checking for just the key part of the message (like "DOCTYPE") instead of the full exception message.

```java
assertTrue(e.getMessage().toLowerCase().contains("doctype"));
```

**Comment by jhouserizer** [comment]
Thanks, probably the latter is best, because who know what the jvm arg might subtly affect elsewhere.
