### ISSUE TITLE
ISchedulerListener is firing twice for events.

### ISSUE THREAD

**Issue by DRAirey1** [quartz-scheduler/quartz#1269]
I have a simple scheduler that I'm loading from an SQL table (that resembles the Quartz records):

```
            // Create, configure and start the scheduler.
            this.scheduler = await this.schedulerFactory.GetScheduler(cancellationToken);
            this.scheduler.JobFactory = this.jobFactory;
            this.scheduler.ListenerManager.AddSchedulerListener(this.schedulerListener);
            await this.scheduler.Start(cancellationToken).ConfigureAwait(false);

```

I've verified with logging that this code is only run once. I've verified with logging that the job is only running once.
The listener is a trivial implementation of an IScheduleListener:

```
        /// <inheritdoc/>
        public async Task JobAdded(IJobDetail jobDetail, CancellationToken cancellationToken = default)
        {
            this.logger.LogInformation($"Starting ({jobDetail.Key.Group}, {jobDetail.Key.Name}).");
        }
        

```
When I run this program, I get:

```
info: ThetaRex.Market.Jobs.JobService[0]
      Starting (ETrade, Start Quote Service Job).
info: ThetaRex.Market.Jobs.JobService[0]
      Starting (ETrade, Start Quote Service Job).

```

The listener task is getting called twice for every job I add and twice for every job that is deleted.

**Comment by melloware** [comment]
@DRAirey1 is this .NET code?  This is the Java library GitHub you want Quartz.Net which is not related to this project.

**Comment by DRAirey1** [comment]
That's for the observation. I've posted it on the Quartz.net site. Had no idea there were two different products. You can close this case out.

**Comment by melloware** [comment]
Can you close it I don't have permissions and you opened the ticket?
