### ISSUE TITLE
Does quartz support oracle at the 12c version? The current OracleDelegate supports 10 and 11 versions 

### ISSUE THREAD

**Issue by simfol59** [quartz-scheduler/quartz#13]

**Comment by jhouserizer** [comment]
Have you tried it?  It should work.

**Comment by zemian** [comment]
I have tested latest Quartz on Oracle DB 12.1.0.2.0 and it worked fine. I don't think org.quartz.impl.jdbcjobstore.oracle.OracleDelegate is using anything specific that 12 won't work, even though the current javadoc says only 10 and 11. Perhaps we can should remove the specific version from javadoc to avoid confusion.

**Comment by simfol59** [comment]
Thank you. I have tried and it works.
