### ISSUE TITLE
Trigger getting BLOCKED - prevents the scheduler to run the job again

### ISSUE THREAD

**Issue by allanpro** [quartz-scheduler/quartz#134]
Hi,

we have a job that is run every 2 minutes. The job syncs appointments from our database to an Exchange server. On an arbitrary time during a week the trigger gets BLOCKED and the scheduler stops running the job. Then we do the following: 

1. Delete the row from QRTZ_FIRED_TRIGGERS.
2. Delete the trigger from our web-interface.
3. Add a new CronTrigger from our web-interface.

Then everything works again until next time...

**Other information**
ExchangeJob has @DisallowConcurrentExecution annotation

This is the way we start the scheduler which runs in a server farm with one Oracle Database.
```
        // Configure Main Scheduler Properties
        props.put("org.quartz.scheduler.instanceName", "MyClusteredScheduler");
        props.put("org.quartz.scheduler.instanceId", "AUTO");

        // Configure ThreadPool
        props.put("org.quartz.threadPool.class", "org.quartz.simpl.SimpleThreadPool");
        props.put("org.quartz.threadPool.threadCount", "25");
        props.put("org.quartz.threadPool.threadPriority", "5");

        // Configure JobStore
        props.put("org.quartz.jobStore.misfireThreshold", "60000");
        props.put("org.quartz.jobStore.class", "org.quartz.impl.jdbcjobstore.JobStoreTX");
        props.put("org.quartz.jobStore.driverDelegateClass", "org.quartz.impl.jdbcjobstore.StdJDBCDelegate");
        props.put("org.quartz.jobStore.useProperties", "true");
        props.put("org.quartz.jobStore.dataSource", "MyDS");
        props.put("org.quartz.jobStore.tablePrefix", "QRTZ_");
        props.put("org.quartz.jobStore.isClustered", "true");

        // Configure Datasources
        props.put("org.quartz.dataSource.MyDS.jndiURL", JndiUtil.DATASOURCE_MAIN);
        props.put("org.quartz.dataSource.MyDS.java.naming.factory.initial", "org.jboss.as.naming.InitialContextFactory");
```
And now for the questions:

1) I bet it is hard for anyone to pinpoint the problem right away... so just a common question. How can a trigger lockup in BLOCKED state without ever recovering?

2) Would it help to set TRACE level for Quartz packages in the log files?

Hope anyone reads this as we are pretty stuck...

Best regards
Allan

**Comment by icyerasor** [comment]
See #145 with possible PR including the fix.
Let's move the disucssion there?

**Comment by MSudheer87** [comment]
@allanpro  Are you able to get this issue fixed ?
I am facing similar issue. Can you please help me ?

@icyerasor

**Comment by zemian** [comment]
Closing as dup and fixed by #145

**Comment by rubal18** [comment]
Any clue here? We are facing same issue

**Comment by NEXTick** [comment]
> Any clue here? We are facing same issue

haha me too
