### ISSUE TITLE
quartz not execute

### ISSUE THREAD

**Issue by werwolfGu** [quartz-scheduler/quartz#139]
The application will throw a ' java.util.concurrent.CompletionException: java.lang.OutOfMemoryError: Java heap space' exception, after GC, the application can run successfully. But quartz will not execute on time.

**Comment by zemian** [comment]
Thank you for using Quartz! 

Please use Users Discussion for general questions, and not the Issue tracker on GitHub. Use Issue tracker ONLY if you think you have found a bug or submitting feature requests. For more info, please see https://github.com/quartz-scheduler/quartz/wiki/How-To-Submit-New-Issue
