### ISSUE TITLE
Comment on CompletedExecutionInstruction. SET_TRIGGER_ERROR

### ISSUE THREAD

**Issue by aeneid** [quartz-scheduler/quartz#14]
Seems to me like the comments on CompletedExecutionInstruction. SET_TRIGGER_ERROR and CompletedExecutionInstruction. SET_ALL_JOB_TRIGGERS_ERROR should be switched.
Am I missing anything?

**Comment by ramaraochavali** [comment]
I addressed this issue in the PR https://github.com/quartz-scheduler/quartz/pull/137
