### ISSUE TITLE
Why scheduling classes instead of objects?

### ISSUE THREAD

**Issue by zeroflag** [quartz-scheduler/quartz#140]
Hi,

Based on the documentation this is a typical usage of Quartz.

```java
JobDetail job = newJob(MyJob.class)
      .withIdentity("job1", "group1")
      .build();
[...]
```

MyJob is instantiated by Quartz which makes difficult to pass dependencies to it via the constructor. I wonder what is the idea behind this design decision. Passing objects around instead of classes would make the API easier and safer to use. This just adds seemingly unnecessary complexities. Is there a strong technical reason for doing this way?

**Comment by ramaraochavali** [comment]
You can implement your custom JobFactory to instantiate your job the way you want including all dependencies. You can implement the JobFactory interface and supply to Quartz by specifying the property org.quartz.scheduler.jobFactory.class.

**Comment by zeroflag** [comment]
Thansk for your answer. I still think this is an unnecessary complication, but at least it is possible.

**Comment by ramaraochavali** [comment]
If you are using RAMJobStore, it is possible to schedule with Object rather than class. But if you are using other persistent job stores, I do not think it is a good idea to schedule with objects as it leads to more complications in object serialization etc.
