### ISSUE TITLE
Spelling mistake in Quartz 2.2.x Docs

### ISSUE THREAD

**Issue by laudukang** [quartz-scheduler/quartz#141]
1.
URL:  http://www.quartz-scheduler.org/documentation/quartz-2.2.x/tutorials/tutorial-lesson-02.html
Origin: The block of code that builds the job definition is using methods that were statically imported from the JobBuilder class. Likewise, the block of code that builds the trigger is using methods imported from the TriggerBuilder class - as well as from the **SimpleScheduleBulder** class.

Last second word "SimpleScheduleBulder " should be "SimpleScheduleBuilder".

2.
URL: http://www.quartz-scheduler.org/documentation/quartz-2.2.x/tutorials/tutorial-lesson-07.html
Origin: For your convenience, **tather** than implementing those interfaces, your class could also extend the class JobListenerSupport or TriggerListenerSupport and simply override the events you’re interested in.

word "tather" should be "rather"

**Comment by zemian** [comment]
Fixed by PR #371
