### ISSUE TITLE
Download link on www.quartz-scheduler.org is outdated

### ISSUE THREAD

**Issue by veita** [quartz-scheduler/quartz#143]
It links to the 2.2.3 version.

http://www.quartz-scheduler.org/downloads/

**Comment by microsby0** [comment]
A LOT of the documentation on the site seems out of date.

**Comment by zemian** [comment]
I will start updating the WIKI with more up to date info

https://github.com/quartz-scheduler/quartz/wiki

**Comment by ChristianCiach** [comment]
The website still links to the 2.3 downloads. Why not just take it offline if it is unmaintained?
