### ISSUE TITLE
Hi, where do we see the document of  version 2.3 ?

### ISSUE THREAD

**Issue by xuxueli** [quartz-scheduler/quartz#150]

**Comment by msymons** [comment]
I was also spent quite a while looking for documentation.   I cannot find anything in github and the [documentation page on the website](http://www.quartz-scheduler.org/documentation/) has not been updated for v2.3 (and still links to JIRA).

**Comment by denis111** [comment]
Yes, we need to know if we should apply any changes to our code for upgrading to 2.3 but there's no way to know it?

**Comment by madness-inc** [comment]
This is really disappointing. It's now two month since the release of 2.3.0, and still there is zero changelog/documentation available :-(
As far as I can see in the changelog, it's only changes in pom.xml (search for "2 month ago"):
https://github.com/quartz-scheduler/quartz/blame/quartz-2.3.0/pom.xml

**Comment by zemian** [comment]
Hi all. Yeah unfortunately, our documentation is not up-to-date with latest release. I will try to add/update the WIKI more often from now on with best I can.

As far as I know there is no DB schema changes in 2.3.0 release, and are mostly bug fixes. Try search through the closed issues for a fixed list. For precise changes, you would have to do git diff between the two releases. 

I agree that we should put up a release doc for better user experience.

**Comment by zemian** [comment]
Most of the issues for 2.3.0 are started after we moved into github, and I have collected them here: https://github.com/quartz-scheduler/quartz/milestone/1

Will try to better track issues with next release.

**Comment by zemian** [comment]
BTW, one of the reason we bump 2.3 is we use JDK7 instead of JDK6.

**Comment by ragoley** [comment]
@zemian If you are now using JDK7 for the project, why are you importing the much older -java6 version of HikariCP?  I have personally dealt with issues that required our projects to utilize the 2.4.13 release compared to the 2.3.13 version that 2.3.0 is using.

**Comment by zemian** [comment]
Hi, sorry for the long delay. We now have few open issues relating to cleanup documentation.

Also there is a `changelog.md` file as part of each active branch in tracking changes now.

I hope these help. I will close this issue for now. Please open new issue if you face particular problem.
