### ISSUE TITLE
DB_VALIDATE_ON_CHECKOUT cannot be set anymore in 2.3.0

### ISSUE THREAD

**Issue by Eredian** [quartz-scheduler/quartz#154]
The parameter org.quartz.dataSource.NAME.validateOnCheckout when configured is still sent to C3p0PoolingConnectionProvider and initialized, however the parameter was removed in 2.3.0 from the default properties in StdSchedulerFactory.populateProviderWithExtraProps.

Because of that the scheduler factory attempts to set the property validateOnCheckout, but there is no setter for that property in AbstractComboPooledDataSource.

The issue should be fixed by putting back the parameter validateOnCheckout in StdSchedulerFactory.populateProviderWithExtraProps. 

As a workaround setting org.quartz.dataSource.NAME.TestConnectionOnCheckin to false and org.quartz.dataSource.NAME.TestConnectionOnCheckout to true seems to have the same effect.

Related commit : https://github.com/quartz-scheduler/quartz/commit/db21e2b0f9c919f5e8baf91c8f97098a5ad40e90

**Comment by jebeaudet** [comment]
any update on this issue? Thanks

**Comment by bernieatenovlab** [comment]
I'm also having this issue. Has there been any progress?

**Comment by zemian** [comment]
Hi, this should now be fixed as #281 in all of our active branches
