### ISSUE TITLE
Add Docs for Adding a custom Delegate Class in properties file

### ISSUE THREAD

**Issue by isangieri** [quartz-scheduler/quartz#158]
I wrote a custom Delegate class that's a subclass of `StdJDBCDelegate`, but its unclear from the docs how to specify a custom Delegate class.

**Comment by zemian** [comment]
See "org.quartz.jobStore.driverDelegateClass" in http://www.quartz-scheduler.org/documentation/quartz-2.2.x/configuration/ConfigJobStoreTX.html
