### ISSUE TITLE
Ver 2.2.5 -  Scheduler skips an entire day in scheduling

### ISSUE THREAD

**Issue by PBalla** [quartz-scheduler/quartz#165]
We are using Quartz Scheduler to schedule many jobs. Every once in an year the scheduler skips an entire day for the jobs. 

For example: if the CRON entry for a job is  0 5 0 ? * TUE-SAT , this means the job should run every weekday starting tuesday at 00:05:00am... however, when it tried to schedule this on 03 Jul, it skipped 04 Jul entirely and scheduled the jobs for 5 Jul. Please note that there are no holiday calendars associated with this. 

The same happened on all our dev, sit uat and prod environments. The same issue happened in October last year. 

Below is the entry from our logs:

```
[INFO] 03 Jul 09:04:22.931 PM server.com-startStop-1 [com.app.business.scheduler.impl.ScheduleMgrImpl]
AppJobGroup.PriorDayCalculations has been scheduled to run at: Wed Jul 05 00:05:00 EDT 2017 and repeat based on expression: 0 5 0 ? * TUE-SAT
```

**Comment by zemian** [comment]
Cron trigger is subject to DST adjustment, so ensure if that's not your case.

**Comment by PBalla** [comment]
@zemian  Thanks for the clue. But DST doesnt change in Jul. So I had to eliminate it from the possible causes.

**Comment by zemian** [comment]
HI @PBalla sorry for the long delay respond. 

Unfortunately what you have given is not enough to debug the problem. We need your cron expression, your quartz configuration and any app log relating to your problem. Best if you can recreate this in a standalone test where we can verify.

**Comment by zemian** [comment]
Closing outdated, unresolved issues. Please, reopen if still relevant.
