### ISSUE TITLE
How can I change BLOB data of QUARTZ tables?

### ISSUE THREAD

**Issue by AlvarMayor** [quartz-scheduler/quartz#167]
I must extend a windows service written years ago in C# with Visual Studio from another, unknown, developer. (no way to ask to him)
This Service uses Quartz 2.2.400.0.
Configuration is saved on the Quartz tables inside a SQL Server 2008 database.
This is the Quartz configuration:

```
 <quartz>
    <add key="quartz.scheduler.instanceName" value="EwinJobScheduler" />
    <add key="quartz.threadPool.threadCount" value="10" />
    <add key="quartz.threadPool.threadPriority" value="2" />
    <add key="quartz.jobStore.misfireThreshold" value="60000" />
    <add key="quartz.jobStore.type" value="Quartz.Impl.AdoJobStore.JobStoreTX, Quartz" />
    <add key="quartz.jobStore.driverDelegateType" value="Quartz.Impl.AdoJobStore.StdAdoDelegate, Quartz" />
    <add key="quartz.jobStore.tablePrefix" value="QRTZ_" />
    <add key="quartz.jobStore.dataSource" value="myDS" />
    <add key="quartz.dataSource.myDS.connectionString" value="Data Source=WIN764\SQL2012;Initial Catalog=Gare;User ID=sa;password=sql2012" />
    <add key="quartz.dataSource.myDS.provider" value="SqlServer-20" />
    <add key="quartz.jobStore.useProperties" value="false" />
  </quartz>
```

Part of the configuration is "hidden" inside BLOB data in the Quartz 
tables, QRTZ_JOB_DETAILS and QRTZ_TRIGGERS, in binary format.
And here I have problems.
The jobs of the service receive parameters from the code, and these 
parameters are overwritten by parameters hidden inside the BLOB data.

In code I pass something like this:
{"ProcessManualCheck":false,"UserName":"Admin","IDCategoria":0,"NumInizio":0,"NumFine":0}
and my parameters are overriden by parameters hidden in the BLOB data:
{"ProcessManualCheck":false,"UserName":"Admin"}
loosing all the new properties.

I tried a RAW solution: load blob data in byte[], convert to string, 
change the string, convert back to byte[] and then update the blob.

```
BufOrig = (byte[])MyRow["Job_Data"];
StrOrig = System.Text.Encoding.UTF8.GetString(BufOrig);
StrDest = StrOrig.Replace("{\"ProcessManualCheck\":false,\"UserName\":\"Admin\"}", "{\"ProcessManualCheck\":false,\"UserName\":\"Admin\",\"IDCategoria\":0,\"NumInizio\":0,\"NumFine\":0}");
BufDest = System.Text.Encoding.UTF8.GetBytes(StrDest);
```

All OK until i run the service ... when I see this error:
ERROR Quartz.Core.ErrorLogger [EwinJobScheduler_QuartzSchedulerThread] 
[Error] - An error occurred while scanning for the next trigger to fire.
Quartz.JobPersistenceException: Couldn't acquire next trigger: Couldn't 
retrieve trigger: No map for object '201326592'. ---> 
Quartz.JobPersistenceException: Couldn't retrieve trigger: No map for 
object '201326592'. ---> 
System.Runtime.Serialization.SerializationException: No map for object 
'201326592'.
   in 
System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObject()
   in 
System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
...

How can I change the JOB_DATA fields in the Quartz tables?

**Comment by zemian** [comment]
This is not for Java Quartz project. Close as invalid issue.
