### ISSUE TITLE
CronTriggerImpl doestn't respect the daylight setting of timezone when it set it's  start time

### ISSUE THREAD

**Issue by ShakespeareLiu** [quartz-scheduler/quartz#169]
here is the source code in  CronTriggerImpl.java

 @Override
    public void setStartTime(Date startTime) {
        if (startTime == null) {
            throw new IllegalArgumentException("Start time cannot be null");
        }

        Date eTime = getEndTime();
        if (eTime != null && eTime.before(startTime)) {
            throw new IllegalArgumentException(
                "End time cannot be before start time");
        }
        
        // round off millisecond...
        // Note timeZone is not needed here as parameter for
        // Calendar.getInstance(),
        // since time zone is implicit when using a Date in the setTime method.
        Calendar cl = Calendar.getInstance();
        cl.setTime(startTime);
        cl.set(Calendar.MILLISECOND, 0);

        this.startTime = cl.getTime();
    }
if is in the repeat time of DST and we have a job whoes  first fired time should be in repeat time, and  timeZone of CronTriggerImpl is UTC. But in fact is will be fired after repeat time cause the start time is set by Calendar. Calendar doesn't know it's daylight time or not, it will all take them as normal time. the start time is set to  future time in UTC, maybe one hour later. the first fired time is caculated to next next cycle.
I think we'd better  change  this.startTime = cl.getTime() to  this.startTime = new Date()

**Comment by liubao68** [comment]
This seems a JDK issue but not a quartz issue. After round off milliseconds, it is one hour later after startTime.

**Comment by ShakespeareLiu** [comment]
yes, better to use:

        // round off millisecond...
        // Note timeZone is not needed here as parameter for
        // Calendar.getInstance(),
        // since time zone is implicit when using a Date in the setTime method.

        long tempTime = startTime.getTime()/1000*1000;
        this.startTime = new Date(tempTime);

**Comment by zemian** [comment]
Closing outdated, unresolved issues. Please, reopen if still relevant.
