### ISSUE TITLE
Hello everyone, I based on quartz encapsulates a distributed task scheduling platform, called XXL JOB

### ISSUE THREAD

**Issue by xuxueli** [quartz-scheduler/quartz#17]
Hello everyone, I based on quartz encapsulates a distributed task scheduling platform, called "XXL-JOB"。
The purpose is to contribute to open source, welcome you all to use。
大家好，我基于quartz封装了一个分布式任务调度平台，叫做 “XXL-JOB” 。
目的是为开源做贡献，欢迎大家使用啊。
https://github.com/xuxueli/xxl-job

**Comment by jhouserizer** [comment]
Not an "issue" with quartz.
