### ISSUE TITLE
while running Quartz jar threads are going to TIMED_WAITING (on object monitor)

### ISSUE THREAD

**Issue by velmayil** [quartz-scheduler/quartz#173]
There is a web project on jboss eap6.4.11 which running quartz job 2.2.3. in thread dump we getting like this .

could you please guide us for that issues.

"DefaultQuartzScheduler_Worker-7" prio=6 tid=0x000000001706d000 nid=0x2424 in Object.wait() [0x00000000185df000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000000e7725818> (a java.lang.Object)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
        - locked <0x00000000e7725818> (a java.lang.Object)

   Locked ownable synchronizers:
        - None

"DefaultQuartzScheduler_Worker-6" prio=6 tid=0x0000000017064000 nid=0x317c in Object.wait() [0x00000000184df000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000000e7725648> (a java.lang.Object)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
        - locked <0x00000000e7725648> (a java.lang.Object)

   Locked ownable synchronizers:
        - None

"DefaultQuartzScheduler_Worker-5" prio=6 tid=0x000000001707a800 nid=0x1cc8 in Object.wait() [0x00000000183df000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000000e771b430> (a java.lang.Object)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
        - locked <0x00000000e771b430> (a java.lang.Object)

   Locked ownable synchronizers:
        - None

"DefaultQuartzScheduler_Worker-4" prio=6 tid=0x0000000017064800 nid=0x2f90 in Object.wait() [0x0000000015e7f000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000000e771b260> (a java.lang.Object)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
        - locked <0x00000000e771b260> (a java.lang.Object)

   Locked ownable synchronizers:
        - None

"DefaultQuartzScheduler_Worker-3" prio=6 tid=0x0000000017069800 nid=0x2cf0 in Object.wait() [0x000000001596f000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000000e771b090> (a java.lang.Object)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
        - locked <0x00000000e771b090> (a java.lang.Object)

   Locked ownable synchronizers:
        - None

"DefaultQuartzScheduler_Worker-2" prio=6 tid=0x0000000017065800 nid=0x31e0 in Object.wait() [0x000000001576f000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000000e771aec0> (a java.lang.Object)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
        - locked <0x00000000e771aec0> (a java.lang.Object)

   Locked ownable synchronizers:
        - None

"DefaultQuartzScheduler_Worker-1" prio=6 tid=0x0000000017068800 nid=0x2814 in Object.wait() [0x0000000013d4f000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000000e771acf0> (a java.lang.Object)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
        - locked <0x00000000e771acf0> (a java.lang.Object)

   Locked ownable synchronizers:
        - None

**Comment by zemian** [comment]
These are normal thread states running Quartz.

Also, please use Users Discussion for general questions, and not the Issue tracker on GitHub. Use Issue tracker ONLY if you think you have found a bug or submitting feature requests. For more info, please see https://github.com/quartz-scheduler/quartz/wiki/How-To-Submit-New-Issue
