### ISSUE TITLE
导入quartz源码到eclipse中遇到的问题

### ISSUE THREAD

**Issue by OnlyChange** [quartz-scheduler/quartz#18]
quartz-terracotta-system-tests
Description Resource    Path    Location    Type
Project build error: Non-resolvable parent POM for org.quartz-scheduler.internal:quartz-terracotta-system-tests:2.2.4-SNAPSHOT: Failure to find org.terracotta:system-tests-parent:pom:4.3.2-SNAPSHOT in http://www.terracotta.org/download/reflector/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of terracotta-snapshots has elapsed or updates are forced and 'parent.relativePath' points at no local POM pom.xml /quartz-terracotta-system-tests line 11 Maven pom Loading Problem

**Comment by zemian** [comment]
Can you please clarify your issue in English?

**Comment by zemian** [comment]
Close as invalid

**Comment by bfwq** [comment]
![image](https://github.com/user-attachments/assets/3080d316-c30f-4795-8293-aa25f10a0b49)

**Comment by bfwq** [comment]
Do I need to run unit tests in the quartz-terracotta-system-tests module to adapt my database product
