### ISSUE TITLE
The same trigger with EXECUTINGstate in QRTZ_FIRED_TRIGGERS while with COMPLETE state in QRTZ_TRIGGERS 

### ISSUE THREAD

**Issue by darouwan** [quartz-scheduler/quartz#181]
Why does the same trigger have different state in the same time?

**Comment by simonovdenis** [comment]
I'm facing the same issue. System is stuck with a lot of rows in QRTZ_FIRED_TRIGGERS table, which are in EXECUTING state, and corresponding rows in QRTZ_TRIGGERS table are in COMPLETE state.
Did you find the solution or at least workaround for that?
