### ISSUE TITLE
 "failure obtaining db row lock :lock wait timeout exceeded try restarting transaction" problem 

### ISSUE THREAD

**Issue by darouwan** [quartz-scheduler/quartz#188]
I meet " failure obtaining db row lock :lock wait timeout exceeded try restarting transaction problem " error message when some jobs will be triggered. It seems a thread doesn't release the row lock and block the following job triggers. 

How to avoid this problem ? and when it occurs, how to solve it? 

google group ref:https://groups.google.com/forum/#!category-topic/quartz-scheduler/triggers--scheduling-questions/9A32WVWymq0

**Comment by zemian** [comment]
Closing outdated, unresolved issues. Please, reopen if still relevant.

**Comment by zemian** [comment]
See related #268
