### ISSUE TITLE
Hi, which maximum version of Quartz API is available for Spring 3.2.0?

### ISSUE THREAD

**Issue by aksh2143** [quartz-scheduler/quartz#194]
Hi, which maximum version of Quartz API can i use for spring 3.2.0 and Java6 in My project?
Currently i am using Quarts 1.8.6 with Spring 3.2.0 and Java 6. Upto which version i can upgrade quartz?

**Comment by zemian** [comment]
Hi, you should check the Spring doc and use their dependency requirement.
