### ISSUE TITLE
 Cursors still opened in DB session after shutdown scheduler

### ISSUE THREAD

**Issue by REDIDEMIA** [quartz-scheduler/quartz#196]
hi,

When stoping our server, we stop quartz scheduler using  .scheduler.shutdown(true); as described in quartz documentation :

http://www.quartz-scheduler.org/documentation/quartz-2.x/cookbook/ShutdownScheduler.html

but we observe that cursors opened  in Oracle DB session are not stoped for those queries even after 2 hours :

UPDATE QRTZ_SCHEDULER_STATE SET LAST_CHECKIN_TIME = :1  WHER

SELECT * FROM QRTZ_SCHEDULER_STATE WHERE SCHED_NAME =

SELECT COUNT(TRIGGER_NAME) FROM QRTZ_TRIGGERS WHERE SCHED_NA

SELECT TRIGGER_NAME, TRIGGER_GROUP, NEXT_FIRE_TIME, PRIORITY

 SELECT COUNT(TRIGGER_NAME) FROM NCLS_TRIGGERS WHERE SCHED_NA

Do you have idea about this problem?

thanks.

**Comment by zemian** [comment]
Closing outdated, unresolved issues. Please, reopen if still relevant.
