### ISSUE TITLE
Support JSR-236 ManagedExecutorService

### ISSUE THREAD

**Issue by jwgmeligmeyling** [quartz-scheduler/quartz#200]
I am wondering about the status of [QTZ-473](https://jira.terracotta.org/jira/browse/QTZ-473). There seems to be a patch, but I don't think it ever got merged.

> The JSR-236 spec (part of the Java EE 7) makes it into the application servers (see the list at http://www.oracle.com/technetwork/java/javaee/overview/compatibility-jsp-136984.html ) and becomes the standard to run asynchronous tasks in Java EE application server environments.
> 
> Therefore Quartz Scheduler should be able to make use of the JSR-236 ManagedExecutorService for all its threads - that means job threads as well as the main scheduler and MisfireHandler and ClusterManager ones.
> 
> https://jcp.org/en/jsr/detail?id=236

**Comment by mocleiri** [comment]
I tried to apply the patch on QTZ-473  It was missing a class called **org.quartz.impl.ThreadExecutorSupport**

Other than the missing file the patch did apply cleanly on the quartz-2.2.2 tag.

That tag corresponds to svn revision 2470 http://svn.terracotta.org/svn/quartz/tags/quartz-2.2.2/

**Comment by hostalp** [comment]
@sammyhk Is that QTZ-473.patch (https://jira.terracotta.org/browse/QTZ-473) your patch? Could you please add the missing class org.quartz.impl.ThreadExecutorSupport into it?

**Comment by AlbozDroid** [comment]
So what's the current status here? Seems like we all need this feature.
Is it possible to configure Quartz to use the ManagedExecutorService and ManagedScheduledExecutorService?

**Comment by JWGmeligMeyling** [comment]
QTZ-473 included a patch, which was however incomplete and as its very old I would be surprised if it was still compatible. However, this should be fairly easy to implement: just find the spot where the executor service is initialised, and prepend a check to see whether a managed executor service is available, and if so, use that instead.

Personally I was only using a couple of features from quartz, and have since replaced my `@Scheduled` methods with EJB `@Schedule` Timers, which also gave me clustering and persistent timers for free.

**Comment by AlbozDroid** [comment]
Do you have an example of how you did it? The Quartz scheduler persists the job on DB so even on server re-start it still works... Is your solution just in memory?

**Comment by JWGmeligMeyling** [comment]
The annotation works very similar to the one provided by Quartz, see for example: https://github.com/wildfly/quickstart/blob/master/ejb-timer/src/main/java/org/jboss/as/quickstarts/ejbTimer/ScheduleExample.java

Whether or not it is persistent, depends on your EJB container implementation. For example WildFly allows you to attach a JDBC datasource to the EJB subsystem which is then used to implement persistent timers, that work in the cluster as well. See also: https://docs.jboss.org/author/display/WFLY/EJB3+Clustered+Database+Timers . I don’t remember from the top of my head whether default store is in-memory or file based and thus already persistent but simply not clustered, but this is probably configurable too.

**Comment by hostalp** [comment]
Some time ago I created the following simple implementation that we've been successfully using since then.

It can be used as a simple replacement of the existing CommonJ `WorkManagerThreadExecutor` so you can use the same property `org.quartz.threadExecutor.workManagerName` to specify the JNDI name of the desired managed executor service (otherwise it falls back to the default `java:comp/DefaultManagedExecutorService`).

I'm not going to create a pull request for it, but if anyone in charge deems it suitable, feel free to add it to the Quartz project (with any additional adjustments to make it fitting if required).

Note that you can easily remove the `SuppressFBWarnings` annotation if you want to. We only use it to let it pass the Findbugs code analysis.
```java
package org.quartz.javaee.concurrent;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.Executor;

import javax.enterprise.concurrent.ManagedExecutors;
import javax.enterprise.concurrent.ManagedTask;
import javax.naming.InitialContext;
import javax.naming.NamingException;

import org.quartz.spi.ThreadExecutor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;


/**
 * JSR-236 ManagedExecutorService implementation of hacked Quartz ThreadExecutor
 * class. This class schedules work on a ManagedExecutorService which is looked
 * up in JNDI. The advantage is that all the work performed is done on a managed
 * thread which is required by WebSphere, see <a
 * href="https://jira.terracotta.org/browse/QTZ-473">here</a>, <a
 * href="https://github.com/quartz-scheduler/quartz/issues/200">here</a> and <a
 * href="https://github.com/spring-projects/spring-framework/issues/15751">here</a>
 * for details.
 * <p>
 * Sets the long-running hint to true to avoid the hung thread detection from
 * the application server, see <a href="https://jira.terracotta.org/browse/QTZ-433">here</a>.
 * </p><p>
 * Note: This implementation was created as a simple drop-in replacement of
 * org.quartz.commonj.WorkManagerThreadExecutor
 * </p><p>
 * Inspired by:<ul>
 * <li>org.springframework.scheduling.concurrent.DefaultManagedTaskExecutor</li>
 * <li>org.springframework.scheduling.concurrent.ConcurrentTaskExecutor</li>
 * <li>org.springframework.core.task.support.TaskExecutorAdapter</li>
 * </ul>
 *
 * @author hostalp
 */
public class ManagedThreadExecutor implements ThreadExecutor {

    private static final Logger logger = LoggerFactory.getLogger(ManagedThreadExecutor.class);

    public static final String DEFAULT_MANAGED_EXECUTOR_SERVICE_NAME = "java:comp/DefaultManagedExecutorService";

    private String executorName;

    private ManagedThreadExecutorAdapter managedExecutor;

    /**
     * Sets the JNDI name of the ManagedExecutorService to use.
     *
     * @param executorName the JNDI name to use to lookup the ManagedExecutorService
     */
    public void setWorkManagerName(String executorName) {
        this.executorName = executorName;
    }

    @Override
    public void initialize() {
        synchronized (this) {
            Object jndiObject = null;
            final List<String> jndiNames = Arrays.asList(executorName, DEFAULT_MANAGED_EXECUTOR_SERVICE_NAME);
            for (String jndiName : jndiNames) {
                if (jndiName != null) {
                    try {
                        jndiObject = new InitialContext().lookup(jndiName);
                    } catch (NamingException e) {
                        logger.debug("Naming exception for [{}] in managed thread executor: {}", jndiName, e.getMessage());
                    }
                    if (jndiObject != null) {
                        break;
                    }
                }
            }

            if (jndiObject != null) {
                if (jndiObject instanceof Executor) {
                    logger.info("Using [{}] in managed thread executor", jndiObject);
                    this.managedExecutor = getManagedExecutor((Executor) jndiObject);
                } else {
                    throw new IllegalStateException("JNDI resource [" + jndiObject + "] is not Executor.");
                }
            } else {
                throw new IllegalStateException("Could not locate Executor on following JNDI URLs: " + jndiNames);
            }
        }
    }

    @SuppressFBWarnings(value = "DMI_THREAD_PASSED_WHERE_RUNNABLE_EXPECTED", justification = "Thread is correctly passed here as Runnable")
    @Override
    public void execute(final Thread thread) {
        try {
            managedExecutor.execute(thread); // NOSONAR java:S2438 - thread is correctly passed here as Runnable, expected behaviour
        } catch (Exception e) {
            logger.error("Error attempting to schedule QuartzSchedulerThread", e);
        }
    }

    private static ManagedThreadExecutorAdapter getManagedExecutor(final Executor executor) {
        return new ManagedThreadExecutorAdapter(executor);
    }

    /**
     * Class that wraps all provided Runnables and Callables
     * with a JSR-236 ManagedTask, exposing a long-running hint and an identity
     * name based on the the thread name.
     */
    private static class ManagedThreadExecutorAdapter implements Executor {

        private final Executor concurrentExecutorDelegate;

        /**
         * All args constructor.
         *
         * @param executor the executor
         */
        ManagedThreadExecutorAdapter(final Executor executor) {
            this.concurrentExecutorDelegate = executor;
        }

        /**
         * Executes task.
         *
         * @param task the task to execute
         */
        public void execute(final Runnable task) {
            this.concurrentExecutorDelegate.execute(ManagedTaskBuilder.buildManagedTask(task));
        }
    }

    /**
     * Delegate that wraps a given Runnable/Callable  with a JSR-236 ManagedTask,
     * exposing a long-running hint and a identity name based on the thread name.
     */
    protected static final class ManagedTaskBuilder {

        /**
         * All args constructor.
         */
        private ManagedTaskBuilder() {
            // avoid instantiate
        }

        /**
         * Builds managed task.
         *
         * @param task the task to build
         * @return built managed task
         */
        public static Runnable buildManagedTask(final Runnable task) {
            final Map<String, String> properties = new HashMap<>(4);
            if (task instanceof Thread) {
                final Thread quartzThread = (Thread) task;
                properties.put(ManagedTask.LONGRUNNING_HINT, "true");
                properties.put(ManagedTask.IDENTITY_NAME, quartzThread.getName());
            }
            return ManagedExecutors.managedTask(task, properties, null);
        }
    }

}
```
