### ISSUE TITLE
CronTrigger job,but when it finish can't auto remove 

### ISSUE THREAD

**Issue by hanfre** [quartz-scheduler/quartz#201]
code:
step1:   insert new job // cron is "06 43 11 15 12 ? 2017", taskid is 1,taskgroup is "A"
trigger= TriggerBuilder.newTrigger().withIdentity(String.valueOf(taskid), taskgroup).withSchedule(scheduleBuilder).build(); 
 ((org.quartz.Scheduler) scheduler).scheduleJob(jobDetail, trigger);

step2:remove job when it run finish ,**but  trigger can't find and trigger is null**,so i think it's finish will be auto remove//taskid is 1,taskgroup is "A"
 trigger = (org.quartz.CronTrigger) QuartzUtil.scheduler.getTrigger(triggerKey);
if (null != trigger)
{
  sched .pauseTrigger(triggerKey);
  sched .unscheduleJob(triggerKey);
  sched.deleteJob(trigger.getJobKey());
}

step3:**because can't remove so i think it's finish will be auto remove, but when i repeat insert , show error message "org.quartz.ObjectAlreadyExistsException: Unable to store Job : 'A.1', because one already exists with this identification."** // cron is "06 43 11 15 12 ? 2017", taskid is 1,taskgroup is "A"
trigger= TriggerBuilder.newTrigger().withIdentity(String.valueOf(taskid), taskgroup).withSchedule(scheduleBuilder).build(); 
 ((org.quartz.Scheduler) scheduler).scheduleJob(jobDetail, trigger);   

question:
1/why i can't find job when remove it 
2/if can't find job why can't insert and  show error message

thankyou!

**Comment by zemian** [comment]
Hi, it would be helpful if you can provide a standalone quartz program that reproduce this. 
See also on https://github.com/quartz-scheduler/quartz/wiki/How-To-Submit-New-Issue

**Comment by zemian** [comment]
Closing outdated, unresolved issues. Please, reopen if still relevant.
