### ISSUE TITLE
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'SCHED_TIME' in 'field list'

### ISSUE THREAD

**Issue by manikanta-m** [quartz-scheduler/quartz#202]
when i am trying to create a simple job scheduler with Quartz with persistence as 
org.quartz.jobStore.class = org.quartz.impl.jdbcjobstore.JobStoreTX i am getting the following error 

com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'SCHED_TIME' in 'field list'
I have seen the schema structure from official website but still i can't find any filed 'SCHED_TIME' in the corresponding table.
thanks for any suggestion.

**Comment by zemian** [comment]
It's likely you used a wrong version of schema.

**Comment by zemian** [comment]
Closing outdated, unresolved issues. Please, reopen if still relevant.
