### ISSUE TITLE
Remove references to org.quartz.scheduler.skipUpdateCheck

### ISSUE THREAD

**Issue by rillig-nm** [quartz-scheduler/quartz#205]
The skipUpdateCheck has been removed in dfe1e5a3cc248e2a46a6ea55567aaa6dc8e15ca5. Nevertheless, the word still appears in the source code, suggesting that it is still active.

See https://github.com/quartz-scheduler/quartz/search?q=skipUpdateCheck

**Comment by bcode2** [comment]
Hi @pelepelin  just FYI https://github.com/quartz-scheduler/quartz/issues/1134
Regards
