### ISSUE TITLE
Attempted to use an uninitialized PoolBackedDataSource. Please call setConnectionPoolDataSource( ... ) to initialize.

### ISSUE THREAD

**Issue by dalmatele** [quartz-scheduler/quartz#208]
When I used cluster mode with MySQL, I've got this error message.
I've debuged and seen that in C30PoolingConnectionProvider class, quartz has not call setConnectionPoolDataSource function. Because of that, when quartz can not call getConnection from Datasource.
How to fix it?

**Comment by zemian** [comment]
Hi @dalmatele , You prob have misconfigured the DB conn pool for Quartz. There is a new guide here now. Can you please follow instruction there and let us know if you still has problem?
