### ISSUE TITLE
Unable to delete the task completely. Lead to that i can not create the same "JobKey" task after it has been deleted.

### ISSUE THREAD

**Issue by xuxueli** [quartz-scheduler/quartz#209]
After I deleted the task using the "org.quartz.Scheduler#unscheduleJob", I couldn't create the same "JobKey" task.

And then i found that the task data corresponding to this "JobKey" was found in the "QRTZ_JOB_DETAILS" table and was not deleted. This is why I cannot delete a task.

How to solve it?

**Comment by zemian** [comment]
This will happen if your job is durable. Try to scheduler.deleteJob first.

**Comment by xuxueli** [comment]
Thank you. It worked.
