### ISSUE TITLE
Erroneous example in cron trigger documentation

### ISSUE THREAD

**Issue by williamhoyle** [quartz-scheduler/quartz#211]
The [Cron Trigger Tutorial](http://www.quartz-scheduler.org/documentation/quartz-2.2.x/tutorials/crontrigger.html) gives the following example:

> So cron expressions can be as simple as this: * * * * ? *

The special character `?` is not legal in the fifth field (month). It should probably be

 > So cron expressions can be as simple as this: * * * * * ?

**Comment by zemian** [comment]
Fixed by PR #371
