### ISSUE TITLE
Trigger stuck in "ACQUIRED" state

### ISSUE THREAD

**Issue by atluri64** [quartz-scheduler/quartz#218]
Hi,

We have Quartz scheduler (version 2.2.2) integrated in Spring Boot app. In production environment (Quartz running in clustered mode), we observed that trigger is stuck in "ACQUIRED" state and the corresponding job is not being run. We had to manually change it to "WAITING" to get it activated again.

As per the issue described below, this seems to be issue with Spring integration as dontSetAutoCommitFalse is set to "true".
 
http://www.quartz-scheduler.org/documentation/faq.html#FAQ-springCommit

 I looked at the job store at runtime, yes dontSetAutoCommitFalse is set to true 

As discussed in below post, there is no direct way to set to to "false". Setting it to "true" by the Spring seems to be valid as it is responsible for managing the transaction.

http://forum.spring.io/forum/spring-projects/container/107192-spring-s-default-opposed-to-quartz-recommendation

I have seen lot of posts in forums discussing the same issue with no obvious answer.

Can someone suggest if there is any solution for it?

Thanks & Regards,
Srinivas Atluri.

**Comment by atluri64** [comment]
Any takers please...

**Comment by hsChandra669** [comment]
We are getting same issue in one of our production server, Not reproducible in any test machine. 
Maven Quartz scheduler dependency is as below

<dependency>
    <groupId>org.quartz-scheduler</groupId>
    <artifactId>quartz</artifactId>
    <version>2.3.0</version>
</dependency>

After changing trigger_state to 'WAITING' , next trigger occurred and again went to state 'ACQUIRED' subsequent triggers not happened.

**Comment by adinatusa** [comment]
Same issue for me. In SchedulerFactoryBean class, L 557, will overwrite org.quartz.jobStore.class with LocalDataSourceJobStore. Further more, in LocalDataSourceJobStore for TX DS, L98, setDontSetAutoCommitFalse(true), meaning autocommit=1.

**Comment by srisudarsan** [comment]
Yes, we are still seeing this behaviour using quartz 2.3.2
. Though we are not able to reproduce this our development environments, we are continuously seeing this in production and higher environments

@adinatusa @atluri64 did you folks manage to solve this ?

**Comment by bradical** [comment]
Interestingly, we're seeing this too but on a much older version of Quartz. There's no error logging that we can see but a trigger that's designed to run every 5s appears stuck in ACQUIRED with a next/prev fire time in the past. No evidence of it running anywhere in the worker pools.

**Comment by srisudarsan** [comment]
> Interestingly, we're seeing this too but on a much older version of Quartz. There's no error logging that we can see but a trigger that's designed to run every 5s appears stuck in ACQUIRED with a next/prev fire time in the past. No evidence of it running anywhere in the worker pools.

Hello @bradical , we were able to get an answer to this. Our spring boot application is running on a PostgreSQL on AWS RDS (Multi AZ Enabled). When the database reboots with a fail over, we saw that the connections are closed from the server side, but the client has not closed it and goes to a stale state, which causes quartz recovery threads to hang. (Enabling trace logs helped us find that the blocking code )

Related information - https://www.theguardian.com/info/2019/dec/02/faster-postgresql-connection-recovery#:~:text=What%20value%20to%20set%20it,appropriate%20timeout%20for%20your%20application

We solved it by setting the socketTImeOut value to our JDBC connection string.

**Comment by bradical** [comment]
Thanks @srisudarsan! We got some information here that confirmed we're looking at a clustered environment and one container that is shutting down seems to have acquired access to the trigger but not released it on shutdown. We're trying to confirm whether there was a problem on shutdown releasing it or not.

**Comment by minheinkhantatcodigo** [comment]
Hi @bradical, any update on your comment? Did you find a solution? I am also experiencing a similar issue. Every time a container is shutdown, some of the 5s triggers are stuck in ACQUIRED state.

**Comment by bradical** [comment]
@minheinkhantatcodigo I'll have to check if we still are since we upgraded Quartz to a newer version last year.

**Comment by minheinkhantatcodigo** [comment]
@bradical I updated quartz version to latest (2.5.2), still doesn't help.

**Comment by adriana-corui** [comment]
Any update on this issue?
