### ISSUE TITLE
Cannot handle user in JDBC URL

### ISSUE THREAD

**Issue by ulsa2** [quartz-scheduler/quartz#219]
I get connection problems on 2.2.3 when having the user info in the (MySQL) JDBC URL rather than as a separate property. I don't think the docs explicitly state that user info in the URL is not supported. Is it a MySQL-specific issue maybe? I can't recall I had this problem with PostgreSQL.

This fails:
```
org.quartz.jobStore.dataSource = db
org.quartz.dataSource.db.driver = com.mysql.jdbc.Driver
org.quartz.dataSource.db.URL = jdbc:mysql://localhost:3306/mydb?user=root&useSSL=false
```

with:

```
java.sql.SQLException: Access denied for user ''@'localhost' (using password: NO)
```

This works:
```
org.quartz.jobStore.dataSource = db
org.quartz.dataSource.db.driver = com.mysql.jdbc.Driver
org.quartz.dataSource.db.URL = jdbc:mysql://localhost:3306/mydb?useSSL=false
org.quartz.dataSource.db.user = root
```

I'm using mysql/mysql-connector-java 5.1.45.

**Comment by zemian** [comment]
We do not do anything special on setup the JDBC driver. In fact we simply use a DB pool (c3p0 or HarikaCP) to create DB connection. So if URL is not support user, then you can check with their driver docs.
