### ISSUE TITLE
Maven build fails on maven-forge-plugin

### ISSUE THREAD

**Issue by darkelfdotse** [quartz-scheduler/quartz#226]
Hi Quartz.

Building the quartz repository with maven fails on Windows 10 when running either
$ ./mvnw install -DskipTests
or
$ mvn clean install -DskipTests

Error message output from maven (same for both commands above):

.
.
[INFO] ------------------------------------------------------------------------
[INFO] Building quartz 2.3.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
.
.
[ERROR] Failed to execute goal org.terracotta:maven-forge-plugin:1.1.9:manifest (create-manifest) on project quartz: Execution create-manifest of goal org.terracotta:maven-forge-plugin:1.1.9:manifest failed: Execute failed: java.io.IOException: Cannot run program "svn": CreateProcess error=2, The system cannot find the file specified -> [Help 1]

**Comment by jayanth-ganganahalli** [comment]
Hi,
Even I am facing the similar issue.  I am attaching the logs of the same. Any help is much appreciated.
[log1.txt](https://github.com/quartz-scheduler/quartz/files/2269737/log1.txt)

**Comment by zemian** [comment]
This is a dup of #66
