### ISSUE TITLE
When are you planning to release 2.3.1 with fixed typo in postgres sql scripts?

### ISSUE THREAD

**Issue by pnowy** [quartz-scheduler/quartz#228]
Hi,

are you planning to release 2.3.1 version with fixed typo in sql script for postgres tables?

I see that the all issues for milestone are closed long time ago (ie. https://github.com/quartz-scheduler/quartz/issues/159) but newer version is unreleased.

Thx for the update.

**Comment by zemian** [comment]
Hi, sorry for the long inactivity. Seems we are lacking on developer interests for a while :(

I have put in a in query in the dev list: https://groups.google.com/forum/#!topic/quartz-scheduler-dev/M5XxzsZSLfw

Would love to see someone to respond and get into action again.

**Comment by zemian** [comment]
There is no plan on official release yet, but if you needs to, you can do a manual build from our source for now.
