### ISSUE TITLE
Not implemented features :-(

### ISSUE THREAD

**Issue by AlBundy33** [quartz-scheduler/quartz#229]
Are there any plans to implement missing features?

In my case I would need to specify multiply "nth" days to work with expressions like first and third monday in month.
https://github.com/quartz-scheduler/quartz/blob/master/quartz-core/src/main/java/org/quartz/CronExpression.java#L480

Also the other missing features seems to be helpful. ;-)

BTW: Why is an exception throws if I define day of week and day of month where one of them is *

for example if i use * for day of month and MON for day of week I get this exception until I change day of month to ?

**Comment by zemian** [comment]
Pull Requests are welcome :)

**Comment by franklohr** [comment]
Multiply "nth" days to work with expressions (like first and third monday in month) would be still be usefull!
