### ISSUE TITLE
use Scheduler in activity 

### ISSUE THREAD

**Issue by maryhzf** [quartz-scheduler/quartz#230]
i use this code

 JobDetail job1 = JobBuilder.newJob(MyJob.class)
                    .withIdentity("job1", "group1").build();
            Trigger trigger1 = TriggerBuilder.newTrigger()
                    .withIdentity("cronTrigger1", "group1")
                    .withSchedule(CronScheduleBuilder.cronSchedule("0/5 * * * * ?"))
                    .build();
            Scheduler scheduler1 = StdSchedulerFactory.getDefaultScheduler();
            scheduler1.start();
            scheduler1.scheduleJob(job1, trigger1);

it is fine ,but when i put it in activity ,it has this error
'org.quartz.core.QuartzScheduler', referenced from method org.quartz.impl.StdSchedulerFactory.instantiate
FATAL EXCEPTION: main  java.lang.NoClassDefFoundError: java.beans.Introspector

help me please

**Comment by zemian** [comment]
Please see https://github.com/quartz-scheduler/quartz/wiki/How-To-Submit-New-Issue

**Comment by zemian** [comment]
Closing outdated, unresolved issues. Please, reopen if still relevant.
