### ISSUE TITLE
Cron trigger fires immediately when rescheduleJob() api is called

### ISSUE THREAD

**Issue by dpahuja123** [quartz-scheduler/quartz#232]
Calling the rescheduleJob() method, fires the trigger immediately but when I change the start date time before calling rescheduleJob() method on a trigger, then its working fine.
Is it a bug ???

**Comment by zemian** [comment]
It is all depend what your trigger is. 

Please see https://github.com/quartz-scheduler/quartz/wiki/How-To-Submit-New-Issue

**Comment by zemian** [comment]
Closing outdated, unresolved issues. Please, reopen if still relevant.
