### ISSUE TITLE
jobScheduled listener not triggered

### ISSUE THREAD

**Issue by claudiowilson** [quartz-scheduler/quartz#234]
When using this api:

`void scheduleJob(JobDetail jobDetail, Set<? extends Trigger> triggersForJob, boolean replace) throws SchedulerException;` the jobScheduled callback for the SchedulerListener does not get triggered. This is because when storing the triggers `QuartzScheduler` does not call `notifySchedulerListenersSchduled` in the API. I can put up a fix if you'd like, since it is relatively simple.

**Comment by zemian** [comment]
Fixed with PR #351
