### ISSUE TITLE
Whitelisting Quartz jobs running in clustered quartz environment

### ISSUE THREAD

**Issue by konnectnishant** [quartz-scheduler/quartz#236]
hello!
I'm using Quartz 2.2.1 in a clustered mode using with Oracle database. We are running almost 10 nodes with few jobs with disallowing concurrent execution. The use case here is, I want to whitelist jobs that can run on the particular node. For example: Run node 1-5 picking the only job 'A' and node 6-10 picking job 'B' only. I don't want to create another set of Quartz DB tables to run two different clusters. Does something like this exist? any pointers will greatly help!

**Comment by yarafatin** [comment]
You may create two schedulers, register Job A in scheduler 1, and Job B in scheduler 2. The schedulers must have unique instanceName. Create a new application level property and control the start of the schedulers. node 1-5 will have property value true for scheduler1 and false for scheduler2. Apply the converse to nodes 6-10. This is one way of implementing your requirement. I am sure there are other ways too.

**Comment by zemian** [comment]
Close as not an issue.
