### ISSUE TITLE
Store BLOB_DATA in QRTZ_BLOB_TRIGGERS as json value rather than java serialization

### ISSUE THREAD

**Issue by rlouis-foresee** [quartz-scheduler/quartz#237]
Is there any way to configure quartz to store BLOB_DATA as json/string value as there are serialization issues - 
` local class incompatible: stream classdesc serialVersionUID = 7545828163653121010, local class serialVersionUID = -33983373018933994 [See nested exception: java.io.InvalidClassException: com.example.ExampleClass; local class incompatible: stream classdesc serialVersionUID = 7545828163653121010, local class serialVersionUID = -33983373018933994]`

The only work around right now is manually deleting the triggers using the API.

I am able to store JOB_DATA as String using the property org.quartz.jobStore.useProperties=true. I am looking to see if BLOB_DATA can be stored as a String similarly. Haven't found too much from the documentation.

**Comment by zemian** [comment]
I have been thinking this feature myself as well. It would be very nice to have. Storing blob is really a hassle and not easy to maintain/upgrade. However this would mean break old Quartz API and DB schema completely though. Let's add as part of Quartz3 feature.
