### ISSUE TITLE
quartz scheduler stops when system is heavily loaded without any notification 

### ISSUE THREAD

**Issue by Kushang-egnaroinc** [quartz-scheduler/quartz#238]
Hi,

My entire application's state depends on the quartz scheduler. I am running a daily job which runs every 24 hours and updates the application state based on the logic written in job's execution function.

While testing, I found that sometimes when the system gets heavily loaded, the schedule does not work and the state does not change.

When I was running scheduler for every second and keeps system heavily loaded I was able to reproduce this case frequently.

Is there any way to ensure that quartz scheduler is running always or is there any way where scheduler will give notification in case if it is not able to trigger the job or schedule a job.

**Comment by JackStefen** [comment]
I also encountered the same problem...

**Comment by zemian** [comment]
Closing outdated, unresolved issues. Please, reopen if still relevant. 

See https://github.com/quartz-scheduler/quartz/wiki/How-To-Submit-New-Issue
