### ISSUE TITLE
MISFIRE_INSTRUCTION_DO_NOTHING doesn't work as documented, and has the behavior of MISFIRE_INSTRUCTION_IGNORE_MISFIRE_POLICY

### ISSUE THREAD

**Issue by jnizet** [quartz-scheduler/quartz#239]
I'm using a CronTrigger using the JDBC store on Oracle. 
The trigger fires a job execution every 15 seconds (`0/15 * * * * ?`), and is configured using MISFIRE_INSTRUCTION_DO_NOTHING.

If I shut down my (unique development) server for a minute and then start it up again, I expect the trigger to do nothing until the next 15 seconds fire time is reached. But instead, several triggers are being fired all at once.

Here's a trace of what happens at startup:

```
Starting optimization job... Fire time = Wed Jun 06 16:44:42 CEST 2018, scheduledFireTime =Wed Jun 06 16:44:00 CEST 2018, misfire instruction = 2
Starting optimization job... Fire time = Wed Jun 06 16:44:42 CEST 2018, scheduledFireTime =Wed Jun 06 16:44:15 CEST 2018, misfire instruction = 2
Starting optimization job... Fire time = Wed Jun 06 16:44:42 CEST 2018, scheduledFireTime =Wed Jun 06 16:44:30 CEST 2018, misfire instruction = 2
Starting optimization job... Fire time = Wed Jun 06 16:44:45 CEST 2018, scheduledFireTime =Wed Jun 06 16:44:45 CEST 2018, misfire instruction = 2
```

As you can see, the triggered is being fired at 16:44:42 (which does not match the cron expression), several times, to re-trigger misfired triggers scheduled sooner and missed because the server was down.

These traces are generated by the following instructions:

    @Override
    public void execute(JobExecutionContext context) throws JobExecutionException {
        System.out.println("Starting optimization job... Fire time = "
                               + context.getFireTime()
                               + ", scheduledFireTime ="
                               + context.getScheduledFireTime()
                               + ", misfire instruction = "
                               + context.getTrigger().getMisfireInstruction());

Is there something I don't understand in the documentation, or is this a bug? 
If it's not a bug, how to avoid that behavior?

**Comment by jnizet** [comment]
Never mind. I found the explanation: all these misfires are not considered as misfires because they mised their scheduled fire time by less than 1 minute, which is the default misfire threshold.

**Comment by lemonl2** [comment]
@jnizet 
I have met same problem, but I don't know why
```java
public class JobTest implements Job {
    public void execute(JobExecutionContext context) throws JobExecutionException {
        JobDetail detail = context.getJobDetail();
        String name = detail.getJobDataMap().getString("name");
        System.out.println("say hello to " + name + " at " + new Date());
        System.out.println("fire job " + name + " at " + context.getFireTime());
        System.out.println("fire scheduler " + name + " at " + context.getScheduledFireTime());
    }
}
```

```java
public class SchedulerTest {
    public static void main(String[] args) {
        try {
            Scheduler scheduler = StdSchedulerFactory.getDefaultScheduler();
            CronScheduleBuilder cronScheduleBuilder = CronScheduleBuilder.cronSchedule("0/30 * * * * ?");
            CronTrigger cronTrigger = TriggerBuilder.newTrigger().withIdentity("trigger1", "group1") 
                    .withSchedule(cronScheduleBuilder.withMisfireHandlingInstructionFireAndProceed()) 
                    .build();

            //定义一个JobDetail
            JobDetail job = JobBuilder.newJob(JobTest.class) 
                    .withIdentity("job1", "group1") 
                    .usingJobData("name", "quartz") 
                    .build();

            scheduler.scheduleJob(job, cronTrigger);

            scheduler.start();

            Thread.sleep(100000);
            scheduler.pauseTrigger(cronTrigger.getKey());
            scheduler.pauseJob(job.getKey());
            scheduler.unscheduleJob(cronTrigger.getKey());
            scheduler.deleteJob(job.getKey());
            scheduler.shutdown(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

It don't execute once now,  why ?
`
withMisfireHandlingInstructionFireAndProceed() 
` this function doesn't work?

**Comment by lemonl2** [comment]
I understood something  wrong!
