### ISSUE TITLE
can we change quartz behavior on the fly?

### ISSUE THREAD

**Issue by yangjiajun2014** [quartz-scheduler/quartz#241]
I want to change some properties of quartz schedule when the schedule is running.Is it possible?

**Comment by zemian** [comment]
Hi, if you use the DB store, the schedule (triggers) can be dynamically updated. So does the job data map. However the job class itself would require you to add and restart the process to pickup. Even with job you can create a Script job that execute any Java ScriptEngine and it can be consider as dynamic job.
