### ISSUE TITLE
 [See nested exception: java.sql.SQLSyntaxErrorException: Unknown column 'IS_VOLATILE' in 'where clause']

### ISSUE THREAD

**Issue by linjinhai** [quartz-scheduler/quartz#242]
[See nested exception: java.sql.SQLSyntaxErrorException: Unknown column 'IS_VOLATILE' in 'where clause']

**Comment by storymin** [comment]
你这个不是SQL异常吗，数据库表里面没加这个字段吧。看不出来和这个框架有什么联系。

**Comment by zemian** [comment]
We can not debug with these information. Please submit better description of your problem.

**Comment by linjinhai** [comment]
It has been resolved because the project has two different versions of packages.We have import packages using maven, but there are also all conflicts in lib.
