### ISSUE TITLE
Allow job keys to have multiple groups

### ISSUE THREAD

**Issue by ghost** [quartz-scheduler/quartz#248]
Not really an issue, but more of a potential idea for extension. If a job key could have multiple groups, each group could control the job, rather than just the one group. The idea hasn't materialised in my head much more than that though.

**Comment by zemian** [comment]
Currently it only one group is supported. You can use a naming convention (prefix) to act as sub-group.

In future, I would like to see Quartz to support multiple groups (tags) too. It would be a good Quartz3 item to request!
