### ISSUE TITLE
Quartz with pgBouncer

### ISSUE THREAD

**Issue by OrderOfLion** [quartz-scheduler/quartz#250]
Hi,

We are using quartz 2.1.5, we removed c3p0 as connection pooler from our project due to pgBouncer implementation. When quartz is redirected to pgBouncer it throws error the project fails to start. We can see the quartz use c3p0 as connection pooler so how can we use quartz with pgBouncer? 
Can any one help.

Thanks,

**Comment by zemian** [comment]
In Quartz, we use Java based connection pool, and c3p0 is one such provider. You can change to different pool provider (and there are many in Java world) by config "org.quartz.dataSource.NAME.connectionProvider.class" mentioned here: http://www.quartz-scheduler.org/documentation/quartz-2.2.x/configuration/ConfigDataSources.html

I am not familiar with pgBouncer, but it would have to support Java and JDBC pooling in order for Quartz be able to use it.

**Comment by zemian** [comment]
Close as not an issue
