### ISSUE TITLE
Wrong null check in web-context initialisation listener

### ISSUE THREAD

**Issue by l-dobrev** [quartz-scheduler/quartz#256]
https://github.com/quartz-scheduler/quartz/blob/9f9e400733f51f7cb658e3319fc2c140ab8af938/quartz-core/src/main/java/org/quartz/ee/servlet/QuartzInitializerListener.java#L163

Seems like it's checking for ```shutdownPref```, and then it parses ```shutdownWaitPref```.
This leads to ignoring the configuration value ```quartz:wait-on-shutdown``` if ```quartz:shutdown-on-unload``` is not configured. This leads to a race condition in Tomcat that leaves the scheduler threads alive enough that Tomcat calls then **thread leak**.

**Comment by l-dobrev** [comment]
Current work-around: if ```quartz:wait-on-shutdown``` is needed declaring ```quartz:shutdown-on-unload``` is needed.

**Comment by zemian** [comment]
Looks like there is a PR#212 for this already

**Comment by zemian** [comment]
New PR #322 has been raise for this fix
