### ISSUE TITLE
Unschedule trigger

### ISSUE THREAD

**Issue by chaksoham** [quartz-scheduler/quartz#257]
As far my understanding unscheduling a trigger only removes the trigger but the job persists. While delete removes all triggers and job as well. The issue I am facing is unschedule is also removing job.Any lead will be helpful.

**Comment by Julius95** [comment]
If your jobs get deleted when unscheduling a trigger make sure your jobs are storedDurably. See for example http://www.quartz-scheduler.org/api/2.1.7/org/quartz/JobBuilder.html#storeDurably()

**Comment by zemian** [comment]
Close as it's already answered
