### ISSUE TITLE
Issue with quartz calendar

### ISSUE THREAD

**Issue by EwaiMPI** [quartz-scheduler/quartz#259]
Hello, we are receiving the following message  JobStoreTX  W org.quartz.impl.jdbcjobstore.StdJDBCDelegate selectCalendar Couldn't find calendar with name ' '.  How can I resolve this issue?

**Comment by clevertension** [comment]
1. please give the specific quartz version
2. paste the full exception stack
thanks

**Comment by EwaiMPI** [comment]
1.  quartz-all-1.6.0.jar
2.  please see attached file
[systemout.log](https://github.com/quartz-scheduler/quartz/files/2393386/systemout.log)

**Comment by EwaiMPI** [comment]
sorry, I accidentally closed the issue.

**Comment by clevertension** [comment]
how can you add data in qrtz_calendars, just remove it

**Comment by EwaiMPI** [comment]
There is no data to remove, as the table has no data.  please see attached file
[QuartzCalendarTable.docx](https://github.com/quartz-scheduler/quartz/files/2405605/QuartzCalendarTable.docx)

**Comment by zemian** [comment]
Your error says you have some job that associated calendar with it, and somehow not able to fetch it. You need to verify that.

Please do not attach .docx file.

BTW, We no longer support old quartz-1.6.x. Please retry your problem with latest Quartz release.

**Comment by zemian** [comment]
Closing outdated, unresolved issues. Please, reopen if still relevant.
