### ISSUE TITLE
init sql script running error if have not specify the comment-prefix

### ISSUE THREAD

**Issue by wangkeshan9538** [quartz-scheduler/quartz#262]
when use springboot2  mysql8 with quartz , the application.yml is
```
spring.quartz.jdbc.initialize-schema=ALWAYS
spring.quartz.job-store-type=jdbc
```
its cannot init database , after debug  i find that   i must have  a property is
```
spring.quartz.jdbc.comment-prefix=#
```
so quartz cannot detect the correctly comment-prefix ？

**Comment by zemian** [comment]
This is springboot issue, not quartz. Quartz itself does not initial the DB, it's user task to setup schema first.
