### ISSUE TITLE
One of the schedule triggered twice in difference of milliseconds. 

### ISSUE THREAD

**Issue by shukladhaval25** [quartz-scheduler/quartz#265]
Added on job in Quartz trigger and its get execute twice withing few milliseconds. It happens intermittent.  
Create one schedule with name "TestSchedule" which should be trigger everyday at 13:00 hours. 
First instance of schedule will be triggered at 13:00:00,084
Second instance of same schedule will be trigger at 13:00:00,186

Can some one help me over here? Why Quartz.net allow to trigger same schedule twice at same time?

**Comment by lahma** [comment]
Please give example code to reproduce.

**Comment by zemian** [comment]
Closing outdated, unresolved issues. Please, reopen if still relevant.
