### ISSUE TITLE
Foreign key

### ISSUE THREAD

**Issue by shaolilanse** [quartz-scheduler/quartz#266]
can I remove foreign keys for the tables?

**Comment by zemian** [comment]
We provided db schema for you to get started with Quartz, you can do whatever you like on them to make your project works. :)

**Comment by zemian** [comment]
Close as not an issue

**Comment by thislyc** [comment]
> 

感谢你们的工作！

**Comment by thislyc** [comment]
> We provided db schema for you to get started with Quartz, you can do whatever you like on them to make your project works. :)

Thank you for your work!
I want to know whether quartz relies on the foreign key constraint of the database table to realize some functions. If I delete the foreign key of the table, will it affect the functions of quartz

**Comment by jiayuchen** [comment]
> > We provided db schema for you to get started with Quartz, you can do whatever you like on them to make your project works. :)
> 
> Thank you for your work! I want to know whether quartz relies on the foreign key constraint of the database table to realize some functions. If I delete the foreign key of the table, will it affect the functions of quartz

Hi @thislyc , I have the same problem, have you tried to remove the foreign key and did it affect the functions of quartz? Thx

**Comment by TitaniumOne** [comment]
> > > We provided db schema for you to get started with Quartz, you can do whatever you like on them to make your project works. :)
> > 
> > 
> > Thank you for your work! I want to know whether quartz relies on the foreign key constraint of the database table to realize some functions. If I delete the foreign key of the table, will it affect the functions of quartz
> 
> Hi @thislyc , I have the same problem, have you tried to remove the foreign key and did it affect the functions of quartz? Thx
Hi @jiayuchen , I have the same problem, have you tried to remove the foreign key and did it affect the functions of quartz? Thx
