### ISSUE TITLE
Multiple scheduler instances against one db

### ISSUE THREAD

**Issue by bengitsham** [quartz-scheduler/quartz#269]
Sorry if this is the wrong place to state this - but really needing some advice. 

We are in a situation where we need multiple (non-clustered) scheduler instances running so that - using masstransit and rabbitMQ etc. - we can send our jobs to the correct virtual hosts.

My question is based on the idea of having these instances have different instanceNames but pointing to one Quartz db. I have seen online that this is okay to do and local tests suggest this is fine. However, the quartz documentation states 
"Never start (scheduler.start()) a non-clustered instance against the same set of database tables that any other instance is running (start()ed) against. You may get serious data corruption, and will definitely experience erratic behavior."

So ... is this a really bad idea or am I safe to go ahead with this solution?

(There is also the scheduler name column in the trigger table which doesn't make sense if if is not what it is used for?)

**Comment by jarlah** [comment]
This issue was moved to OpenQuartz/quartz-scheduler#7

**Comment by zemian** [comment]
Hi, Quartz2 can already do this just fine. What you need to understand is how you want your multiple schedulers to run. Quartz2 support clustered or non-clustered when running multiple schedulers. You want clustered feature if you have VERY LARGE number of jobs in system and want them to run in multiple machines. You want non-cluster schedulers if you want just to separate jobs by completely different independent schedulers. 

If all schedulers are non-clustered, then you need to ensure "org.quartz.scheduler.instanceId" is unique for each. Else if clustered, then ensure they shared the same id, and "org.quartz.jobStore.isClustered" is set to "true".

**Comment by zemian** [comment]
Close as not an issue
