### ISSUE TITLE
Datasource default schema

### ISSUE THREAD

**Issue by adexerivera** [quartz-scheduler/quartz#271]
Sorry if this is the wrong place to state this - but really needing some advice.

Actually, I don't know, if it's posible make use of a different database schema, for example on SQL Server 'dbo', and we need select another default schema.

For example: `org.quartz.dataSource.NAME.schema=OTHER`

Like jpa property:  `spring.jpa.properties.hibernate.default_schema`

I would appreciate knowing if there is any way, or if it is possible to add it in code and make use of it.

Thank you

**Comment by jarlah** [comment]
Maybe something i can look at in my clone project. I looked into the JobStoreSupport class and it references table prefix property. I dont know however how to configure prefix, i just saw the support in the code. Prefix means in effect the same as schema. You can Just add a dot at the end.

**Comment by jarlah** [comment]
As i have tried to say along time now. This project is dead. You cannot expect anyone to fix anything in this repo unless the original developers give the repo away. Which i highly doubt.

I cant just rip off their docs blatantly. But what i can do in my now ready to use clone is to add a wiki page with tricks like these. And point to the official docs for more info.

**Comment by jarlah** [comment]
This issue was moved to OpenQuartz/quartz-scheduler#6

**Comment by zemian** [comment]
Hi, this is already mentioned in the doc here: http://www.quartz-scheduler.org/documentation/quartz-2.2.x/configuration/ConfigJobStoreTX.html

See "org.quartz.jobStore.tablePrefix"

**Comment by zemian** [comment]
Close as not an issue
