### ISSUE TITLE
Handling 1 trigger(s) that missed their scheduled fire-time. 

### ISSUE THREAD

**Issue by Rain569** [quartz-scheduler/quartz#274]
Avoid error handlers
Handling 1 trigger(s) that missed their scheduled fire-time.s
![_20181031162522](https://user-images.githubusercontent.com/29650825/47775139-d9aa1480-dd29-11e8-86c3-76080267c957.png)

**Comment by jarlah** [comment]
This issue was moved to OpenQuartz/quartz-scheduler#5

**Comment by zemian** [comment]
Hi, I am not sure I understand what your request is. If you have a problem with quartz, please try to reproduce with a standalone Java program, and provide stacktrace and log if possible.

**Comment by zemian** [comment]
Close as not an issue
