### ISSUE TITLE
Quartz RMI remote server not work

### ISSUE THREAD

**Issue by HaiNM-deha** [quartz-scheduler/quartz#282]
On the remote server the config is:

org.quartz.scheduler.rmi.proxy = true
org.quartz.scheduler.rmi.registryHost = public ip
org.quartz.scheduler.rmi.registryPort = 1099

System.setProperty("java.rmi.server.hostname", "public ip");

ERROR [2016-07-28 09:10:23,017] xxxx: Error communicating with remote scheduler.
! java.net.ConnectException: Connection refused
! ... 83 common frames omitted
! Causing: java.rmi.ConnectException: Connection refused to host: log-emea-1; nested exception is:
! java.net.ConnectException: Connection refused

**Comment by HaiNM-deha** [comment]
@zemian please help me, thanks

**Comment by zemian** [comment]
Hi, this error means your quartz server is not running, and hence your quartz client can't connect. If you still face this issue, please post both the server and client side of your quartz.properties

**Comment by zemian** [comment]
Closing outdated, unresolved issues. Please, reopen if still relevant.
