### ISSUE TITLE
Job FailureRetryInterval 

### ISSUE THREAD

**Issue by Joker1995** [quartz-scheduler/quartz#283]
SomeTime My job was time-sensitive,this job would be executed on next day,but that was wrong,I think maybe have some args to cancel this retry 

> Please provide more information to to show what problem Quartz has.

nothing maybe my code was wrong,Please close this issue,Thank u for your reply

**Comment by zemian** [comment]
Please provide more information to to show what problem Quartz has.

**Comment by zemian** [comment]
Close as not an issue
