### ISSUE TITLE
Issue with @disallowconcurrentexecution

### ISSUE THREAD

**Issue by nikhil-dhiman** [quartz-scheduler/quartz#286]
1st issue: I am running my DisallowConcurrentExecution quartz job in multiple containers. The problem arises when the container suddenly shuts downs while the job was still running. And after that, there is no way I can run that cron, without updating tables.
2nd issue: How to remove a job, I am not finding a way, I can do that from Quartz config script, but data was still in MySQL tables.

Version: x.y.z
2.3.0

**Comment by zemian** [comment]
Hi, 
1) Try use Scheduler.shutdown(true) to wait for jobs to complete before shutdown. See http://www.quartz-scheduler.org/documentation/quartz-2.x/cookbook/ShutdownScheduler.html
2) You can remove job using the Scheduler.removeJob() method.

**Comment by zemian** [comment]
Close as not an issue
