### ISSUE TITLE
Quartz.Impl.AdoJobStore.LockException: Failure obtaining db row lock

### ISSUE THREAD

**Issue by shweta2089** [quartz-scheduler/quartz#287]
We are facing continuous exception from quartz stating "Quartz.Impl.AdoJobStore.LockException: Failure obtaining db row lock: Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.Data.SqlClient.SqlException: Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> "

As per our findings, we analyse that we have the call for below query multiple times
"SELECT * FROM QRTZ_LOCKS WITH (UPDLOCK,ROWLOCK) WHERE SCHED_NAME = 'MarilynScheduler' AND LOCK_NAME = @lockName"

And this is taking lock on open transaction and not releasing the locks at the required time.
Does anyone has any idea about it?
How to solve the issue?

**Comment by zemian** [comment]
I think you are in the wrong project. Your code looks like the .Net quartz, this is the Java quartz.

**Comment by zemian** [comment]
Close as not an issue

**Comment by zemian** [comment]
See related #268
