### ISSUE TITLE
Can CronExpression support tow expressions？

### ISSUE THREAD

**Issue by chenchuxin** [quartz-scheduler/quartz#289]
Like 22:00-0:05
 `* * 22-23 * * ? , * 0-5 0 * * ?`

**Comment by Meteorkor** [comment]
you can work through 'org.quartz.impl.calendarDailyCalendar'
refer to http://www.quartz-scheduler.org/documentation/quartz-2.1.x/tutorials/tutorial-lesson-04.html

**Comment by zemian** [comment]
Close as not an issue
