### ISSUE TITLE
print executing sql

### ISSUE THREAD

**Issue by Chinazhouwy** [quartz-scheduler/quartz#291]
how to print the executing sql in my log?  I see the source is JDBC, maybe cannot do it

**Comment by zemian** [comment]
Hi, Unfortunately Quartz itself does not print the sql in log. However, you can try turning on your database SQL logging for this.

Another solution that I can think of is you can try https://github.com/arthurblake/log4jdbc that wrap around a JDBC driver to log the SQL as well.

All this will take a performance hit on your application obviously. So use it with care.

**Comment by Chinazhouwy** [comment]
> Hi, Unfortunately Quartz itself does not print the sql in log. However, you can try turning on your database SQL logging for this.
> 
> Another solution that I can think of is you can try https://github.com/arthurblake/log4jdbc that wrap around a JDBC driver to log the SQL as well.
> 
> All this will take a performance hit on your application obviously. So use it with care.

thanks ,I use druid and log4j2
