### ISSUE TITLE
website no longer available on original address http://quartz-scheduler.org

### ISSUE THREAD

**Issue by VGerris** [quartz-scheduler/quartz#3]
Hi,

I guess you moved to github for the hosting.
The quartz-scheduler.org DNS record does not point to the site anymore and www.quartz-scheduler.org shows an invalid HTTPS certificate (github.com).
If I google I find the non www link as the first, which gives me a time out.
You may want to fix this (DNS and certificate :) ).

Greetings,
Vincent

**Comment by jhouserizer** [comment]
We'll probably move back to self-hosting before too long.  In the mean time we can't support HTTPS on github as the platform doesn't allow for it.
