### ISSUE TITLE
About Quartz Database table 

### ISSUE THREAD

**Issue by fanshaowei** [quartz-scheduler/quartz#30]
hello,first ,thanks for quartz to help me to complete my time jobs.
But now ,i have some question about the Database table of the Quartz framework.
Because I want to knows the  tables's columns meaning ,but is a pity,i can't find the related docs.
Could you can me,beautiful girls or handsome boys!!!! ^ o ^

**Comment by zemian** [comment]
This is not an issue.

I am not aware there is a such documentation on describing each of database table. If you have question on a specific table, you can ask on the quartz mailing list.
