### ISSUE TITLE
after pauseJob, i resumeJob, execute many times job

### ISSUE THREAD

**Issue by huangshayang** [quartz-scheduler/quartz#308]
`JobDetail jobDetail = JobBuilder.newJob(QuartzStudy.class).withIdentity("job1").build();
        Trigger trigger = TriggerBuilder.newTrigger()
                .startAt(DateBuilder.evenSecondDate(new Date()))
                .withSchedule(CronScheduleBuilder.cronSchedule("*/5 * * * * ?").withMisfireHandlingInstructionDoNothing())
                .build();
scheduler.pauseJob(jobDetail.getKey());
        Thread.sleep(10000);
        scheduler.resumeJob(jobDetail.getKey());`
10s wait   resumeJob execute 2 times job
20s wait resumeJob execute 4 times job
...
how to solve this problem

**Comment by zemian** [comment]
Close as invalid issue. 

Your question is unclear nor has enough info to help you. 

Also, issue tracker is for filing bug. Please ask your question on mailing list. 
questions. Please see https://github.com/quartz-scheduler/quartz/wiki/How-To-Submit-New-Issue
