### ISSUE TITLE
most databases are lowercase, why is your uppercase? linux mysql case sensitive，windows not

### ISSUE THREAD

**Issue by Dreampie** [quartz-scheduler/quartz#31]
give a reason，and can I not use uppercase？

**Comment by zemian** [comment]
This is not an issue.

Most of the database vendors has option to turn case insensitive on table and column names. Also the SQL lang itself should be case in sensitive, so We don't see a problem using uppercase. The code at runtime will try to construct all queries using upper case to be consistent. 

Let us know if you face a particular issue with DB name case.

**Comment by cycbluesky** [comment]
It's more better if we have a configuration to decide uppercase or lowercase.
I created quartz tables in my database, the existent tables are all lowercase, but the quartz tables must be uppercase, due to my linux mysql case sensitive.

**Comment by hopana** [comment]
same request, better to have a configuration

**Comment by krishnakittu** [comment]
Same for me as well. Better to  Better to have this as a configuration instead of depending on DB vendor.

**Comment by hinorashi** [comment]
hello there, is anyone still waiting for this feature 🐧

**Comment by limengning** [comment]
装什么B
