### ISSUE TITLE
delete fired triggers failed when jdbc connect down, DisallowConcurrentExecution job cannot be triigger  

### ISSUE THREAD

**Issue by modou1618** [quartz-scheduler/quartz#310]
JobRunShell.run 
qs.notifyJobStoreJobComplete(trigger, jobDetail, instCode);

delete fired triggers failed when jdbc connect down, 
triggers'state  for  DisallowConcurrentExecution job will always be  blocked
job then cannot be triigger  any more

i only can restart cluster node to delete cluster's dirty fire triiger for restore job trigger.

**Comment by zemian** [comment]
Hi, can't help you with these info. Please read https://github.com/quartz-scheduler/quartz/wiki/How-To-Submit-New-Issue

**Comment by zemian** [comment]
Closing outdated, unresolved issues. Please, reopen if still relevant.
