### ISSUE TITLE
Failure obtaining db row lock: Lock wait timeout exceeded

### ISSUE THREAD

**Issue by chilingpan123** [quartz-scheduler/quartz#313]
We frequently met with following error:
org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: Lock wait timeout exceeded; try restarting transaction
    at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:157) ~[quartz-2.2.1.jar:na]
    at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113) ~[quartz-2.2.1.jar:na]
    at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3185) ~[quartz-2.2.1.jar:na]
    at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:3935) [quartz-2.2.1.jar:na]
    at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:3956) [quartz-2.2.1.jar:na]

Quartz version: 2.2.1
JDK8
DB: MySQL 5.5
We used it in cluster environment, where there are 18 servers. There are total about 450 jobs are scheduled running in various frequency. The most often ones are running every 5 minutes.

Quartz property in Spring:
org.quartz.scheduler.instanceName: SomeBatchScheduler
org.quartz.scheduler.instanceId: AUTO
org.quartz.jobStore.misfireThreshold: 60000
org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
org.quartz.jobStore.tablePrefix: ${quartz.tablePrefix}
org.quartz.jobStore.isClustered: true
org.quartz.jobStore.dontSetAutoCommitFalse: false
org.quartz.threadPool.class; org.quartz.simpl.SimpleThreadPool
org.quartz.threadPool.threadCount: 50
org.quartz.threadPool.threadPriority: 5

DataSource defined:
dataSource class: com.mchange.v2.c3p0.ComboPooledDataSource
destroy-method: close
driverClass: ${app.jdbc.driverClassName}
jdbcUrl: ${app.jdbc.url}
maxPoolSize" value="40"
minPoolSize" value="5"
acquireIncrement" value="2"
checkoutTimeout" value="60000" 
debugUnreturnedConnectionStackTraces: "true"
testConnectionOnCheckin: "true"
testConnectionOnCheckout: "true"
idleConnectionTestPeriod: "300"
preferredTestQuery: "SELECT 1"

Symptom on DB side:
When this issue happened, there are many threads (150) were stucked on query:
SELECT * FROM COAP_LOCKS WHERE SCHED_NAME = '####' AND LOCK_NAME = 'STATE_ACCESS' FOR UPDATE
or
SELECT * FROM COAP_LOCKS WHERE SCHED_NAME = '####' AND LOCK_NAME = 'TRIGGER_ACCESS' FOR UPDATE

It looks like some Quartz thread didn't release lock and these threads are waiting indefinitely.
The entries in fired_triggers stayed in "ACQUIRED" state.
Seem a bug that Quartz forgot to release lock.

To get out of the stucking state, we have to re-start application to kill the session.

Please advise for fixing the issue.

Thanks

**Comment by zemian** [comment]
Closing as dup of #268
