### ISSUE TITLE
Feature request: add weekly to interval in DailyTimeIntervalScheduleBuilder

### ISSUE THREAD

**Issue by malinmario** [quartz-scheduler/quartz#314]
I would like to be able to do something like this;

.withSchedule(DailyTimeIntervalScheduleBuilder
							.dailyTimeIntervalSchedule()
							.onDaysOfTheWeek(Calendar.WEDNESDAY)
							.startingDailyAt(TimeOfDay.hourAndMinuteOfDay(13, 0))
							.withInterval(2, IntervalUnit.WEEK)
						).build();

This would allow for scheduling weekly activities.

The other option would be to add support for a weekly interval in the CronScheduleBuilder that would support;

CronExpression cron = new CronExpression("0 0 6 ? * MON-WED/2");

The CronExpression ignores the /2 and executes every week MON-WED at 6 am.

**Comment by khalibartan** [comment]
@zemian I would like to work on this.

**Comment by litehead** [comment]
This feature would be also interesting

Currently in order to achieve this we have to:
1. build 1 trigger with dailytime interval schedule for certain week days
2. get n datetimes of start from it 
3. build n triggers with calendar week interval using these start dates
(n is amount of week days)
