### ISSUE TITLE
Jobs not marked for recovery are being recovered

### ISSUE THREAD

**Issue by HomoEfficio** [quartz-scheduler/quartz#318]
## Summary

Jobs which were not marked for recovery are still being recovered by other quartz instances in the clustering mode.

## Situation

- Running Quartz clustering with 3 nodes of Quartz Version 2.2.3
- No2 Instance went bad and No1 Instance recovered(reran) the jobs which was running in No2
![dmp-quartz-recovery-log-toquartz](https://user-images.githubusercontent.com/17228983/52398221-b72f5080-2afb-11e9-9735-05c272a561db.png)
- But the jobs were not marked for recovery
![dmp-quartz-clustering-error-toquartz](https://user-images.githubusercontent.com/17228983/52398630-1346a480-2afd-11e9-8145-89c09eb9487e.png)

- So the jobs of No2 must not be rerun by other instances, but they are rerun.

**Comment by zemian** [comment]
Hi @HomoEfficio ,

Your problem sounds very similar to #107. Please follow the solution provided there to see if it fix your issue.

If your problem continue to occur, please see https://github.com/quartz-scheduler/quartz/wiki/How-To-Submit-New-Issue

**Comment by HomoEfficio** [comment]
Thanks for the reply.

I'm not sure I read the #107 correctly, because there are so many talks, but if I'm right, to set `acquireTriggersWithinLock` to true is the solution in #107, am I right?

But in this document http://www.quartz-scheduler.org/documentation/quartz-2.x/configuration/ConfigJobStoreTX.html, it is not needed to set `acquireTriggersWithinLock` to true.

And I don't think my case and #107 is similar because my case is about `request recovery` but in #107 everybody talked about trigger acquisition and dead-lock. No one talked about `request recovery` there.

So I'm gonna submit a new issue following the guide you provided. Please review in the new issue.
