### ISSUE TITLE
Document of "Example 6 - Dealing with Job Exceptions" is wrong

### ISSUE THREAD

**Issue by zldiablo** [quartz-scheduler/quartz#33]
on http://www.quartz-scheduler.org/documentation/quartz-2.2.x/examples/Example6.html
**BadJob1** Example called 
`e2.refireImmediately();`
it should be
`e2.setRefireImmediately(true);`

**Comment by zemian** [comment]
Hi zldiablo, thanks for pointing this out. I agree that this is just a doc bug and needs to be updated.

However if you look at the actual code in 'quartz\distribution\examples\src\main\java\org\quartz\examples\example6\BadJob1.java', it actually has the correct code!

**Comment by zemian** [comment]
Close as invalid. We now points direct examples to the code without the need to repeat the documentation side.
