### ISSUE TITLE
Cron expression 'month' is wrong

### ISSUE THREAD

**Issue by weilai201** [quartz-scheduler/quartz#34]
Site: http://www.quartz-scheduler.org/documentation/quartz-2.2.x/tutorials/tutorial-lesson-06.html
The site says :"Months can be specified as values between 0 and 11, or by using the strings JAN, FEB, MAR, APR, MAY, JUN, JUL, AUG, SEP, OCT, NOV and DEC."
My test is : the value of month is between 1 and 12.

**Comment by zemian** [comment]
Yes, this looks like a doc bug. The correct range for month field is from 1-12.

**Comment by zemian** [comment]
This is fixed in quartz-scheduler/quartz-scheduler.org-site#12
