### ISSUE TITLE
Allow Job Excution to be pin to a cluster node

### ISSUE THREAD

**Issue by zemian** [quartz-scheduler/quartz#344]
It would be nice to able to configure certain specific jobs to allows run in a specific host name in cluster mode.

Currently users would have to write this logic into their job implementation to skip the work if host names match to some known list.

Other work around is not to use cluster env and place jobs into individual standalone schedulers.

**Comment by HiranChaudhuri** [comment]
I'd implement this slightly different but basically this is the functionality that I need, therefore
+1

What I'd do is
- assign labels to scheduler-instances
- specify required labes, preferred labes or not-wanted labels on the jobs
- Quartz needs to match the labels when choosing a trigger to fire...

This will allow to declare a job should run on one host, on a group of hosts, preferrably on some host or exclude specific hosts, meaning you can set affinity, anti-affinity or a bias.

**Comment by HiranChaudhuri** [comment]
Even better might be to
1) extend the scheduler with a strategy which trigger/job to pick next
2) implement the above algorithm as one of the strategies

**Comment by zemian** [comment]
Hi @HiranChaudhuri, The job+ triggers itself already has key, and these can be the labels. I think what we need is be able to specify keys to be pin/bound to a threadPool to be process. This will solve this problem and require minimum changes.

**Comment by HiranChaudhuri** [comment]
> Hi @HiranChaudhuri, The job+ triggers itself already has key, and these can be the labels. I think what we need is be able to specify keys to be pin/bound to a threadPool to be process. This will solve this problem and require minimum changes.

Sound good for me. So I am looking forward for the next release... :-)

**Comment by mederly** [comment]
Hello @HiranChaudhuri. As @zemian says we have had similar requirements described in #175; maybe a bit stronger as our customers require setting also thread limits per job types. The implementation I've made seems to work quite well in production for almost two years: https://github.com/Evolveum/quartz/tree/quartz-2.3.0.e2 (except for occasional https://jira.evolveum.com/browse/MID-4558 that looks harmless but should be resolved anyway, eventually).

**Comment by sajinieKavindya** [comment]
Hi @zemian . We use quartz scheduler and we are in a need of the feature #344. Would you please let me know the current status of this requested feature? If it is going to be included in the next release, appreciate if you can give me a hint of the next release date. =)

**Comment by mattiacirioloWS** [comment]
Hi all, we are interested in this feature too.
We think it might be interesting to add to the "Trigger" interface the "startHere()" and "startAlwaysOnNode(_nodeId_)" methods to start the execution on the node on which the Job is added to the Scheduler or on the specified node.
What do you think about?

Thanks and best regards.

**Comment by mederly** [comment]
@mattiacirioloWS I am not quite sure. The reasons are:

1. The method should be written in the language of execution groups, not nodes -- at least if it has to match current implementation of the pinning feature. So the method should be probably like setExecutionGroup(group). 
2. Methods that provide similar functionality are currently in the Scheduler interface. So I think that this method belongs there.

**Comment by HiranChaudhuri** [comment]
With so many good ideas (some of which contradict each other), would not not make sense to implement a strategy pattern (https://en.wikipedia.org/wiki/Strategy_pattern) and provide some default algorithms? That way everyone could easily use what is provided or override for further customization.

**Comment by mederly** [comment]
Strategy pattern is generally a good idea, although I am not quite sure it is applicable here. The method of "pinning" a job to a given node is quite dependent on appropriate DB representation. Current representation (in Evolveum-provided work) is using `EXECUTION_GROUP` column. So there's not much room for specifying the behavior using the Strategy pattern here.

**Comment by mattiacirioloWS** [comment]
> @mattiacirioloWS I am not quite sure. The reasons are:
> 
> 1. The method should be written in the language of execution groups, not nodes -- at least if it has to match current implementation of the pinning feature. So the method should be probably like setExecutionGroup(group).
> 2. Methods that provide similar functionality are currently in the Scheduler interface. So I think that this method belongs there.

Thanks for your reply, @mederly 
I agree with you on point 1.
As for point 2, I think that the Scheduler is common to all Jobs. Setting the execution group on the Scheduler means to define different scheduler also in the case we want that only one of the jobs in the system is executed on single node (or group of nodes) and not on the whole cluster, doesn't it?
In my opinion, a good place to define exceptions to the functioning of the Scheduler could be the Trigger, which defines the execution strategy for the single Job. What do you think about?

Thank you so much for support :+1:

**Comment by devurandom** [comment]
I am interested in a similar feature.

Context: Certain Quartz instances support certain jobs (they might implement the job class, but not a certain feature of it, or be currently not able to execute it).

What I am looking for: A way to prevent an instance from acquiring a job based on the result of a callback function [^1], or alternatively a way for instances to reject execution of jobs based on a callback [^2], so that another instance can try to acquire the job.  These callbacks need to be executed on the instance where the job would be executed.

How would I do that within the features Quartz offers currently?

I believe this is different from `org.quartz.TriggerListener#vetoJobExecution`, since if that returns `true` the job will not be executed at all, while I want it to be executed by a different instance.

[^1]: This callback would probably be called at around the time when `org.quartz.core.QuartzSchedulerThread#run` calls `org.quartz.spi.JobStore#acquireNextTriggers`?
[^2]: This callback would probably be called before `org.quartz.core.QuartzSchedulerThread#run` creates the `org.quartz.core.JobRunShell`?
