### ISSUE TITLE
doc typo issue

### ISSUE THREAD

**Issue by winger007** [quartz-scheduler/quartz#38]
http://www.quartz-scheduler.org/documentation/quartz-2.x/cookbook/UpdateTrigger.html

typo issue found for :
```
Trigger newTrigger = tb.withSchedule(simpleSchedule()
    .withIntervalInSeconds(10)
    .withRepeatCount(10)
    .build();
```
missing right parenthesis after withRepeatCount

should be
```
Trigger newTrigger = tb.withSchedule(simpleSchedule()
    .withIntervalInSeconds(10)
    .withRepeatCount(10))
    .build();
```

**Comment by zemian** [comment]
This is fixed in quartz-scheduler/quartz-scheduler.org-site#12
