### ISSUE TITLE
jobDataMap cannot be modified when thread is executing the job

### ISSUE THREAD

**Issue by KokinSSJ** [quartz-scheduler/quartz#387]
In my project we have distributed application installed on PCs + server.
App gets cron expression from server  which is in most cases something like "0 0 22 * * ?" so job is started every day at 10pm, during this time apps send request to the server to get changes. 
But using only this parameter we have high traffic spike at full hour.
To distribute it even more we have second parameter which is some random number, representing number of second for delay which has this instance of app waits until it can start sending request to the server. 
E.g. app.instance1 at 10pm start job but random value for this is 60, so waits 60sec before starts sending request to the server, app.instance2 starts at 10pm, but have value 900, so waits 15minutes before starts sending request.
Goal of this it to distribute more evenly the requests to the server.

So we implemented CronTrigger with setCronExpression, JobDetail with jobDataMap where there is passed delay + bunch of other parameters for task itself.
When job is executed at scheduled time,  from JobExecutionContext jobDataMap is extracted and from jobDataMap delay. Then called is Thread.sleep(delay).
And in this scenario all works fine.

But if app gets new cron expression and new instance delay then we need to update jobDataMap to execute at time and with new delay.
scheduler.rescheduleJob(triggerKey, trigger) works fine and jobs is scheduled with new cron expression, but we have a problem with passing new values jobDataMap to job.

The problem is that when job is still executing (so Quartz thread is working) and you schedule new job  "scheduler.scheduleJob(newJob, trigger)" then new execution of task (so the next day at 10pm) is still having previous jobDataMap with old values.
We use @DisallowConcurrentExecution, @PersistJobDataAfterExecution

I was trying to:
1. unscheduleJob(triggerKey) if scheduler.getJobDetail(jobKey) !=null and then scheduleJob with new jobDataMap, but task is executed according to cron expression but with old jobDataMap
2. rescheduleJob + addJob(jobDetail, true)
3. using interrupt as described in one of examples
4. instead of Thread.sleep() use simple while(elapsedTime<delay) (I know silly idea, but I had to check! :))

Do you know how to avoid such behaviour?
Maybe there is some way to build trigger using cron expression with delay?

**Comment by zemian** [comment]
Hi, This does not seems to be a bug issue.

If you use `@DisallowConcurrentExecution` and `@PersistJobDataAfterExecution` then there is no need to unschedule and re-schedule the job. You simply update the jobDataMap. And these seems to be working properly. You probably just want to add random delay in the job execution itself. Just beaware that might hold up your job execution on purpose.
