### ISSUE TITLE
Deadlock always occurs while delete job.

### ISSUE THREAD

**Issue by zhanjiejun** [quartz-scheduler/quartz#39]
org.quartz.JobPersistenceException: Couldn't remove job: Deadlock found when trying to get lock; try restarting transaction 
[See nested exception: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction]

**I deploy a cluster with 2 nodes, would it because i did'n set the acquireTriggersWithinLock property?**

**Comment by maratynsky** [comment]
@zhanjiejun Hello, can you share your solution?

**Comment by zhanjiejun** [comment]
set properties below

```
org.quartz.jobStore.lockHandler.class=org.quartz.impl.jdbcjobstore.UpdateLockRowSemaphore
org.quartz.scheduler.batchTriggerAcquisitionMaxCount=50
org.quartz.jobStore.acquireTriggersWithinLock=true
```
