### ISSUE TITLE
Include DB schema scripts in org.quartz-scheduler:quartz artifact

### ISSUE THREAD

**Issue by vpavic** [quartz-scheduler/quartz#4]
It would be much more convenient for the users if DB schema scripts were included in ```org.quartz-scheduler:quartz``` artifact rather than having to download the distribution archive and extract them from there.

This way the scripts would easily obtainable using the dependency management system of choice. In addition, this would also allow for a programmatic access to scripts since they would automatically be included in the classpath.

Many other popular frameworks take this approach, for example many Spring projects (Integration, Batch, Security...), Activiti BPMN, etc.

**Comment by vpavic** [comment]
Any feedback on this proposal?

It would be quite useful for the proposed Spring Boot auto-configuration support for Quartz Scheduler. See spring-projects/spring-boot#4299 for more details.

Thanks.

**Comment by jhouserizer** [comment]
I suppose there's no harm in doing so.   Though the reason they haven't been packaged like that over the previous 15 years of Quartz is the assumption that a large portion - perhaps even 95% - of users will want to modify them before using them.  E.g. changing the table name prefix, changing column widths (e.g. of the varchars)  etc.  to suit their needs.

**Comment by vpavic** [comment]
> Though the reason they haven't been packaged like that over the previous 15 years of Quartz is the assumption that a large portion - perhaps even 95% - of users will want to modify them before using them.

Interesting :) From my experience with projects using Quartz I don't remember we ever needed to change the default scripts (we've used it on Oracle and PostgreSQL).

Would you accept a PR to address this?
