### ISSUE TITLE
Asking about best configuration when using Quartz

### ISSUE THREAD

**Issue by ariawanzero** [quartz-scheduler/quartz#402]
Hello Anyone I want to ask something about Configuration or Other Option for Using Scheduller on My Service Project. I'm using this library for process big stream data. there are two service working paralel and concurrent for processing stream data and i'm setup my quartz scheduller for processing stream data on each service every 5 seconds, is it good enough? 
I just want to ask about other Opinion or Someone have same condtion like with best solution

**Comment by zemian** [comment]
Hi @ariawanzero 

Yes you can use Quartz for your service. 

See https://github.com/quartz-scheduler/quartz/wiki/How-To-Submit-New-Issue
