### ISSUE TITLE
scenario that should start schedule after this job is executed

### ISSUE THREAD

**Issue by LycheeHe** [quartz-scheduler/quartz#407]
I have a trigger
`Trigger taskTrigger = TriggerBuilder.newTrigger()
    .withSchedule(DailyTimeIntervalScheduleBuilder.dailyTimeIntervalSchedule()
    .withIntervalInMinutes(5))
    .build()`
a jobDetail
`JobDetail task= JobBuilder.newJob(Task.class).build()`
and a scheduler
`Scheduler scheduler = StdScheduleFactory.getDefaultScheduler();
scheduler.schdeuleJob(task, taskTrigger);
scheduler.start()`

the task is to copy file from remote server.
the scheduler runs perfect, but a problem will happen in a way:
if the task take more time (>5min) to execute, and the second schedule start copy file while the first schedule isn't finished the task. 
the program will copy the same file in multi-scheduler, the program re-write the same file again and again, which will cause endless loop.
Does anyone have a solution to solve this problem? Thx

**Comment by LycheeHe** [comment]
I want a solution to start the schedule after the job is finished.

**Comment by zemian** [comment]
Please ask questions in user forum group. This is for tracking quartz bug only. See https://github.com/quartz-scheduler/quartz/wiki/How-to-Submit-New-Issue

I would suggest you read through the FULL QUARTZ DOCS to see how to use it properly. Especially on Trigger MISFIRE policy.

**Comment by LycheeHe** [comment]
Thank you for guiding me to find an answer by myself. But I don't think quartz documentation is efficient for those special requirement because there have no key word searching engine in quartz website and less relative information when i search by Google. And there is no doubt that quartz do me a big favor.
