### ISSUE TITLE
Plans to release 2.4.0?

### ISSUE THREAD

**Issue by PawelLipski** [quartz-scheduler/quartz#409]
Looks like no issues are pending... https://github.com/quartz-scheduler/quartz/milestone/5

Quartz 2.4.0 will bump HikariCP version to 3.2.0 (from current 2.x) which also happens to be a transitive dependency of Play Framework 2.7.x (via play-slick 4.0.0). Also see https://github.com/enragedginger/akka-quartz-scheduler/issues/83.

**Comment by ilgrosso** [comment]
Guys, you really need to move HikariCP (or any other db pool dependency) as `provided`, Quartz is typically embedded in applications that already manage their db persistence...

**Comment by PawelLipski** [comment]
@ilgrosso  looks there's already https://github.com/quartz-scheduler/quartz/issues/306 for that... either way, the dependency change needs to be released in a new Quartz version.

**Comment by ilgrosso** [comment]
@PawelLipski thx, I overlooked that :+1:

**Comment by PawelLipski** [comment]
See my reservations to that approach, though https://github.com/quartz-scheduler/quartz/issues/306#issuecomment-477094819

**Comment by zemian** [comment]
Hi all, I plan to work on rest of the issues/PR's whenever I can on the master branch (target 2.4.0). Unless we have more volunteer contributors, it will be a while before a release comes. But again, I don't make releases, so if you guys will up vote this issue, folks from Terracotta might do a quick release if that's what you want.

However for those who can't wait, you can get pre-releases or snapshot here:

https://jitpack.io/#zemian/quartz/master-SNAPSHOT

**Comment by wdroste** [comment]
Any status on this? We're a year out from the last release..

**Comment by ilgrosso** [comment]
Very relevant, but I'm afraid closed anyway.
Time to look seriously for alternatives to Quartz.

**Comment by XhstormR** [comment]
It has been three years since the last release.

**Comment by wdroste** [comment]
Why is this closed if there's no release.
