### ISSUE TITLE
Tasks pause after system time is modified.  

### ISSUE THREAD

**Issue by zhaowenxishi** [quartz-scheduler/quartz#410]
I do know that "Tasks pause after system time is modified. " is reasonable.

If there is a task which will be triggerd at 12:00:00 2019/3/27. After it is registered, we modify the system time to 2019/3/20. Obviously, the task will paused for a long time, it's OK.

But if we have a task which triggers once an hour, last time it triggered at 12:00:00 2019/3/26. Then it will be triggered at 13:00:00 2019/3/26, but if we modify the time to 2019/3/20 for some tests or just an accident, it will be paused for a few days. 

Of course, the situation is reasonable. But for users, we don't really hope the task stopped for this kind  of sistuation. Cause we registered a simple LOOP job and hope it will trigger once an hour continually no matter it's year 1990 or 2020.

Firstly, I wanna know if Quartz has some supports for this kind of situations. And if not, would you please help me with the situation. We have requests to modify system time for some function, our plan is to refresh all the tasks every after the time modification. Then all the tasks will be triggerd properly just like they are registerd for the first time. Do you have some suggestions for me to handle the issue？

**Comment by zemian** [comment]
Hi, fire time of any trigger is depends on system time. If you go modified the system time while scheduler is running, then there is no guarantee of anything at all. If you must do this, then I would suggest you restart the scheduler after each system time has changed.
