### ISSUE TITLE
Doc files are missing in distribution

### ISSUE THREAD

**Issue by Jolter** [quartz-scheduler/quartz#414]
In http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/tutorial-lesson-10.html, it is stated:
"There are some sample configurations (including descriptions of the properties) in the “docs/config” directory of the Quartz distribution."

I can find no such directory in the Quartz 2.3.0 distribution. The only contents of "docs/" is a directory called "images" containing two files (see screenshot).

Likewise, I read on JDBC setup guide (lesson 9), "You can find table-creation SQL scripts in the “docs/dbTables” directory of the Quartz distribution" - this is also missing.
I see that the table-creation files are present in some older distributions, but I cannot find the sample configurations in any of them. (In fact, most of the older distributions are impossible to open in 7Zip, it complains that the archives are not valid. I should check another gunzip tool.)

![image](https://user-images.githubusercontent.com/9645307/55147708-2c57f300-5147-11e9-8b8c-c300d4f022a1.png)

**Comment by Jolter** [comment]
Looks like the SQL files are in the repo at /quartz-core/src/main/resources/org/quartz/impl/jdbcjobstore/*.sql, but they are not being copied into the distribution on build.

**Comment by Jolter** [comment]
I cloned the repo and did `./mvnw package`, but I didn't get any `.gz` or ` .tgz` file. Just the jars under each `target/` dir.
Shall I assume the distributions are assembled by hand?

**Comment by zemian** [comment]
Hi Jolter, 

These links are outdated. AFAI, there were any sample of quartz config in the repository for a long time. If you are looking for some, you can check out here: https://github.com/zemian/quartz-starter/tree/master/learn/src/main/resources/zemian/quartzstarter

As you have found out that the SQL files has moved to new folder now.

Last question you have is where the package? One way to build the package is `mvn package -DskipTests -Pdist`, and the output should be under `distribution/target`. But unfortunately it requires access to `http://www.terracotta.org/download/reflector/releases` that is no longer accessible to public. (Quartz release and distribution package are to be run and release by Terracotta engineers only). I think we should make it so public users should able build it on their own, but we don't have the time to fix it yet.

NOTE that the package contains nothing but just convenient package of all jars together for you to download. The easiest way to use quartz is to simply use Maven dependency in your own project.

**Comment by zemian** [comment]
BTW, If you want to fix the user dist build, please create a separate feature request to request on rework for the "distribution" to be build-able using public repo access. We can keep this Issue for fixing outdated documentation links only.

**Comment by Jolter** [comment]
Hi Zemian,

Thanks for answering.

The package build is not important to me. It was just my attempt to debug
whether the missing docs were due to a build script error, or some manual
error.
I suppose there are (at least) two possible fixes.

Either:
1. The SQL files are essential to any user who wants to set up database
jobstore. Hence they should be included in the distro, not only in the
github repo. (Not all users will be able to find them there.) It seems like
it should be trivial to adjust the Maven build to ensure they are part of
the distro again.
Or:
2. The documentation on the web site needs to be updated to point to the
SQL files in the repo, instead of referring to the distro file.

I would suggest that also the rest of the documentation should be part of
the distro.

BR,
Joel

**Comment by shea-demandbase** [comment]
Similarly surprised that the docs are out of date & the scripts aren't being included in build.

**Comment by aravindparappil46** [comment]
Same here. I was expecting to find `dbTables` SQL script to set up the QRTZ tables inside the distribution. This issue pointed me in the right direction!

**Comment by norrs** [comment]
You can navigate to https://github.com/quartz-scheduler/quartz/tree/quartz-2.3.x/quartz-core/src/main/resources/org/quartz/impl/jdbcjobstore (branch 2.3.x) for finding the SQL scripts for now until the distribution package gets fixed to package em under /docs/dbTables again. 

Found via https://github.com/quartz-scheduler/quartz/wiki/How-to-Setup-Databases#first-time-postgresql-server-setup
