### ISSUE TITLE
Start project loss of data

### ISSUE THREAD

**Issue by Jossc** [quartz-scheduler/quartz#415]
Thank you very much for answering my question，
In a clustered environment，The deployment of project, The table 'qrtz_cron_triggers' loss of data。
I used version 2.3,
spring boot version 1.5.2.RELEASE.

This is my initialization code
`
    @Bean("schedulerFactoryBean")
    public SchedulerFactoryBean schedulerFactoryBean(@Qualifier("triggerForUser")
                                                             Trigger triggerForUser,
                                                     @Qualifier("triggerForFollower") Trigger triggerForFollower,
                                                     @Qualifier("prepareTrigger") Trigger prepareTrigger) throws IOException {
        SchedulerFactoryBean factory = new SchedulerFactoryBean();
        factory.setOverwriteExistingJobs(true);
        factory.setDataSource(source);
        factory.setStartupDelay(15);
        factory.setQuartzProperties(quartzProperties());
        factory.setTriggers(triggerForUser, triggerForFollower, prepareTrigger);
        factory.setAutoStartup(true);
        return factory;
    }`

**Comment by zemian** [comment]
Hi, this is not enough info to file a bug report. Please read https://github.com/quartz-scheduler/quartz/wiki/How-to-Submit-New-Issue
