### ISSUE TITLE
Quartz does not honor manual updates to qrtz_triggers table

### ISSUE THREAD

**Issue by grobinson-r7** [quartz-scheduler/quartz#42]
**Steps to to reproduce**
1. Create and persist a trigger with misfire instruction = 0 
2. Update code base using API to use a new misfire instruction (e.g. 2)
3. New triggers persisted will be correct, however old triggers will not update
4. Manually updating the misfire_instr on quartz_triggers will persist until the next trigger fire time, when the record is replaced with the original misfire instruction - it appears that this is coming from the blob data persisted to the database.

**Comment by zemian** [comment]
Manual update to DB is not recommended. You should use the Quartz API where possible.
