### ISSUE TITLE
Website documentation and JavaDoc for history plugins is wrong

### ISSUE THREAD

**Issue by Vampire** [quartz-scheduler/quartz#427]
Said documentations for job and trigger history plugins state that it logs with JCL while they are logging with SLF4J (now).

**Comment by Vampire** [comment]
> Is this still relevant?

Yes
> If so, what is blocking it?

Your time
> Is there anything you can do to help move it forward?

No

**Comment by Vampire** [comment]
Still relevant, please reopen

**Comment by Vampire** [comment]
.

**Comment by Vampire** [comment]
Wake up stupid annoying @stale bot

**Comment by jhouserizer** [comment]
thanks!
