### ISSUE TITLE
set misfire instruction is not work?

### ISSUE THREAD

**Issue by kibear** [quartz-scheduler/quartz#43]
Hi, i define two triggers, they fire on the same time, i set every seconds.
of course,  set org.quartz.threadPool.threadCount = 1

so one job cannot fire, because one thread at one time cannot execute two job, and i read quartz document, I find: 
http://www.quartz-scheduler.org/documentation/quartz-2.2.x/examples/Example5.html
 withMisfireHandlingInstructionNowWithExistingCount()) // set misfire instruction

but it not work, still only one job execute, other one job cannot execute.

**Comment by jhouserizer** [comment]
There is insufficient information here to investigate anything.

**Comment by zemian** [comment]
Closing outdated, unresolved issues. Please, reopen if still relevant.
