### ISSUE TITLE
Every 90 minutes, how cron expressions will be generated?

### ISSUE THREAD

**Issue by namjitharavind** [quartz-scheduler/quartz#433]

**Comment by Jolter** [comment]
Can you please clarify this question? It's difficult to understand what you are looking for.

**Comment by regmebaby** [comment]
@namjitharavind Maybe you have to define two cron triggers for such a job:
0 0 0/3 ? * * * --> every three full hours
0 30 1/3 ? * * * --> every three full hours, shifted by 90min=1.5h
