### ISSUE TITLE
Quartz scheduled Jobs neither executed and not reported by misfire handler

### ISSUE THREAD

**Issue by fossf** [quartz-scheduler/quartz#44]
Moving from https://jira.terracotta.org/jira/browse/CDV-1673

Error -
2016-08-01 10:29:58 DEBUG JobStoreTX:3949 - MisfireHandler: scanning for misfires...
2016-08-01 10:29:58 DEBUG JobStoreTX:3198 - Found 0 triggers that missed their scheduled fire-time.
<Aug 1, 2016 10:30:00 AM IST> <Emergency> <oracle.dfw.incident> <BEA-000000> <incident 178 created with problem key "DFW-99998 [java.lang.ClassNotFoundException][weblogic.utils.classloaders.ChangeAwareClassLoader.loadClass][EmpEngApp]">
<Aug 1, 2016 10:30:00 AM IST> <Error> <oracle.odl.management.logquery> <BEA-000000> <unexpected exception: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Double

Please note this doesn't occur always but only sometimes. So can't understand where I am going wrong.Any help will be appreciated.
[RelevantFiles.zip](https://github.com/quartz-scheduler/quartz/files/394735/RelevantFiles.zip)

**Comment by mandritaca** [comment]
Sometimes the scheduled job doesn't execute and it also doesn't show up as misfired. When I checked QRTZ_TRIGGER table I find that the trigger_status='ACQUIRED' but it doesn't move into WAITING state.I have uploaded the relevant logs which shows series of Class not found exception and nothing more. I have found this behaviour more in the case when a scheduled job has executed once on it's scheduled time and is scheduled to run again on the next fire time.

**Comment by mandritaca** [comment]
Test

**Comment by disaacson** [comment]
When we restart a scheduler process any triggers with jobs running get stuck in ACQUIRED state and we have to manually clean them up. What is supposed to happen here?

**Comment by jhouserizer** [comment]
Generally speaking, upon a restart the scheduler should reset any "ACQUIRED" triggers back to "WAITING" state.  And this generally works, but apparently there may be some error scenario during the process of reseting the trigger states that causes them to be left in ACQUIRED state (which in turn causes them to be ignored).

**Comment by shukladhaval25** [comment]
Currently i am also facing same issue. Like i have schedule job for three different time and randomly it is failing and not execute job event it was not fall in category of misfire schedule also. Any idea how can we handle this failing situation? If this is bug from Quartz then is it get fix? I am using Quartz.Net 2.3.3.0.

**Comment by Lajos-Racz** [comment]
Hi,
I am still having this issue. Some jobs just would not start without any error message. Can you pls advise?
Thx.

**Comment by srisudarsan** [comment]
Hello @fossf  @Lajos-Racz  where you able to fix this ?
@jhouserizer we are still seeing this using quartz 2.3.2
Seems related to https://github.com/quartz-scheduler/quartz/issues/218, can we have this addressed please ?
