### ISSUE TITLE
Switch to a newer version of HikariCP

### ISSUE THREAD

**Issue by oneiros-de** [quartz-scheduler/quartz#441]
We have a project with spring boot 2.1.4 and are using quartz 2.3.1. I wanted to switch our project to spring-boot-actuator/micrometer but ran into https://github.com/spring-projects/spring-boot/issues/16656 : Spring Boot Acuator needs a newer Hikari than the one Quartz uses (com.zaxxer:HikariCP-java7); Spring Boot uses com.zaxxer:HikariCP:3.2.0

Please update your depedency.

**Comment by oneiros-de** [comment]
@snicoli So this will be fixed in 2.1.5?

**Comment by snicoll** [comment]
If you take the time to follow the link I already gave, you can see yourself the PR was merged in `2.1.5`

**Comment by oridool** [comment]
I'm using latest springboot **2.3.2**, and have the same issue mentioned above and also in 
https://github.com/spring-projects/spring-boot/issues/16489 

With springboot 2.3.1 , I didn't get this error.
As a woraround I added to my dependency:
```java
    implementation ('org.springframework.boot:spring-boot-starter-quartz') {
        exclude group: 'com.zaxxer', module: 'HikariCP-java7'
        // workaround for https://github.com/spring-projects/spring-boot/issues/16489
    }
```

Before this exclusion, I had the following dependencies:

+--- org.springframework.boot:spring-boot-starter-quartz -> 2.3.2.RELEASE
|    +--- org.springframework.boot:spring-boot-starter:2.3.2.RELEASE (*)
|    +--- org.springframework:spring-context-support:5.2.8.RELEASE (*)
|    +--- org.springframework:spring-tx:5.2.8.RELEASE (*)
|    \--- org.quartz-scheduler:quartz:2.3.2
|         +--- com.mchange:mchange-commons-java:0.2.15
|         +--- **com.zaxxer:HikariCP-java7:2.4.13**
|         |    \--- org.slf4j:slf4j-api:1.7.21 -> 1.7.30
|         \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.30


I'm not sure if that is an issue related to Quartz or to SpringBoot...

**Comment by snicoll** [comment]
> I'm not sure if that is an issue related to Quartz or to SpringBoot...

Not related to Quartz so please ignore this. This is taken care on our side, more info: https://github.com/spring-projects/spring-boot/issues/16489#issuecomment-664872466
