### ISSUE TITLE
Timed tasks trigger repeated executions, 2 times at the same time,why??

### ISSUE THREAD

**Issue by taotao2014** [quartz-scheduler/quartz#463]
Version: 2.3.3.0

Timed tasks trigger repeated executions, 2 times at the same time,why??

Is it possible to cause this problem if server cluster time synchronization and time rewind?？？？

**Comment by lmtoc** [comment]
quartz will execute the job  server time rewind, even if the job has finished at the last same time

**Comment by lmtoc** [comment]
> Version: 2.3.3.0
> 
> Timed tasks trigger repeated executions, 2 times at the same time,why??
> 
> Is it possible to cause this problem if server cluster time synchronization and time rewind?？？？

quartz will execute the job server time rewind, even if the job has finished at the last same time
