### ISSUE TITLE
StdRowLockSemaphore does not work properly in DB2

### ISSUE THREAD

**Issue by grzegrzk** [quartz-scheduler/quartz#464]
Quartz DB locking does not work with DB2
----
When quartz is configured to use `org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX` and `org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate` with `org.quartz.jobStore.isClustered=true` then StdRowLockSemaphore does not work as indented on DB2 - it allows to run code concurrently when it should prevent concurrent access.

Quartz uses "FOR UPDATE" SQL clause to synchronize access to some shared resources. Example select issued by quartz looks like this:

`SELECT * FROM QRTZ_LOCKS WHERE SCHED_NAME = 'TestScheduler' AND LOCK_NAME = 'TRIGGER_ACCESS' FOR UPDATE;`

Unfortunately by default this statement does not acquire update-lock in DB2. To achieve the goal one must add "WITH RS" at the end of the statement, like this:

`SELECT * FROM QRTZ_LOCKS WHERE SCHED_NAME = 'TestScheduler' AND LOCK_NAME = 'TRIGGER_ACCESS' FOR UPDATE WITH RS;`

Below I will try to explain what is going on in DB2 and provide links to DB2 documentation about it, but unfortunately I could not find single resource mentioning that "WITH RS" is required to achieve goal that in other databases is done by simple "FOR UPDATE"

The proof there are no locks when SQL from default Quartz installation is used
----
When someone does this select without commiting transaction:

`SELECT * FROM QRTZ_LOCKS WHERE SCHED_NAME = 'TestScheduler' AND LOCK_NAME = 'TRIGGER_ACCESS' FOR UPDATE`

Then the table does not have any locks:

`SELECT * FROM TABLE (SYSPROC.MON_GET_LOCKS(CLOB('<table_schema>TESTSCHEMA</table_schema><table_name>QRTZ_LOCKS</table_name>'), -2));`
`0 rows retrieved in 25 ms (execution: 4 ms, fetching: 21 ms)`

But after this statement:
`SELECT * FROM QRTZ_LOCKS WHERE SCHED_NAME = 'TestScheduler' AND LOCK_NAME = 'TRIGGER_ACCESS' FOR UPDATE WITH RS`

The locks are here:
`SELECT * FROM TABLE (SYSPROC.MON_GET_LOCKS(CLOB('<table_schema>TESTSCHEMA</table_schema><table_name>QRTZ_LOCKS</table_name>'), -2));`

> APPLICATION_HANDLE	MEMBER	LOCK_NAME	LOCK_OBJECT_TYPE_ID	LOCK_OBJECT_TYPE	LOCK_MODE	LOCK_CURRENT_MODE	LOCK_STATUS	LOCK_ATTRIBUTES	LOCK_RELEASE_FLAGS	LOCK_RRIID	LOCK_COUNT	LOCK_HOLD_COUNT	TBSP_ID	TAB_FILE_ID
> 353	0	02002100040000000000000052	BLOB(x'52')	ROW	U		G	0000000000000000	0000000000000001	0	1	0	2	33
> 353	0	02002100000000000000000054	BLOB(x'54')	TABLE	IX		G	0000000000202000	0000000000000001	0	1	0	2	33

`2 rows retrieved starting from 1 in 32 ms (execution: 6 ms, fetching: 26 ms)`

The simple way to verify that there are indeed proper locks is to open two separate connections to DB2 with disabled autocommit and to check that seconds select will hung untill first connection either commits or rollbacks.

DB2 documentation links
----
In DB2 the "FOR UPDATE" clause is described here:
https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.sql.ref.doc/doc/r0059218.html

The documentation says "The FOR UPDATE clause identifies the columns that can be targets in an assignment clause in a subsequent positioned UPDATE statement.".
The documentation does not say anything about locking strategies involved, but from my testing it seems that DB2 just checks that there is no lock for this row but does not acquire new lock for it.

The addition of "WITH RS" changes isolation level for given statement:
https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.sql.ref.doc/doc/r0059221.html

By default isolation level is taken from isolation level of connection, and most popular (and default) isolation level for connection is "CS" (Cursor Stability) with is equivalent of "Read Committed" from SQL standard. As one can see from documentation it is not possible to provide 
"lock-request-clause" when "CS" isolation is used - I couldn't find explicit statement that DB2 does not use any locks for selects with "CS" isolation but apparently this is a case.
To have locks one must provide at least "RS" isolation level (Read Stability - equivalent of Repeatable Read from SQL standard) and then one can provide lock request clause described here:

https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.sql.ref.doc/doc/r0059222.html

And again I could not find what is default value if this clause is not provided, but apparently this is either "USE AND KEEP UPDATE LOCKS" or "USE AND KEEP EXCLUSIVE LOCKS". 
In other words it is enough to add "WITH RS" at the end of the statement and do not bother to add explicit lock-request-clause.

Workaround
----
For the time being the workaround is to provide own implementation of quartz semaphore for DB2.

```
package com.example.quartz;

import org.quartz.impl.jdbcjobstore.StdRowLockSemaphore;

/**
 * Extension of {@link StdRowLockSemaphore} from quartz with fix for DB2. It must be configured in quartz properties
 * to have effect (property "org.quartz.jobStore.lockHandler.class").
 */
public class Db2QuartzSemaphore extends StdRowLockSemaphore {

    /**
     * Manual tests showed that DB2 allows many connections to have lock acquired by "SELECT ... FOR UPDATE".
     * To have exclusive lock one must add "WITH RS" at the end, so here is the fix.
     */
    public static final String SELECT_FOR_LOCK_FOR_DB2 = "SELECT * FROM "
            + TABLE_PREFIX_SUBST + TABLE_LOCKS + " WHERE " + COL_SCHEDULER_NAME + " = " + SCHED_NAME_SUBST
            + " AND " + COL_LOCK_NAME + " = ? FOR UPDATE WITH RS";

    /**
     * Constructor
     */
    public Db2QuartzSemaphore() {
        setSQL(SELECT_FOR_LOCK_FOR_DB2);
    }
}
```

And then configure it in quartz.properties:
`quartz.jobStore.lockHandler.class=com.example.quartz.Db2QuartzSemaphore`

**Comment by dgeissl** [comment]
That's a very good point, I guess that hit us too as we got some DeadLocks during cluster checkIn. Thanks for pointing that out.
