### ISSUE TITLE
Hikari CP configuration with Quartz

### ISSUE THREAD

**Issue by niaggarw** [quartz-scheduler/quartz#465]
Hi @zemian,

Thanks for all the information you provided. I am still facing an issue regarding this setup. I am using the following versions:
Hikari cp: 3.1.0
Quartz: 2.4.0
java 8

My quartz.properties file looks like:
org.quartz.dataSource.DS.driver = com.mysql.cj.jdbc.Driver
org.quartz.dataSource.DS.URL = jdbc:mysql://127.0.0.1:3306/db51?useOldAliasMetadataBehavior=true&rewriteBatchedStatements=true
org.quartz.dataSource.DS.user =root
org.quartz.dataSource.DS.password =root
hibernate.dialect=org.hibernate.dialect.MySQL57InnoDBDialect
org.quartz.jobStore.driverDelegateClass = org.quartz.impl.jdbcjobstore.StdJDBCDelegate
org.quartz.dataSource.DS.testQuery = select now()
org.quartz.dataSource.DS.testConnection= false
org.quartz.dataSource.DS.readReplica.URL = jdbc:mysql://127.0.0.1:3306/db51?useOldAliasMetadataBehavior=true
org.quartz.dataSource.DS.connectionProvider.class=org.quartz.utils.HikariCpPoolingConnectionProvider

My queries are:

Do i need HikariCp-java jar as well, if yes then which version of this jar will work with my setup?
I am getting an error continuously despite of trying everything you mentioned is
Error creating bean with name 'schedulerFactoryBean' defined in ServletContext resource [/WEB-INF/servlet.xml]: Invocation of init method failed; nested exception is org.quartz.SchedulerException: ConnectionProvider class 'org.quartz.utils.HikariCpPoolingConnectionProvider' could not be instantiated. [See nested exception: java.lang.InstantiationException: org.quartz.utils.HikariCpPoolingConnectionProvider]

Kindly Suggest.

**Comment by melloware** [comment]
I don't think you need this line..
```
org.quartz.dataSource.DS.connectionProvider.class=org.quartz.utils.HikariCpPoolingConnectionProvider
```

Just omit it and as long as HikariCp is on your classpath and C3P0 is NOT on your classpath it should use it.
