### ISSUE TITLE
Impossible Exception is thrown and terminate the taskScheduler Thread

### ISSUE THREAD

**Issue by thomasnikolay** [quartz-scheduler/quartz#466]
### Error Description
The following error occurred on our AS. After the taskScheduler was terminated and no job was executed anymore. 

> #2.0#2019 07 13 23:15:26:061#+0200#Warning#com.sap.engine.core.thread.impl3.UncaughtExceptionHandler#
> com.sap.ASJ.krn_thd.000109##***#C0000A31E8667ABF0000000300006131#662169850000000026#***/***#com.sap.engine.core.thread.impl3.UncaughtExceptionHandler#Guest#0##466497F52C0610069CB2ADD13A30B742#466497f52c0610069cb2add13a30b742##0#Thread[taskScheduler_QuartzSchedulerThread,5,QuartzScheduler:taskScheduler]#Plain##
> The following unhandled exception: [java.lang.AssertionError] was detected in [Thread[taskScheduler_QuartzSchedulerThread,5,QuartzScheduler:taskScheduler]]
> [EXCEPTION]
> java.lang.AssertionError
> 	at org.quartz.CronExpression.<init>(CronExpression.java:296)
> 	at org.quartz.impl.triggers.CronTriggerImpl.clone(CronTriggerImpl.java:340)
> 	at org.quartz.simpl.RAMJobStore.acquireNextTriggers(RAMJobStore.java:1439)
> 	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:272)
> 

### Analyze
This should not happen according to code and the comment. Because the trigger is only cloned and the expression should be parseable. Do you know what can raise such an error?
From my point of view, it should not throw an assertion error because it terminate the thread and no job is executed anymore. At least, it should be printed out the error message of the parsing. 

https://github.com/quartz-scheduler/quartz/blob/ce1650f2bd23166b913a342a73c5c62e30d73632/quartz-core/src/main/java/org/quartz/CronExpression.java#L296

**Comment by 31KM** [comment]
Just to keep you updated: it seems that this was caused by a bug in the used SAP JVM on POWER9.
