### ISSUE TITLE
Strange behavior of quartz in cluster configuration

### ISSUE THREAD

**Issue by nianhang** [quartz-scheduler/quartz#469]
[QuartzScheduler_CrawlerScheduler-ClusterManager] org.quartz.impl.jdbcjobstore.JobStoreTX - This scheduler instance is still active but was recovered by another instance in the cluster.  This may cause inconsistent behavior.

**Comment by nandkumariitr** [comment]
Have you found any solution. We are also seeing the same behavior where it is leading us to ABA behavior means recoverd jobs are getting picked up by 2 nodes at the same time.
