### ISSUE TITLE
ClassNotFoundException when adding jobs through QuartzSchedulerMBean API

### ISSUE THREAD

**Issue by xmoravej** [quartz-scheduler/quartz#47]
QuartzSchedulerMBeanImpl.addJob method invokes JobDetailSupport.newJobDetail to create a JobDetail instance before the job detail is registered with the scheduler. JobDetailSupport.newJobDetail uses Class.forName to load the job implementation class. This works only if the job implementation class can be loaded by the class loader that loaded the JobDetailSupport class and this is not always the case. For example, this is a very common Quartz deployment scenario:

```
App.ear
 |
 +--- lib
 |    |
 |    +--- quartz-x.y.z.jar
 |
 +--- App1.war
 |      |
 |      +--- WEB-INF/classes or WEB-INF/lib /* possibly contains Quartz job impl classes */
 |
 +--- EJBJar.jar /* possibly contains Quartz job impl classes */
```

In this scenario, when you attempt to add a new job through the QuartzSchedulerMBean API, it fails, because the Quartz class loader cannot see classes in WAR and EJB JAR modules.

Various Quartz components consistently use the ClassLoadHelper to load job implementation classes as well as other classes that may not reside on the Quartz scheduler's classpath. JobDetailSupport does not make use of the ClassLoadHelper. This severly limits the use of the Quartz MBean API to only one Quartz deployment scenario where Quartz API and job implementation classes are all loaded through the Quartz API class loader (or any of its parent class loaders).

I have implemented a fix for Quartz 2.2.1 and I am attaching the relevant patches for the modified classes in the picture below.

Please consider including the patch in Quartz 2.2.4. Thank you.

Thank you,
Jan

[quartz-2.2.1-patches.zip](https://github.com/quartz-scheduler/quartz/files/411603/quartz-2.2.1-patches.zip)

![quartz-changed-classes](https://cloud.githubusercontent.com/assets/12745537/17561305/ad092a62-5f25-11e6-8553-4197b5e678e1.png)

**Comment by jhouserizer** [comment]
Could you please submit the patch as a PR for review?
