### ISSUE TITLE
Couldn't retrieve job due to an AdoJobStore conversion error

### ISSUE THREAD

**Issue by josephadams-izenda** [quartz-scheduler/quartz#494]
Hi, I'm a developer in my company and we use Quartz for scheduling items. One of our customers recently encountered an error while retrieving job information in the ADOJobStore and I wanted to know if this has been encountered before by anyone. I have attached the full error with the stack trace to this issue.

[RetrieveJobFailed.txt](https://github.com/quartz-scheduler/quartz/files/3637613/RetrieveJobFailed.txt)

**Comment by chrisdennis** [comment]
Pretty sure you want to file this here: https://github.com/quartznet/quartznet/issues
