### ISSUE TITLE
OSGI : Unable to resolve.. missing requirement.. (osgi.wiring.package=commonj.work)

### ISSUE THREAD

**Issue by ahhughes** [quartz-scheduler/quartz#5]
Hi,

Sorry I am not an OSGI export, hoping someone could check this out and validate this issue.

I'm unable to use quartz inside an OSGI bundle with Felix (even with the following decalared optional). The import "commonj.work" appears to be incorrect. I am not sure what this java package is, but I also suspect that other OSGI containers might still work with the optional declaration, just not in my case.

So should this import actually be in the MANIFEST.MF ?.  

https://github.com/quartz-scheduler/quartz/blob/master/quartz/pom.xml#L232

Cheers.

**Comment by eximius313** [comment]
I also have the same issue.

**Comment by eximius313** [comment]
Ok, if you use this bundle: `org.apache.servicemix.bundles:org.apache.servicemix.bundles.quartz:2.3.0_2`, `commonj.work` is no longer required
