### ISSUE TITLE
Is there ideal solution to Daylight Saving Problem (One Feature Request)

### ISSUE THREAD

**Issue by kunkun-tang** [quartz-scheduler/quartz#51]
Hi Quartz communities,

Because of the maturity and stability of Quartz, our work flow system is using Quartz library. We can't use UTC directly, since many of our jobs have to depend on PDT/PST. I've read through the [daylight saving part](http://www.quartz-scheduler.org/documentation/faq.html#FAQ-daylightSavings) of Quartz documentation. However, Both CronTrigger and SimpleTrigger can not meet our requirement.

We are using CronTrigger, but 2:00-3:00 job will be missed when daylight saving changes, you know. Do you have any hacks to let jobs delay to run (no skip) at that day, if the job is a daily job.

**Comment by zemian** [comment]
That's how we design the Cron and Simple Trigger to be. There are many other triggers available from the library as well, please ensure you read through them. The best way to avoid DST is not to use any Calendar base trigger (eg: SimpleTrigger)

If you must use Calendar based Trigger, then you can try create Listener to specially detect when DST occur, then you simply invoke the job manually in your listener.
