### ISSUE TITLE
Equals should be implemented in all Trigger implementation

### ISSUE THREAD

**Issue by roman-ivanov-vector** [quartz-scheduler/quartz#510]
AbstractTrigger have implementation of `equals` - https://github.com/quartz-scheduler/quartz/blob/master/quartz-core/src/main/java/org/quartz/impl/triggers/AbstractTrigger.java#L836-L845

But non of actual implementations have them, so it mean that all Triggers are equal if have the same key.  
That make complication to figure out if scheduling is actually changed to reschedule.

Example of Trigger without equals: https://github.com/quartz-scheduler/quartz/blob/master/quartz-core/src/main/java/org/quartz/impl/triggers/CronTriggerImpl.java 

Example of problem of sample classes: https://stackoverflow.com/a/54481355

Expected: all implementations of Trigger should have implementation of `equals`.

**Comment by chrisdennis** [comment]
The by-design equals contract of Triggers is documented in the Trigger interface:
```java
/**
 * Trigger equality is based upon the equality of the TriggerKey.
 * 
 * @return true if the key of this Trigger equals that of the given Trigger.
 */
public boolean equals(Object other);
```

**Comment by romani** [comment]
Is there way to compare scheduling/trigger ?

**Comment by chrisdennis** [comment]
Maybe? I guess it depends on how you define "equal" right? Depending on what trigger types you use this could be anything from relatively simple to code all the way to impossible (or at least a perfect solution would be impossible). What kind of triggers are you using?

**Comment by romani** [comment]
@chrisdennis , thank a lot for continuing discussion.

>  I guess it depends on how you define "equal" right?

yes, so my simple assumption was that it is based on whole content of Triggers that user can define. If I created `triger1` named "mytrigger" scheduled each 1 hour, and `trigger2` named "mytrigger" scheduled each 2 hours. I think it is a bit reasonable (at least as first thought) to consider them NOT equal. If I miss something , please a reason why `equals` is limited for name only? is there some explanation ? or special cases where it is become obvious.

> What kind of triggers are you using?

I am new to code base and quartz so I might not understand something ... where are Triggers configured in code, on moment of app start it takes all job/triggers from DB and compare with what app is having and if something is different then job need to be rescheduled. Reasonable solution is simply replace job/triggers, but team warned me that it is not good and can result in unexpected behavior and problems (something I also need to investigate). 
I am using  CronTrigger and SimpleTrigger and did some ugly hack code:
```
  private static boolean compareSheduling(Trigger trigger1, Trigger trigger2) {
    boolean result = true;
    if (trigger1 instanceof CronTrigger && trigger2 instanceof CronTrigger) {

      CronTrigger cronTrigger1 = (CronTrigger)trigger1;
      CronTrigger cronTrigger2 = (CronTrigger)trigger2;
      result = cronTrigger1.getPriority() == cronTrigger2.getPriority()
          && cronTrigger1.getCronExpression().equals(cronTrigger2.getCronExpression());

    } else if (trigger1 instanceof SimpleTrigger && trigger2 instanceof SimpleTrigger) {

      SimpleTrigger simpleTrigger1 = (SimpleTrigger)trigger1;
      SimpleTrigger simpleTrigger2 = (SimpleTrigger)trigger2;
      result = simpleTrigger1.getPriority() == simpleTrigger2.getPriority()
          && simpleTrigger1.getRepeatCount() == simpleTrigger2.getRepeatCount()
          && simpleTrigger1.getRepeatInterval() == simpleTrigger2.getRepeatInterval();
    }
    return result;
  }
``` 
to ease problem for some time for cases that I need only.

But it is better to have better implementation for sure. We might end up with better code later on, but before contributing code back to quartz I would like to get acceptance on what is right from maintainers.
