### ISSUE TITLE
Invite to the quartz user support group?

### ISSUE THREAD

**Issue by yashdoshi** [quartz-scheduler/quartz#525]
Hi there! 
Can you add me to the quartz user support group? Google groups doesn't let you request membership. 

Thank you!

**Comment by chrisdennis** [comment]
No... since your email address isn't visible to me on GitHub. I am working on getting the quartz group opened up again (not sure how/why it became private in the first place).  I'll comment back when this is done.

**Comment by chrisdennis** [comment]
Should be fixed... see if you can add yourself now.

**Comment by yashdoshi** [comment]
Looks good now. Thanks
