### ISSUE TITLE
定时任务

### ISSUE THREAD

**Issue by lichengliang1** [quartz-scheduler/quartz#528]
我想要一个cron表达式，每45分钟触发一次。

根据文档，我创建了 0 0/45 * *？表达式。
但它会以12:00，12:45，13:00，13:45，14:00的模式被执行。
但我期望和想要的是在12:00，12:45，13:30，14:15被执行。

**Comment by yangjiajun2014** [comment]
你不要用cron，简单的定时调度频率不就行了，设置一个整点的startTime

**Comment by miRUAcleInjoker** [comment]
一个cron表达式不行， 可以分为几个表达式来实现。 Job 支持 多 trigger

**Comment by NameNolen** [comment]
`0 */45 * *?`  可以吧。[cron 表达式](https://crontab.guru/#0_*/20_*_*_*)

**Comment by lichengliang1** [comment]
已解决
