### ISSUE TITLE
Quartz with MYSQL8.0

### ISSUE THREAD

**Issue by jiveshpkuniyil** [quartz-scheduler/quartz#532]
I am using .Net Core Application with MySql 8.0(Linux).If i create a Day/Week job, Then changes reflected in MySql database but it will not trigger but if i configure for Minutes it will work. Before we implemented Quartz job scheduler with MSSQL is perfectly working with .Net Core Application. Following are configuration changes i have made when i change MSSQL to MySql.
MSSQL
-----------------
<pre>driver Delegate Type - Quartz.Impl.AdoJobStore.SqlServerDelegate, Quartz</pre>
<pre>Database Provider - SqlServer</pre>

MYSQL
-----------------
<pre>driver Delegate Type - Quartz.Impl.AdoJobStore.MySQLDelegate, Quartz</pre>

<pre>Database Provider - MySql</pre>

Do i need any changes related with this in application and kindly do needful to fix this issue.

**Comment by chrisdennis** [comment]
I think you want https://github.com/quartznet/quartznet
