### ISSUE TITLE
MisfireHandler breaks when there is a corrupt trigger record

### ISSUE THREAD

**Issue by harshavardhan-upendram** [quartz-scheduler/quartz#546]
When a trigger entry is corrupted, the MisfireHandler is breaking and is not handling other misfires. We are getting below exception when the trigger entry is present in QRTZ_TRIGGERS but is missing in QRTZ_CRON_TRIGGERS table.
`MisfireHandler: Error handling misfires: Couldn't retrieve trigger: No record found for selection of Trigger with key: 'DEFAULT.trigger-key' and statement: SELECT * FROM QRTZ_CRON_TRIGGERS WHERE SCHED_NAME = 'scheduler-name' AND TRIGGER_NAME = ? AND TRIGGER_GROUP = ?
`

This results in MisfireHandler not handling other misfires, till the DB entry is corrected for that one wrong trigger. MisfireHandler should handle other misfires in such cases.

**Comment by nductrung213** [comment]
I am facing the same problem. Do we have any updates?
