### ISSUE TITLE
Quartz cron job fire duplicate times in cluster mode

### ISSUE THREAD

**Issue by luoxiaoxun** [quartz-scheduler/quartz#548]
Quartz release version: 2.2.3 
I have four quartz scheduler instance(A/B/C/D)in cluster mode and set acquireTriggersWithinLock=true, but I find one of my cron job(trigger every minute)fire four times at a similar time as following: scheduler instance A with ip 10.152.33.54 fire at 2020-01-01 08:00:01 as normal which has pre and next fire time, but another three times are abnormal with no pre and next fire time,  scheduler instance B with ip 10.152.33.55 fire at 2020-01-01 08:01:02, scheduler instance C with ip 10.152.33.79 fire at 2020-01-01 08:01:29 and scheduler instance B with ip 10.152.33.55 fire at 2020-01-01 08:02:07 again.
![image](https://user-images.githubusercontent.com/4713954/71638690-d863d700-2ca1-11ea-80f4-262b58734d20.png)
![image](https://user-images.githubusercontent.com/4713954/71638703-2c6ebb80-2ca2-11ea-83df-afdd8f5007a3.png)
![image](https://user-images.githubusercontent.com/4713954/71638716-5b852d00-2ca2-11ea-9f54-739c7a887c7a.png)
![image](https://user-images.githubusercontent.com/4713954/71638729-aef77b00-2ca2-11ea-8bc2-104687828845.png)
![image](https://user-images.githubusercontent.com/4713954/71638733-dbab9280-2ca2-11ea-876a-0ef951b5117a.png)

**Comment by jimgovea** [comment]
I am not an expert, but I experienced in the past this kind of behavior when the clocks on the machines are not synchronized, are you sure that the clocks have a correct sync mechanism?

**Comment by cookietx** [comment]
I just started heavily using the scheduler with two AWS EC2 hosts in a cluster. I am seeing the same problem.  I had 2064 jobs scheduled for the same trigger time today and found 2081 triggerings across the two hosts.  That is 17 duplicates.

**Comment by tasier** [comment]
> I am not an expert, but I experienced in the past this kind of behavior when the clocks on the machines are not synchronized, are you sure that the clocks have a correct sync mechanism?

I experienced  such problem at same machine
![image](https://user-images.githubusercontent.com/8427332/76072265-9f621e80-5fd2-11ea-8262-68198d873b57.png)

**Comment by xiyelife** [comment]
I had the same problem.  And times on these hosts are always in sync

**Comment by lmr3796** [comment]
hitting this problem too

**Comment by alex-ha-github** [comment]
I got this problem too.
I am using WebLogic 12c and Oracle DB.
And the servers time are in sync.
Anyone find the solution?

**Comment by cookietx** [comment]
I searched and experimented for months.  Finally gave up and just running a single instance per environment.
