### ISSUE TITLE
qutz_trigger临时触发器问题

### ISSUE THREAD

**Issue by HEWU10** [quartz-scheduler/quartz#56]
@ljacomet @lorban 
版本：2.2.2
使用quartz2任务调度框架时，qutz_triggers表内生成了很多临时的，未知的触发器，Trigger_name命名以MT_开头。JOB_NAME都是notifyJobDetail，想知道这是什么问题？
![qq 20160919150136](https://cloud.githubusercontent.com/assets/13062383/18624402/05c35754-7e7a-11e6-827a-fcf80274603e.png)

**Comment by zemian** [comment]
What's this issue about? Can you post it in English?

**Comment by aukl** [comment]
@HEWU10 以上记录都是Scheduler#triggerJob被调用时, 随机产生的临时触发器. 

> All records you mentioned were generated by Scheduler#triggerJob, which will generate a random trigger key for ur job once invoked.

**Comment by HEWU10** [comment]
thank you .@aukl
