### ISSUE TITLE
Scheduler#rescheduleJob is not atomic

### ISSUE THREAD

**Issue by apixandru** [quartz-scheduler/quartz#57]
I'm running quartz on a cluster and I'm using spring to integrate with it.
There is a race condition going on when the cluster starts and it starts replacing the old stale jobs with the new ones.

One node will be initializing the scheduler and it will decide to replace the trigger (breakpoint org.quartz.impl.jdbcjobstore.SimpleTriggerPersistenceDelegate#deleteExtendedTriggerProperties )
Right after it executes this method, the trigger won't be in the database any longer so when another node in the cluster will try to read it (org.quartz.impl.jdbcjobstore.JobStoreSupport#retrieveTrigger) it will fail with the exception below. Because of this exception, the whole application will fail to start (not just the scheduler).
Caused by: org.quartz.JobPersistenceException: Couldn't retrieve trigger: No record found for selection of Trigger with key:

The logs can be found at https://github.com/apixandru/case-study/tree/master/spring-boot-quartz/logs (The exception can be found on the Server-1 node after the 4th restart)

For the whole project that demonstrates this issue go to https://github.com/apixandru/case-study/tree/master/spring-boot-quartz

To get the bug on any machine, start one server in debug mode and put a breakpoint on SimpleTriggerPersistenceDelegate.deleteExtendedTriggerProperties and just after it executes, start the second server and you will get this exception

The part of the spring code that causes this race condition just calls rescheduleJob, it can be found at 
https://github.com/spring-projects/spring-framework/blob/v4.3.3.RELEASE/spring-context-support/src/main/java/org/springframework/scheduling/quartz/SchedulerAccessor.java#L302

**Comment by zemian** [comment]
Hi @apixandru , the operations for Scheduler#rescheduleJob are executed within a lock block already, so what you describe should not occur. 

I have not look into your example yet, but if you can, please try to reproduce it with just plain Quartz test case without Spring. It will help us debug it quicker.

**Comment by apixandru** [comment]
Hi @zemian,

You are right, I just tried rewriting it in plain quartz and the scenario doesn't happen. It appears that somehow spring doesn't do this transactionally. 
If I breakpoint in JobStoreSupport at line 1498 with spring, the trigger is already gone in the database but when i do it in plain quartz, the row is replaced only after the commitConnection at line 3805.

Thanks for the help, I'll go update the spring guys

    package com.apixandru.casestudy;
    
    import org.quartz.JobDetail;
    import org.quartz.Scheduler;
    import org.quartz.SchedulerException;
    import org.quartz.Trigger;
    import org.quartz.impl.StdSchedulerFactory;
    import org.quartz.impl.jdbcjobstore.JobStoreTX;
    
    import java.util.Properties;
    
    import static java.util.Collections.singleton;
    import static org.quartz.JobBuilder.newJob;
    import static org.quartz.SimpleScheduleBuilder.simpleSchedule;
    import static org.quartz.TriggerBuilder.newTrigger;
    import static org.quartz.impl.StdSchedulerFactory.PROP_JOB_STORE_CLASS;
    
    public class QuartzTest {
    
        public static void main(String[] args) throws SchedulerException, InterruptedException {
    
            Properties props = new Properties();
            props.put("org.quartz.scheduler.instanceName", "QuartzTest Scheduler");
            props.put("org.quartz.scheduler.instanceId", "AUTO");
    
            props.put("org.quartz.jobStore.isClustered", "true");
            props.put("org.quartz.threadPool.threadCount", "2");
    
            props.put("org.quartz.dataSource.NAME.URL", "jdbc:oracle:thin:@localhost:49161:xe");
            props.put("org.quartz.dataSource.NAME.user", "system");
            props.put("org.quartz.dataSource.NAME.password", "oracle");
            props.put("org.quartz.dataSource.NAME.driver", "oracle.jdbc.OracleDriver");
            props.put("org.quartz.jobStore.dataSource", "NAME");
    
            props.put(PROP_JOB_STORE_CLASS, JobStoreTX.class.getName());
    
            Scheduler scheduler = new StdSchedulerFactory(props).getScheduler();
    
            scheduler.start();
    
            JobDetail job = newJob(HelloJob.class)
                    .withIdentity("QuartzTest Job")
                    .storeDurably()
                    .build();
    
            Trigger trigger = newTrigger()
                    .withIdentity("QuartzTest Trigger")
                    .startNow()
                    .withSchedule(simpleSchedule()
                            .withIntervalInSeconds(20)
                            .repeatForever())
                    .build();
    
            scheduler.addJob(job, true);
    
            // run this the first time to register the trigger
    //        scheduler.scheduleJob(job, singleton(trigger), true);
    
            // after the trigger was registered, run this instead
            scheduler.rescheduleJob(trigger.getKey(), trigger);
    
        }
    }

**Comment by apixandru** [comment]
I had a more detailed look and the problem appears to be that the spring's job store is a JobStoreCMT instance rather than a JobStoreTX but a transaction is not provided when executing the code that registers everything so the operations are not done in a transaction.

**Comment by zemian** [comment]
Yeah, please checkout Spring API doc carefully on how to properly set the DataSource if you choose to use Quartz through Spring. This is especially tricky if you are using an app server (eg WebLogic) with a XA DataSource. In that case you're suppose to also use an additional Spring's non-XA DataSource as well. See http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/scheduling/quartz/SchedulerFactoryBean.html on both setDataSource() and setNonTransactionalDataSource() methods docs.

**Comment by apixandru** [comment]
Thank you
