### ISSUE TITLE
Persisting a Job Result

### ISSUE THREAD

**Issue by khashish** [quartz-scheduler/quartz#575]
Hello,

Is there a way to be able to persist a job result while a job is currently executing. I noticed @PersistJobDataAfterExecution which persists data to the job data map after a job finishes execution. However in my case I am looking to be able to persist some job related data while the job is executing.

As an example if I am using a job to upload some file to AWS s3 and I want to persist the progress, where should I be persisting that progress if I am only able to persist after job execution.

Thanks.

**Comment by mar1u50** [comment]
Any solution to this?

**Comment by MaxwellDAssistek** [comment]
Classic case of stale bot killing a perfectly valid issue.

**Comment by funkrusher** [comment]
i'm also currently having a use-case where i need this, 
and am now looking for alternatives like JBerret, that have this use-case in mind.
Quartz would be better though.

Reinventing the wheel could mean to write an own Job-Queue Table, where each Job persists it's data during job-run so when the server crashes, the job can recover and continue processing where it left off. But it's a bit sad, to write this again for each use-case, while quartz already has a table where this could be persisted during job-run.

**Comment by khashish** [comment]
@funkrusher I had asked the same question on stackoverflow at that time. 

If I remember correctly the answer was exactly as you suggested (to write the data you need in your own table outside quartz)

https://stackoverflow.com/questions/61397363/persisting-quartz-job-result

**Comment by funkrusher** [comment]
@khashish thanks for the feedback.

i guess i will do it like this. 
It just would be pretty comfortable to use the existing jobData for it, and i also would not need to convince other developers in my team that quartz is still the better tool for this job against others (JBeret, Apache Camel, ...), even though i need to write a persistance mechanism for the job-processing myself.
