### ISSUE TITLE
Reactive support

### ISSUE THREAD

**Issue by ddcprg** [quartz-scheduler/quartz#591]
I'm trying to access the issue tracker and Google groups as per the official page but those don't seem to work for me so I'll raise my issue here.

I was wondering if anyone has discussed adding support at least for R2DBC or, even better, having the option to schedule jobs in a reactive manner? At the moment the only way to get both R2DBC and Quartz is defining 2 datasources which is not great. An option would be to implement a R2DBCJobStoreTX class that would bridge the integration with R2DBC.

Any thoughts on this?

**Comment by breun** [comment]
I think this is still relevant. As long as Quartz only supports JDBC (blocking I/O), reactive applications that use R2DBC (non-blocking I/O) for database access will need to add a JDBC-based datasource for Quartz.

**Comment by antoinechamot** [comment]
Any news ?

**Comment by koenpunt** [comment]
Still relevant in my opinion.

**Comment by ddcprg** [comment]
!stalebot reopen

**Comment by KatarzynaGniadzik** [comment]
This is still relevant - we need r2dbc support for quartz to use ReactiveTransactionManager in WebFlux - please reopen

**Comment by antoinechamot** [comment]
Why this was closed ? Of course it is still relevant if nothing was done

**Comment by mehatab** [comment]
Any update on this?

**Comment by krodyrobi** [comment]
Bumping on my side as well.
