### ISSUE TITLE
Cannot create tables in MySQL with InnoDB and UTF8mb4 using `tables_mysql.sql`

### ISSUE THREAD

**Issue by krrg** [quartz-scheduler/quartz#6]
InnoDB has a maximum size of 767 bytes on a single column index. When using a `VARCHAR(200)` as one of the columns in a multicolumn primary key, this limit still is in force.

When the character encoding is set to `UTF8mb4`, the `VARCHAR(200)` data type required 800 bytes, which is greater than the allowed 767 by InnoDB.

This should be easy to fix by reducing the `VARCHAR(200)` columns to `VARCHAR(190)` columns, which will fit inside the 767 byte limit with any encoding that uses 4 bytes or less.

For limitations on InnoDB, see http://dev.mysql.com/doc/refman/5.6/en/innodb-restrictions.html

**Comment by jhouserizer** [comment]
See #7

**Comment by zemian** [comment]
PR merged.
