### ISSUE TITLE
I often miss tasks at the same time. Does anyone have the same problem? How to solve it?

### ISSUE THREAD

**Issue by Imjiajiawang** [quartz-scheduler/quartz#602]
I often miss tasks executing at the same time. Does anyone have the same problem? How to solve it?

**Comment by Imjiajiawang** [comment]
I used quartz:2.3.2.I configured five tasks with cornTrigger(0 0/10 * * * ? *) .Sometimes a task is not executed.I do not know why.

**Comment by Imjiajiawang** [comment]
There are my configration:
# Default Properties file for use by StdSchedulerFactory
# to create a Quartz Scheduler Instance, if a different
# properties file is not explicitly specified.
#

org.quartz.scheduler.instanceName: DefaultQuartzScheduler
#自动配置scheduler实例id
org.quartz.scheduler.instanceId: AUTO
org.quartz.scheduler.rmi.export: false
org.quartz.scheduler.rmi.proxy: false
org.quartz.scheduler.wrapJobExecutionInUserTransaction: false

#单次扫描trigger的数量
org.quartz.scheduler.batchTriggerAcquisitionMaxCount=15
org.quartz.jobStore.acquireTriggersWithinLock: true

org.quartz.threadPool.class: org.quartz.simpl.SimpleThreadPool
org.quartz.threadPool.threadCount: 15
org.quartz.threadPool.threadPriority: 5
org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread: true

#任务错失时间
org.quartz.jobStore.misfireThreshold: 60000

#时间窗口调节参数
org.quartz.scheduler.batchTriggerAcquisitionFireAheadTimeWindow: 10000

//一个quartz实例的主线程完成一次操作过后的停顿时间，默认30秒，
//对于大量短时任务可以适当的减小该值，弊端是增加数据库的负担
org.quartz.scheduler.idleWaitTime=30000

#org.quartz.jobStore.class: org.quartz.simpl.RAMJobStore
org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
org.quartz.jobStore.driverDelegateClass = org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
org.quartz.jobStore.tablePrefix = QRTZ_

# 是否集群、负载均衡、容错，如果应用在集群中设置为false会出错
org.quartz.jobStore.isClustered: true

# 检入到数据库中的频率(毫秒)。检查是否其他的实例到了应当检入的时候未检入这能指出一个失败的实例，且当前Scheduler会以此来接管执行失败并可恢复的Job通过检入操作，Scheduler也会更新自身的状态记录
org.quartz.jobStore.clusterCheckinInterval: 20000

#不检查quartz版本更新
org.terracotta.quartz.skipUpdateCheck=true

**Comment by Technoboy-** [comment]
any logs ?

**Comment by Imjiajiawang** [comment]
> any logs ?

There no any error logs,and i found it lost by scheduler with named NON_CLUSTERED.
![image](https://user-images.githubusercontent.com/21121295/87003922-21678b80-c1ef-11ea-8014-347fbbe8d329.png)

**Comment by samuelTharma** [comment]
I used 1.6.5, three jobs were sheduled and running every 10 seconds without any problem, in the long run sometimes one job is stopped running without any logs silently?

**Comment by 350478992** [comment]
I have the same problem,
