### ISSUE TITLE
Quartz in Android

### ISSUE THREAD

**Issue by hewitta** [quartz-scheduler/quartz#607]
StdSchedulerFactory in Quartz requires some classes from java.beans that aren't included in Android. [There is a jar file available from Google](https://code.google.com/archive/p/openbeans/) to add the classes, but the import path to the classes needs to be changed in the Quartz files which are read-only. Any help in resolving this would be appreciated.

![screenshot](https://user-images.githubusercontent.com/64169310/87214918-f53b3000-c2fe-11ea-89b5-8cab8667d146.jpg)

**Comment by mikedawson** [comment]
Although this is an old issue, as it turned up in a search for me, I'll post an answer. 

Even if you get Quartz to compile on Android, it probably won't do what you want. Android will destroy applications shortly after the user leaves them (whether or not they were explicitly closed). Quartz can't execute anything if it's not running.

If you want to execute tasks on a schedule on Android reliably, you need to use Android's APIs to do so (such that your task will execute at the desired time). JetPack WorkManager is the way to do that: [https://developer.android.com/topic/libraries/architecture/workmanager](https://developer.android.com/topic/libraries/architecture/workmanager)
