### ISSUE TITLE
Add Support for functional Interface

### ISSUE THREAD

**Issue by Presto412** [quartz-scheduler/quartz#608]
When I try to create a job without having an explicit class defined, it fails and isn't able to find the class. Sample code: 

```
       return JobBuilder
                .newJob(((Job) context -> {
                    log.debug("No class yay");
                }).getClass())
                .withIdentity("SampleJob1")
                .withDescription("SampleJob1")
                .storeDurably()
                .build();
```

I get the following error:
`org.quartz.JobPersistenceException: Couldn't retrieve job because a required class was not found: com.example.common.cron.JobConfig$$Lambda$183/1691426065 [See nested exception: java.lang.ClassNotFoundException: com.example.common.cron.JobConfig$$Lambda$183/1691426065]
`

**Comment by dowonderatwill** [comment]
Job is an interface so needs to implement execute method. May be that could be the reason.

**Comment by Presto412** [comment]
Yes but the lambda function takes care of that. I think it's more to do with a dynamic class generated rather than a precomputed   class.

**Comment by vamsikurre** [comment]
Lambda expressions create abstract classes which are dynamically built at runtime using InvokeDynamic. 

A good read
https://www.infoq.com/articles/Java-8-Lambdas-A-Peek-Under-the-Hood/
