### ISSUE TITLE
Day-of-Week Indexing is incompatible with ISO/IEC/IEEE 9945 Posix spec and all other schedulers

### ISSUE THREAD

**Issue by justjanne** [quartz-scheduler/quartz#609]
# Expected

0 or 7 is the day-of-week ordinal for sunday, with 1-6 representing monday through saturday

# Actual

Sunday is represented by an ordinal value of 1, 2-6 represent monday through saturday

# Background

The ISO/IEC/IEEE 9945 Posix spec specifies day-of-week ordinals for cron expressions as follows:

> 5. Day of the week ([0,6] with 0=Sunday)

dcron also follows this definition<sup>[\[1\]](https://github.com/dubiousjim/dcron/blob/1ba33c3325df48de46263276a43ed76cf9d81518/defs.h#L156)</sup>

The currently implemented version by cronie<sup>[\[2\]](https://github.com/dubiousjim/dcron/blob/1ba33c3325df48de46263276a43ed76cf9d81518/defs.h#L156)</sup> and vixie cron<sup>[\[3\]](https://github.com/freebsd/freebsd/blob/bbbbd9c36164fd299abb5411918bbe8e3a33ac61/usr.sbin/cron/cron/cron.h#L146)</sup>, the most common cron implementations, is as follows:

> /* note on DOW: 0 and 7 are both Sunday, for compatibility reasons. */

This has been the standard for over 26 years, as vixie cron introduced this ordinal indexing in 1994<sup>[\[4\]]()</sup>.

# Problem Description

Quartz is the only scheduler trying to be somewhat similar to cron that doesn’t implement this in a way that is compatible with the POSIX spec, or compatible with older schedulers.

Quartz has had this issue at least since 2012<sup>[\[5\]](https://github.com/quartz-scheduler/quartz/blame/f3e15e4a5117700797f77b313737d67e8a0e0492/quartz-core/src/main/java/org/quartz/CronExpression.java#L231)</sup>, so enough projects may have already started depending on this bug in Quartz, but it should clearly be fixed.

# Recommendation

1. Fix the ordinals to match the usual POSIX spec, with 0 and 7 being sunday, 1-6 being mon-sat
2. Add an optional flag to the CronTrigger and CronExpression constructor to allow using the old, broken 1-7 indexing with 1 being sunday

---

### Footnotes

[1. dcron day-of-week definition](https://github.com/dubiousjim/dcron/blob/1ba33c3325df48de46263276a43ed76cf9d81518/defs.h#L156)
[2. cronie day-of-week definition](https://github.com/cronie-crond/cronie/blob/584911514ce6aa2f16e1d79431bac816ea62cb2c/src/macros.h#L128)
[3. vixie cron day-of-week definition](https://github.com/freebsd/freebsd/blob/bbbbd9c36164fd299abb5411918bbe8e3a33ac61/usr.sbin/cron/cron/cron.h#L146)
[4. vixie cron commit introducing 0-7 support](https://github.com/freebsd/freebsd/commit/54a3fb733766ec35c7a9f85aab18eceac14b4eab#diff-0491ac6bd1189ca505a05cebe135df30)
[5. quartz commit introducing broken day-of-week definition](https://github.com/quartz-scheduler/quartz/blame/f3e15e4a5117700797f77b313737d67e8a0e0492/quartz-core/src/main/java/org/quartz/CronExpression.java#L231)

**Comment by justjanne** [comment]
So apparently, compatibility with the cron spec is now WONTFIX?

**Comment by dguder** [comment]
> Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?
I second @justjanne,
It seems that compatibility to ISO/IEC standards is not as important as something else.
