### ISSUE TITLE
Not using index while trying to fetch next trigger to execute with Postgres.

### ISSUE THREAD

**Issue by rahulreddyr3** [quartz-scheduler/quartz#612]
**Problem Statement:**
Quartz is not using index available on `qrtz_triggers` while fetching next trigger to execute. Instead doing a sequential scan on the entire table. This is taking long (~2 sec) when there are around ~2.5M records in the table. This is causing lot of job to be misfired.

**Log from Postgres**
Slow logs from Postgres:
```
Query Text: SELECT TRIGGER_NAME, TRIGGER_GROUP, NEXT_FIRE_TIME, PRIORITY FROM QRTZ_TRIGGERS WHERE SCHED_NAME = 'Scheduler' AND TRIGGER_STATE = $1 AND NEXT_FIRE_TIME <= $2 AND (MISFIRE_INSTR = -1 OR (MISFIRE_INSTR != -1 AND NEXT_FIRE_TIME >= $3)) ORDER BY NEXT_FIRE_TIME ASC, PRIORITY DESC
	Gather Merge  (cost=521557.74..551344.36 rows=255296 width=88) (actual time=1692.754..1692.760 rows=25 loops=1)
	  Output: trigger_name, trigger_group, next_fire_time, priority
	  Workers Planned: 2
	  Workers Launched: 0
	  ->  Sort  (cost=520557.72..520876.84 rows=127648 width=88) (actual time=1692.752..1692.754 rows=25 loops=1)
	        Output: trigger_name, trigger_group, next_fire_time, priority
	        Sort Key: qrtz_triggers.next_fire_time, qrtz_triggers.priority DESC
	        Sort Method: external sort  Disk: 7432kB
	        ->  Parallel Seq Scan on public.qrtz_triggers  (cost=0.00..497510.01 rows=127648 width=88) (actual time=1567.453..1651.449 rows=64368 loops=1)
	              Output: trigger_name, trigger_group, next_fire_time, priority
	              Filter: (((qrtz_triggers.sched_name)::text = 'Scheduler'::text) AND ((qrtz_triggers.trigger_state)::text = 'WAITING'::text) AND ((qrtz_triggers.next_fire_time)::numeric <= '1595503996000'::numeric) AND ((qrtz_triggers.misfire_instr = '-1'::integer) OR ((qrtz_triggers.misfire_instr <> '-1'::integer) AND ((qrtz_triggers.next_fire_time)::numeric >= '1595204009000'::numeric))))
	              Rows Removed by Filter: 2694520
```

**Expected**
Ideally the query for next fire time should use the `idx_qrtz_t_next_fire_time` index present on the table.

**How to reproduce:**
Create the database as per the [suggested migrations](https://github.com/quartz-scheduler/quartz/blob/master/quartz-core/src/main/resources/org/quartz/impl/jdbcjobstore/tables_postgres.sql)
Enable slow logs on Postgres with explain analyse on using [this](https://www.postgresql.org/docs/9.2/auto-explain.html). This should start logging the query plan of every query.
Then we should be able to see the above log of sequential scan instead of using index. Even when the table is quite large (2.5M records).

**Cause**
The [selectTriggerToAcquire](https://github.com/quartz-scheduler/quartz/blob/caacb552d34174becf487a1f0ddf4b93d5846ab1/quartz-core/src/main/java/org/quartz/impl/jdbcjobstore/StdJDBCDelegate.java#L2593) method is using `setBigDecimal`. According to the documentation of `setBigDecimal` sends the query to Postgres with datatype of `next_fire_time` as `numeric`.
```
Sets the designated parameter to the given <code>java.math.BigDecimal</code> value.
The driver converts this to an SQL <code>NUMERIC</code> value when
it sends it to the database.
```
But according to the suggested migration the `next_fire_time` is of type `bigint` in db. This is causing Postgres to skip using index. More details on this can be found [here](https://dba.stackexchange.com/questions/146294/why-does-postgresql-perform-a-seq-scan-when-comparing-a-numeric-value-with-a-big)
If we do the following change in [here](https://github.com/quartz-scheduler/quartz/blob/caacb552d34174becf487a1f0ddf4b93d5846ab1/quartz-core/src/main/java/org/quartz/impl/jdbcjobstore/StdJDBCDelegate.java#L2611)
```
ps.setBigDecimal(2, new BigDecimal(String.valueOf(noLaterThan)));
ps.setBigDecimal(3, new BigDecimal(String.valueOf(noEarlierThan)));
```
to 
```
ps.setLong(2, noLaterThan);
ps.setLong(3, noEarlierThan);
```
The query starts using Index. Log from Postgres after changes:
```
Query Text: SELECT TRIGGER_NAME, TRIGGER_GROUP, NEXT_FIRE_TIME, PRIORITY FROM QRTZ_TRIGGERS WHERE SCHED_NAME = 'Scheduler' AND TRIGGER_STATE = $1 AND NEXT_FIRE_TIME <= $2 AND (MISFIRE_INSTR = -1 OR (MISFIRE_INSTR != -1 AND NEXT_FIRE_TIME >= $3)) ORDER BY NEXT_FIRE_TIME ASC, PRIORITY DESC
	Sort  (cost=131366.44..131538.06 rows=68647 width=88) (actual time=101.373..101.375 rows=25 loops=1)
	  Output: trigger_name, trigger_group, next_fire_time, priority
	  Sort Key: qrtz_triggers.next_fire_time, qrtz_triggers.priority DESC
	  Sort Method: external sort  Disk: 7432kB
	  ->  Index Scan using idx_qrtz_t_next_fire_time on public.qrtz_triggers  (cost=0.56..122565.21 rows=68647 width=88) (actual time=2.446..61.542 rows=64368 loops=1)
	        Output: trigger_name, trigger_group, next_fire_time, priority
	        Index Cond: (((qrtz_triggers.sched_name)::text = 'Scheduler'::text) AND (qrtz_triggers.next_fire_time <= '1595503996000'::bigint))
	        Filter: (((qrtz_triggers.trigger_state)::text = 'WAITING'::text) AND ((qrtz_triggers.misfire_instr = '-1'::integer) OR ((qrtz_triggers.misfire_instr <> '-1'::integer) AND (qrtz_triggers.next_fire_time >= '1595204009000'::bigint))))
```

Let us know if anything is missing. Else we can raise the PR for same.

**Comment by oliversaggau** [comment]
We encountered the same problem. But instead of forking and building our own Quartz we just added specific indices for numeric to our database:
```
CREATE INDEX IDX_QRTZ_T_NEXT_FIRE_TIME2
  ON QRTZ_TRIGGERS (SCHED_NAME, CAST(NEXT_FIRE_TIME AS NUMERIC));
CREATE INDEX IDX_QRTZ_T_NFT_ST2
  ON QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_STATE, CAST(NEXT_FIRE_TIME AS NUMERIC));
CREATE INDEX IDX_QRTZ_T_NFT_MISFIRE2
  ON QRTZ_TRIGGERS (SCHED_NAME, MISFIRE_INSTR, CAST(NEXT_FIRE_TIME AS NUMERIC));
CREATE INDEX IDX_QRTZ_T_NFT_ST_MISFIRE2
  ON QRTZ_TRIGGERS (SCHED_NAME, MISFIRE_INSTR, CAST(NEXT_FIRE_TIME AS NUMERIC), TRIGGER_STATE);
CREATE INDEX IDX_QRTZ_T_NFT_ST_MISFIRE_GRP2
  ON QRTZ_TRIGGERS (SCHED_NAME, MISFIRE_INSTR, CAST(NEXT_FIRE_TIME AS NUMERIC), TRIGGER_GROUP, TRIGGER_STATE);
  ```

**Comment by oliversaggau** [comment]
The issue is still relevant. On `master` the `selectTriggerToAcquire` method still uses `PreparedStatement#setBigDecimal` which the JDBC driver will then translate to `NUMERIC` but the index on `master` is not suitable for `NUMERIC` i.e. the `selectTriggerToAcquire` doesn't use any index for it's queries.
