### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by lcoller** [quartz-scheduler/quartz#622]
Is anyone still maintaining this?  There hasn't been an update to the repository since Oct 2019, none of the issues filed since then have been closed (other than by the filer of the issue).  The download page on the http://www.quartz-scheduler.org/ site shows 2.3.0 as the latest stable release despite 2.3.2 having been released here on github.  Lots of open pull requests as well.

**Comment by ahmed-adly-khalil** [comment]
follow

**Comment by zemian** [comment]
Hi, I used to able to put in some free time on this project, but have been busy lately. I still tried to answer questions on the mailing list forum once in a while though. If any of you are up for contributing, please do contact @jhouserizer and his team at Terracotta/SoftwareAG.
