### ISSUE TITLE
Missing dbTables in latest distributions

### ISSUE THREAD

**Issue by squalou** [quartz-scheduler/quartz#623]
docs/dbTables does not exist anymore on latest distributions,
last seen on 2.2.3

How are we supposed to implement jdbc job store ?

By the way : Main website does not even make it possible to download 2.3.2 (actually the latest at the time of writing), the 'latest' points to a 2.3.0-SNAPSHOT archive, which is really weird.

thx

regards

**Comment by squalou** [comment]
duplicate of #576 sorry

but still .... is there activity on this project ?

**Comment by EduFrazao** [comment]
@squalou I'm also in doubt. So many opened bugs or questions, withou any activity. More than one year without a release. There is other users asking if the project is still mantained, but with no answer...
