### ISSUE TITLE
k8s, org.quartz.JobPersistenceException: Couldn't retrieve job because a required class was not found

### ISSUE THREAD

**Issue by peeeto** [quartz-scheduler/quartz#638]
Hi, we are using quartz scheduler with spring-boot on kubernetes.
What we observe, is, that adding new job to cluster is not compatible with kubernetes zero downtime rolling upgrade.

There is old instance with lower version (without job class) running parallel to new instance with higher version (with job class) for certain amount of time (until readiness check of new instance is successful).
Old instance marks the trigger to ERROR because ClassNotFoundException and the Job will never run again - although new instaces could schedule the Job without problem.

**Is there way to workaround the behavior of setting the trigger to ERROR state on ClassNotFoundException?**
Thanks.

Oct 19, 2020 @ 11:40:37.275org.quartz.JobPersistenceException: Couldn't retrieve job because a required class was not found: com.mycompany.MyJob
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveJob(JobStoreSupport.java:1393)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2864)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2805)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2803)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3864)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTriggers(JobStoreSupport.java:2802)
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:287)
Caused by: java.lang.ClassNotFoundException: com.mycompany.MyJob
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:284)
	at org.springframework.scheduling.quartz.ResourceLoaderClassLoadHelper.loadClass(ResourceLoaderClassLoadHelper.java:81)
	at org.springframework.scheduling.quartz.ResourceLoaderClassLoadHelper.loadClass(ResourceLoaderClassLoadHelper.java:87)
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectJobDetail(StdJDBCDelegate.java:852)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveJob(JobStoreSupport.java:1390)
	... 6 common frames omitted

Stack Detail:
`#docker image with: adoptopenjdk/openjdk11:jre-11.0.7_10-alpine`

`#postgresql 9.6`

```
#pom.xml
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot</artifactId>
        <version>2.3.4.RELEASE</version>
      </dependency>

      <dependency>
        <groupId>org.quartz-scheduler</groupId>
        <artifactId>quartz</artifactId>
        <version>2.3.2</version>
        <exclusions>
          <exclusion>
            <artifactId>slf4j-api</artifactId>
            <groupId>org.slf4j</groupId>
          </exclusion>
        </exclusions>
      </dependency>
      <dependency>
        <groupId>org.quartz-scheduler</groupId>
        <artifactId>quartz-jobs</artifactId>
        <version>2.3.2</version>
      </dependency>
```
```

#quartz.properties
org.quartz.jobStore.useProperties=true
org.quartz.jobStore.tablePrefix=QRTZ_
org.quartz.jobStore.isClustered=true
org.quartz.jobStore.clusterCheckinInterval=20000
org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
org.quartz.scheduler.instanceId=AUTO
org.quartz.threadPool.class=org.quartz.simpl.SimpleThreadPool
org.quartz.threadPool.threadCount=20
org.quartz.threadPool.threadPriority=5
org.quartz.threadPool.makeThreadsDaemons=false
org.quartz.scheduler.jmx.export=false
org.quartz.scheduler.rmi.export=false
org.quartz.scheduler.rmi.proxy=false
org.quartz.plugin.shutdownHook.class=org.quartz.plugins.management.ShutdownHookPlugin
org.quartz.plugin.shutdownHook.cleanShutdown=false
org.quartz.jobStore.dontSetAutoCommitFalse=false
org.quartz.scheduler.skipUpdateCheck=true
```

```
# qrtz_triggers
INSERT INTO public.qrtz_triggers (sched_name, trigger_name, trigger_group, job_name, job_group, description, next_fire_time, prev_fire_time, priority, trigger_state, trigger_type, start_time, end_time, calendar_name, misfire_instr, job_data) VALUES 
('ClusteredScheduler', 'MyJob_everyMinute', 'DEFAULT', 'MyJob', 'DEFAULT', null, 1605084480000, 1605084420000, 0, 'ERROR', 'CRON', 1605084325000, 0, null, 0, '');
```

**Comment by peeeto** [comment]
I implemented workaround using custom class loader helper:
`@Slf4j
public class ClassNotFoundIgnoringClassLoadHelper extends org.quartz.simpl.CascadingClassLoadHelper {

    @Override
    public Class<?> loadClass(String name) {
        try {
            return super.loadClass(name);
        } catch (ClassNotFoundException e) {
            Class<Job> clz = Job.class;
            return clz;
        }
    }
}`

`#quartz.properties
org.quartz.scheduler.classLoadHelper.class=com.mycompany.ClassNotFoundIgnoringHelper`

**Comment by yangwliu** [comment]
> I implemented workaround using custom class loader helper:
> 
> ```
> 
> public class ClassNotFoundIgnoringClassLoadHelper extends org.quartz.simpl.CascadingClassLoadHelper {
> 
>     @Override
>     public Class<?> loadClass(String name) {
>         try {
>             return super.loadClass(name);
>         } catch (ClassNotFoundException e) {
>             Class<Job> clz = Job.class;
>             return clz;
>         }
>     }
> }
> ```
> 
> `#quartz.properties org.quartz.scheduler.classLoadHelper.class=com.mycompany.ClassNotFoundIgnoringHelper`

However, i tried it, but the trigger still was set to ERROR, when the older one try to initial job.

**Comment by yangwliu** [comment]
@peeeto Sorry for the last reply. Your solution works well. Actually if you are integrating quartz with SpringBoot, if you custom the ClassLoadHelper to extends the CascadingClassLoadHelper, sometimes it will throw some exception when instance the Job. It will work to custom your own ClassLoaderHelper to extents the ResourceLoaderClassLoadHelper.

**Comment by elue** [comment]
Hi,
This issue is still relevant because it happens to every containerized environment.

**Comment by pablomoreno61** [comment]
I'm facing the same issue. is there a fix for this?
