### ISSUE TITLE
[FR] Add the ability to switch Scheduler in Clustered Environment

### ISSUE THREAD

**Issue by lashakv** [quartz-scheduler/quartz#639]
Hi Everyone,

I would like to issue a feature-request or let me know if it is possible to have with Quartz 2.3.0+ version.

Quartz Scheduler has a Clustered environment mode, which has multiple purposes (e.g. fail-over mechanism, load balancing of all jobs between instances etc.)

At this time, bunch of companies have continues deploys without any downtime, for instance, blue/green deployment. In a nutshell, companies have 2 instances live and standby. At some point, when standby is ready to be exposed operations switch all the traffic from live node to standby one. Both live/standby replicas use the same DB instance.

In case of the service that uses Quartz Scheduler, there are 2 instances that work against the same DB and only one of them actually triggers all the jobs.

The feature request is: As a Dev, I would like to have an API that will allow me to control which scheduler has obtained the lock and is active. Probably, having an api that will stop current scheduler for the other one to obtain the lock.

**Comment by xmoravej** [comment]
Would not simply pausing one of the schedulers work for you? The pause operation can be invoked through various means - Quartz api (local or remote through rmi or jmx), gui, web service.
-------- Original message --------From: "Lasha K." <notifications@github.com> Date: 11/12/20  14:22  (GMT+01:00) To: quartz-scheduler/quartz <quartz@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [quartz-scheduler/quartz] [FR] Add the ability to switch Scheduler in
  Clustered Environment (#639) 
Hi Everyone,
I would like to issue a feature-request or let me know if it is possible to have with Quartz 2.3.0+ version.
Quartz Scheduler has a Clustered environment mode, which has multiple purposes (e.g. fail-over mechanism, load balancing of all jobs between instances etc.)
At this time, bunch of companies have continues deploys without any downtime, for instance, blue/green deployment. In a nutshell, companies have 2 instances live and standby. At some point, when standby is ready to be exposed operations switch all the traffic from live node to standby one. Both live/standby replicas use the same DB instance.
In case of the service that uses Quartz Scheduler, there are 2 instances that work against the same DB and only one of them actually triggers all the jobs.
The feature request is: As a Dev, I would like to have an API that will allow me to control which scheduler has obtained the lock and is active. Probably, having an api that will stop current scheduler for the other one to obtain the lock.

**Comment by lashakv** [comment]
Thank you @xmoravej I'll definitely double check that, but my understanding was that pausing or standby for scheduler does not release the db lock and quartz will not let another scheduler to process the triggers.

**Comment by xmoravej** [comment]
When a scheduler is paused, it finishes executing whatever jobs it is currently executing and is no longer participating in the “db lock race” to acquire new locks to execute triggers.

**Comment by lashakv** [comment]
thank you @xmoravej . I tested it and the solution is as simple as you described. Just monitoring what's the active environment and pausing/starting the scheduler, which should do the job.
