### ISSUE TITLE
Drop dependency on C3p0 and Hikari

### ISSUE THREAD

**Issue by Dragas** [quartz-scheduler/quartz#649]
While quartz does work with databases via jobstores, I do not believe quartz should have a dependency on connection pool managers, and instead leave it up to the application that uses quartz to provide the `DataSource` instance. The said datasource often is already provided by the application used connection pooling solution. This prevents unnecessary dependencies in `module-info.java` file,  if you will ever decide to define one.

**Comment by apflieger** [comment]
Definitly
Related https://github.com/quartz-scheduler/quartz/issues/650

**Comment by Dragas** [comment]
I too enjoy bots taking care of issues in abandoned projects.
