### ISSUE TITLE
Provide a way to inject dependency to custom connection provider

### ISSUE THREAD

**Issue by vivekkothari** [quartz-scheduler/quartz#650]
I have a custom connection provider which looks like,

```
public class HikariConnectionProvider implements ConnectionProvider {

  private DataSource dataSource;

  @Override
  public Connection getConnection() throws SQLException {
    return dataSource.getConnection();
  }

  @Override
  public void shutdown() throws SQLException {
  }

  @Override
  public void initialize() throws SQLException {
  }

  public void setDataSource(DataSource dataSource) {
    this.dataSource = dataSource;
  }
}
```

I need the ability to provide my datasource directly to this class which it is invoked reflectivity.

The reason I am not using `org.quartz.utils.HikariCpPoolingConnectionProvider` is because my application uses a `yml` file to define all the config params and the problem of hiding sensitive stuff like passwords is solved for the yml parser.

If Quartz can be instantiated using a yml file, nothing like it.

**Comment by apflieger** [comment]
I have almost the same need. I just want to pass a DataSource object to the SchedulerFactory somehow.

**Comment by maxqch** [comment]
+1. This would be very nice to have.

We got around this limitation in the following (pretty hacky) way. Something like this:

`
public class MyConnectionProvider implements ConnectionProvider {
  static Map<String, Datasource> ds;
  private String dsId;

  public static void register(final String id, final DataSource ds) {
     ds.put(id, ds);
  }

  @Override public Connection getConnection() {
    return ds.get(dsId).getConnection();
  }
  public void setDsId(String dsId) {
    this.dsId = dsId;
  }
}
`
And during DI, we call register and also set the id on the quartz connection provider property

`org.quartz.dataSource.NAME.dsId = ...`
