### ISSUE TITLE
Is this project still alive？

### ISSUE THREAD

**Issue by zhaowenxishi** [quartz-scheduler/quartz#663]
Is this project currently being maintained? Is it temporarily not maintained, or no one will maintain it in the future?

**Comment by jhouserizer** [comment]
Unfortunately not really, though working on a solution for that.

**Comment by shaundsmith** [comment]
Hi @jhouserizer. roughly how long will it be before maintenance resumes? Will it be short term, or longer term?

**Comment by bmertens911** [comment]
I switched to [JobRunr](https://github.com/jobrunr/jobrunr) and could not be happier... It even has a built-in dashboard which I just love!

**Comment by jhouserizer** [comment]
JobRunr is cool, but isn't an equivalent of Quartz (neither are equally good depending upon the use case).

The good news is, some plans are in the works to revitalize the maintenance of the project.

**Comment by zhaowenxishi** [comment]
> JobRunr is cool, but isn't an equivalent of Quartz (neither are equally good depending upon the use case).
> 
> The good news is, some plans are in the works to revitalize the maintenance of the project.

When will it be?
