### ISSUE TITLE
Quartz+ Spring Boot + SQLite configuration

### ISSUE THREAD

**Issue by RamanShyrski** [quartz-scheduler/quartz#690]
I'm trying to configure these three to work, but on startup quartz scheduler bean instantiation fails with sql error. The issue is that to obtain lock for QRTZ_LOCK table quartz is running SELECT * FROM QRTZ_LOCKS WHERE SCHED_NAME = 'quartzScheduler' AND LOCK_NAME = ? FOR UPDATE query. But sqlite does not support locks and throws SQLException

Is there any way to make it work?

**Comment by SpaceMiao** [comment]
@RamanShyrski Hello, i'm facing this issue now. Did you fixed it already? please share solution~ many thanks.
