### ISSUE TITLE
Couldn't acquire next trigger: Deadlock found when trying to get lock

### ISSUE THREAD

**Issue by jaymedidata** [quartz-scheduler/quartz#692]
We are getting Deadlocks periodically, Quartz jobs hangs and stop updating NEXT_FIRE_TIME when it happens.

Quartz version: 2.3.2
MySQL version: '5.7.28'

This issue is very similar to what this article described: [Quartz-scheduler causes InnoDB deadlock](https://www.programmersought.com/article/13861594803/), the solution is to disable gap-locking use innodb_locks_unsafe_for_binlog=1, but as of MySQL 5.6.3, innodb_locks_unsafe_for_binlog is deprecated.

Error: 
`{"timestamp":"2021-07-02T01:34:42.193Z","message":"An error occurred while scanning for the next triggers to fire.","component":"rcm-api","component_version":"2020.4.2","machine":"ip-10-224-91-182","data":{},"exception":"org.quartz.JobPersistenceException: Couldn\u0027t acquire next trigger: Deadlock found when trying to get lock; try restarting transaction [See nested exception: com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction]","stack":["org.quartz.JobPersistenceException: Couldn\u0027t acquire next trigger: Deadlock found when trying to get lock; try restarting transaction [See nested exception: com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction]","    at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2923)","    at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2805)","    at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2803)","    at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3864)","    at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTriggers(JobStoreSupport.java:2802)","    at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:287)","Caused by: com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction","    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:123)","    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)","    at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)","    at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)","    at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)","    at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)","    at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)","    at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)","    at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)","    at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)","    at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.updateTriggerStateFromOtherState(StdJDBCDelegate.java:1439)","    at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2901)","    ... 5 more"],"level":"ERROR"}`

**Comment by nsaravanas** [comment]
Please see https://github.com/quartz-scheduler/quartz/issues/693

Could be possible with the indexes created, create a proper index in the correct order would fix the issue.

**Comment by chclaus** [comment]
I could also mention my answer on #693 ;)
