### ISSUE TITLE
Deadlock in TRIGGERS cluster mode

### ISSUE THREAD

**Issue by nsaravanas** [quartz-scheduler/quartz#693]
We've the quartz scheduler running production in cluster mode and noticed the row level lock acquired on TRIGGERS table is causing deadlock.

**Setup**

- DB2v10.1
- Java8
- Quartz 2.3.2

**Config**

- cluster mode - on
- worker threads - 15
- instances - 2

**DDL**

- https://github.com/quartz-scheduler/quartz/blob/master/quartz-core/src/main/resources/org/quartz/impl/jdbcjobstore/tables_db2_v95.sql

**Issue**

The below exception occurs after spawning multiple instances or sometimes on single instance with multiple worker threads.

method **JobStoreSupport.triggeredJobComplete** - line no **3188**

`DB2 SQL error: SQLCODE: -911, SQLSTATE: 40001, SQLERRMC: 2`

**Analysis**

The issue is due to the incorrect index created on the TRIGGER table, when updating status of a trigger in triggers table, the whole table is scanned, when another thread has acquired a lock on a particular row.

**Fix**

Create index on JOB_GROUP, TRIGGER_STATE, JOB_NAME, SCHED_NAME

After creating the index, tried with 10 instances with 15 threads each, didn't observe the issue.

**Comment by chclaus** [comment]
I noticed that index creation is unfortunately not included in the DB schema. However, the indices are described in the Liquibase file. I think there is something wrong here, because the `CREATE INDEX` statements should imho also be present in the DBMS specific SQL scripts. Potentially a very important fix.

**Comment by nsaravanas** [comment]
Thank you, will raise a PR with proper indices

**Comment by nsaravanas** [comment]
The PR has been raised https://github.com/quartz-scheduler/quartz/pull/722

**Comment by nsaravanas** [comment]
@chclaus  can you review the PR?
