### ISSUE TITLE
Invalid cron expression with v2.3.x

### ISSUE THREAD

**Issue by saintcoder** [quartz-scheduler/quartz#729]
Cron expression `0 0 10 1/80 * ? *` which was working with v2.2.3 fails with v2.3.x. Quick check reveals v.2.3.x have more validations added to cron expression.

https://crontab.cronhub.io validates the expression "At 10.00 AM, every 80 days".

**Comment by realflash7** [comment]
This change actually breaks the existing schedules.  

Following cron expressions are failing with 2.3.x versions - 
0/120 * * ? *
0 0 1/24 ? * 1,2,3,4,5,6,7
0 0 1/24 ? * 5,3
0 0 0/24 ? * 1,2,3,4,5,6,7
0 0 5/24 ? * 1,2,3,4,5,6,7
0 0/60 11-23 ? * 1,2,3,4,5,6,7
0 45 11/24 ? * 3,1,2,4,5,6,7

Is there a way to bypass the new validations in 2.3.2+ versions?
Thanks.

**Comment by amit-r** [comment]
Minor version upgrade v2.3.x isn't backwards compatible with v2.2.3, and it's breaking cron expression posted by @realflash7 for all our users. Could backwards compatibility be reinstated?
