### ISSUE TITLE
org.quartz.impl.jdbcjobstore.JobStoreSupport.MisfireHandler is still running when schedule in standby mode

### ISSUE THREAD

**Issue by wuhongzhi** [quartz-scheduler/quartz#735]
In my case, I start the scheduler, both org.quartz.core.QuartzSchedulerThread and org.quartz.impl.jdbcjobstore.JobStoreSupport.MisfireHandler  run, then truns the scheduler to standby, QuartzSchedulerThread  goes into a loop (check paused && !halted.get()), but MisfireHandler still works (as there is no such loop checking), 

It's also should be in standby as the scheduler does?

**Comment by linsage** [comment]
I got the same problem recently.
the version of quartz is 2.3.2
