### ISSUE TITLE
May be add spring boot support, is therer any schedule?

### ISSUE THREAD

**Issue by zhxxcq** [quartz-scheduler/quartz#75]
Like titile.

**Comment by zemian** [comment]
Spring already has quartz support. You should see their documentation on usage.

**Comment by vpavic** [comment]
@zhxxcq I you're interested in first-class Quartz Scheduler support in Spring Boot vote for this PR: spring-projects/spring-boot#4299

**Comment by zhxxcq** [comment]
thanks very much!
