### ISSUE TITLE
isTriggerLockExpired(Document document) function in ExpiryCalculator class is not working for multiple instances with multiple region of project

### ISSUE THREAD

**Issue by ashwin4glory** [quartz-scheduler/quartz#757]
We used below quartz dependency in our spring boot application:
      <dependency>
                <groupId>com.novemberain</groupId>
                <artifactId>quartz-mongodb</artifactId>
                <version>2.2.0-rc2</version>
       </dependency>
 
1. Our application runs in four instances of which two belong to one region and the other two belong to different region.
2. When the trigger lock is getting created by the instance of region-1 and the  another instance which belongs to region-2 is trying to create the trigger lock for the same job then we are seeing the lock of region-1 is getting expired within 20-25 seconds(ideally it should expire after 10 minutes) and it is trying to relock, for which misfire of job is happening and the same job is running twice here. 
3. Below is the code snippet for which we are facing this issue as this method "hasDefunctScheduler" is returning true : 
            `return scheduler.isDefunct(clock.millis()) && schedulerDao.isNotSelf(scheduler);`

4. scheduler.isDefunct(clock.millis()) -> 
 Quartz is considering the last check-in time of the region-1 scheduler and is comparing it with the current milliseconds of region-2 instance. Hence it is returning true. 
          `public boolean isDefunct(long time) {
       ​return expectedCheckinTime() < time;
   ​}`
 
    `private long expectedCheckinTime() {
        return lastCheckinTime + checkinInterval + TIME_EPSILON;
    }`

5. Below is the snippet of code where we are comparing the scheduler from region-1 with the scheduler of the region-2 which are not same so we are getting the condition as true. 

 `public boolean isNotSelf(Scheduler scheduler) {
        return !instanceId.equals(scheduler.getInstanceId());
    }`

Please assist me with the above issue .

**Comment by jhouserizer** [comment]
Quartz docs are pretty clear that the clocks on the machines need to be synchronized (such as with NTP) - can you confirm that is the case?  it sounds like either the clocks are not synchronized, or one of the instances is stalling for long periods (e.g. CPU starvation).

**Comment by jhouserizer** [comment]
Also note that mongodb support is NOT part of quartz - it's someone else's add on.
