### ISSUE TITLE
Version 2.2.2 Initial Tables created for MS-SQL lacks a forein key

### ISSUE THREAD

**Issue by GeorgHohenberger** [quartz-scheduler/quartz#76]
The table QRTZ_BLOB_TRIGGERS lacks the foreign key to the QRTZ_TRIGGERS table like the other trigger type tables have (e.g. QRTZ_SIMPLE_TRIGGERS).
In Oracle this foreign key is named QRTZ_BLOB_TRIG_TO_TRIG_FK.
In MSSQL the name schould be 
FK_QRTZ_BLOB_TRIGGERS_QRTZ_TRIGGERS but it is not present.

Was this made by accident or intention?

**Comment by zemian** [comment]
Hi @GeorgHohenberger , thanks for reporting the issue. I don't have a MS-SQL server to test this schema changes, it does look like a miss. Do you mind sending a Pull Request to patch the schema?

Zemian

**Comment by GeorgHohenberger** [comment]
No sorry, i don't want to join developing quartz, i just stumbled upon this when migrating quartz jobs for my company.
