### ISSUE TITLE
When run "mvn clean install -DskipTests" in java8, got error for javadoc plugin. 

### ISSUE THREAD

**Issue by ligangty** [quartz-scheduler/quartz#8]
When I download the code and try to build with "mvn clean install -DskipTests", It always failed with error of javadoc plugin.

Seems this is because of java 8 javadoc xlint check is much more strict than previous. See blog.joda.org/2014/02/turning-off-doclint-in-jdk-8-javadoc.html.

**Comment by jhouserizer** [comment]
See #9

**Comment by zemian** [comment]
This is now fixed. See PR https://github.com/quartz-scheduler/quartz/pull/50
