### ISSUE TITLE
Wrong next fire time calculation during DST hour.

### ISSUE THREAD

**Issue by mbrade** [quartz-scheduler/quartz#81]
We use quartz to call other services periodically every minute. During DST we noticed that the signal did not arrive for exact one hour. We investigated the problem and found out that after the last minute passed in the current timezone ( in our case 2:59 CEST ) the next trigger time will be set to 3:00 CET. Which means that during the second hour 2:00 - 2:59 CET no triggering will be done.
Setting  the timezone to UTC at the cronexpression would fix our problem, but there are also usecases where you can not change the timezone.

I wrote a small junit test that illustrates the problem.
[TestCronExpression.zip](https://github.com/quartz-scheduler/quartz/files/575375/TestCronExpression.zip)

**Comment by zemian** [comment]
Hi @mbrade Are you running Cron trigger? If yes, then that's how it is designed. If you want constant periodic schedule of every minute, then try using Simple trigger instead. See http://www.quartz-scheduler.org/documentation/faq.html#FAQ-daylightSavings

**Comment by mbrade** [comment]
Hi Zemian
yes we use the CronTrigger. And we fixed it using UTC is timezone. But as I wrote some things wouldn't work. E.g. Do something every minute between 1 and 3 o'clock. Using another timezone wouldn't work and also SimpleTrigger does not the job. You could do workarounds but I wouldn't expect to need them using a framework like quartz.
Anyway for me the status is clear now. I'll inform our department about the limitation and provide the possible workarounds.
Thank you.
