### ISSUE TITLE
[Question] Why updating calendars with updateTriggers changes triggers state to WAITING

### ISSUE THREAD

**Issue by TomaszWrona** [quartz-scheduler/quartz#829]
When `JobStoreSupport.storeCalendar` method is invoked with `updateTriggers` option set to true, all triggers that reference given calendar are updated, and the state of those trigger always changes to `WAITING`.

I would not like to change state of the triggers that are associated with a calendar, but I guess hardcoded `WAITING` status for triggers in `storeCalendar` has a reason, which is not clear to me.

Background: In my application user can disable single trigger. Actually `JobStoreSupport.pauseJob` method is used but there can be only one trigger per job and effectively disabled jobs are jobs with triggers in state PAUSED. Users complain that their "inactive" jobs change status to "active" automatically.

My question is:
Can I change `JobStoreSupport.storeCalendar` method to retain current trigger status when recalculating triggers?

**Comment by BrandonDotLin** [comment]
@TomaszWrona I had the same issue as you, all PAUSED triggers change to WAITING after calling:
`scheduler.addCalendar(calName, cal, true, true);`

Any advise or suggestions to deal with the weird problem?

**Comment by TomaszWrona** [comment]
@hebrd I created custom implementation of `org.quartz.jobStore.class` by extending JobStoreTX. In my custom implementation I just override storeCalendar method. In fact, I changed only this part of the original method:

```
for(OperableTrigger trigger: trigs) {
	trigger.updateWithNewCalendar(calendar, getMisfireThreshold());

	String originalTriggerState = getDelegate().selectTriggerState(conn, trigger.getKey());
	String newTriggerState = originalTriggerState.equals(STATE_PAUSED) ? STATE_PAUSED : STATE_WAITING;

	log.info("recalculate QUARTZ trigger {}", trigger.getKey());

	storeTrigger(conn, trigger, null, true, newTriggerState, false, false);
}
```
