### ISSUE TITLE
[Question] Trigger that fires every two weeks by specific day of week

### ISSUE THREAD

**Issue by kuza2010** [quartz-scheduler/quartz#834]
Let's say I want my triggers fires every 2 weeks by Monday, Tuesday and Friday at 18:00, how can I create this one?
The cron expression  `0 0 18 */14 * 1,2,5` seems does not supported

**Comment by kuza2010** [comment]
It's clear that we can create a job and 3 triggers that will fires every two week. It it possible to do that in terms of one trigger.

**Comment by RitikDua3** [comment]
@kuza2010 
For once a week, with trigger on Mon, Tue and Fri 
You can use this cron expression `0 18 0 ? * MON,TUE,FRI *`

For further update, you can use this website . [Cron Generator](https://www.freeformatter.com/cron-expression-generator-quartz.html)

**Comment by kuza2010** [comment]
Thank you for your comment, @RitikDua3 but it's not a case. I need there is some interval be present between weeks. I don't need repeat it evert week.

**Comment by kuza2010** [comment]
Ok, I am closing it since I have not found another way except creating 3 separate triggers.
