### ISSUE TITLE
How do I configure not to automatically create tables at startup

### ISSUE THREAD

**Issue by 1248142645** [quartz-scheduler/quartz#836]
Do not prefix QRTZ_ table, how to prohibit creation

**Comment by kirmerzlikin** [comment]
I believe Quartz itself does not create database tables, it expects you to create them manually before starting the scheduler (see [this piece of documentation](http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/tutorial-lesson-09.html#TutorialLesson9-JDBCJobStore)).

But if you are using Quartz with Spring Boot (namely, `spring-boot-autoconfigure` module) then Spring Boot will create those tables for you (via `QuartzDataSourceScriptDatabaseInitializer`). To disable this behaviour, you need to simply set configuration property `spring.quartz.jdbc.initialize-schema` to `never`.

**Comment by gklijs** [comment]
@kirmerzlikin is right, so this can be closed.
