### ISSUE TITLE
Link broken with doc about how to use terracotta + scheduler

### ISSUE THREAD

**Issue by pablovb** [quartz-scheduler/quartz#841]
https://github.com/quartz-scheduler/quartz/blob/master/docs/configuration.adoc contains a section [Configuration of TerracottaJobStore (Clustering without a database!)](https://github.com/quartz-scheduler/quartz/blob/master/docs/configuration.adoc#configuration-of-terracottajobstore-clustering-without-a-database), where

> More information about this JobStore and Terracotta can be found at http://www.terracotta.org/quartz

that link is broken

**Comment by pablovb** [comment]
The link should be fixed

**Comment by jhouserizer** [comment]
Resolved: https://github.com/quartz-scheduler/quartz/pull/891
