### ISSUE TITLE
Where can I find release notes for v2.2.0, 1, 2, 3 and v2.3.0?

### ISSUE THREAD

**Issue by blamepotato** [quartz-scheduler/quartz#846]
I've searched for them every where and can't find them.

**Comment by fabioformosa** [comment]
I've found this changelog https://github.com/quartz-scheduler/quartz/blob/master/docs/changelog.adoc but it looks more like the set of jira issues moved to done than an upgrade guide.
About the v2.3.2, there's no mention in the doc of the official website.
