### ISSUE TITLE
Quartz 2.2.2 Triggers does not fire and stays in Waiting State

### ISSUE THREAD

**Issue by aditya1592** [quartz-scheduler/quartz#856]
Hi!

I am creating jobs dynamically whenever server gets a request. Triggers are set to fire only once for every request and have enabled the property withMisfireHandlingInstructionFireNow for the scheduled trigger.

Quartz properties :: JobStore class :JobStoreTX , 10 threadCount and db pool.

Issue :: Since few days back there aren't any new fired triggers. In QRTZ_TRIGGERS table the job stays back in Waiting state.
I can verify that fields in table like prevFireTime is -1 and nextFireTime is perfectly set in Table and MISFIRE_INSTR is 1. But it does not triggert the job.

There aren't any exception, or error in log. I can still create new trigger, but they are never fired. 

Can anyone help, what's is the problem, or how can I resolve it?

**Comment by arun-oyo** [comment]
Can you please run the application in debug mode and share the complete log dump?

Also, which version of quartz you are using?
