### ISSUE TITLE
Please reopen non-stale issues

### ISSUE THREAD

**Issue by Vampire** [quartz-scheduler/quartz#865]
https://github.com/quartz-scheduler/quartz/issues/426, https://github.com/quartz-scheduler/quartz/issues/427, https://github.com/quartz-scheduler/quartz/issues/428, https://github.com/quartz-scheduler/quartz/issues/429, https://github.com/quartz-scheduler/quartz/issues/430 are still relevant, please reopen them.
Writing this as new issue as the comments on the closed issues are ignored and as a normal user you are not able to reopen closed issues unless you closed them yourself

**Comment by flozano** [comment]
Same with #780 please

**Comment by flozano** [comment]
yes it's still relevant

**Comment by diban** [comment]
This one also: https://github.com/quartz-scheduler/quartz/issues/674

**Comment by krodyrobi** [comment]
Also this one #591

**Comment by krodyrobi** [comment]
yes

**Comment by jhouserizer** [comment]
with review, those issues (426-430) have been handled already elsewhere

**Comment by diban** [comment]
What about the rest of the issues mentioned in this ticket? https://github.com/quartz-scheduler/quartz/issues/591, https://github.com/quartz-scheduler/quartz/issues/674 and https://github.com/quartz-scheduler/quartz/issues/780.
