### ISSUE TITLE
Weekly & Monthly Scheduled Triggers not firing when scheduled for morning time.

### ISSUE THREAD

**Issue by bhatrohit85** [quartz-scheduler/quartz#867]
Use Case : Created a trigger and added it to scheduled job today for 4 am for next day and the consecutive day. e,g i created schedule 
on monday to fire it weekly at 4 AM on tuesday and wednesday. The schedule job is added using UTC DATE format with following code
and expression

Note : Same works fine if we schedule it after noon time.
// triggername is unique
//startdate - it could be today or before that
//enddate - it would be few months later
//cronexpression - 0 30 22 ? * TUE,WED
TriggerBuilder.Create()
                      .WithIdentity(triggerName, null)
                      .StartAt(DateTime.SpecifyKind(scheduleInfo.StartDate, DateTimeKind.Utc))
                      .EndAt(DateTime.SpecifyKind(endDate, DateTimeKind.Utc))
                      .WithCronSchedule(cronexpression, action => action
                      .InTimeZone(TimeZoneInfo.Utc)
                      .WithMisfireHandlingInstructionDoNothing()
                      .Build())
                      .ForJob(jobName)
                      .Build();

**Comment by bhatrohit85** [comment]
Hi ,

I need urgent help on this. I have observed that with the code above , if i schedule trigger for tomorrow morning e.g for FRI 01:00 AM but we are passing cronexpression with UTC Time . 

The Quartz Scheduler is firing the same on SAT 01:00 AM instead of FRI 01:00 AM.  I have specified that timezone to use is UTC.
So if i am providing time too in UTC , so it should automatically adjust the time back to the server TimeZone and fire the trigger on FRI instead of SAT.

Please help me immediately as this issue has raise serious concerns to the business.

**Comment by QuantumXiecao** [comment]
@bhatrohit85  Maybe I could supply some help.  Has this problem been solved now ?

**Comment by bhatrohit85** [comment]
> @bhatrohit85 Maybe I could supply some help. Has this problem been solved now ?

Hi , Surely. I have sent the date into the IST format right now as a workaround.Setting time to UTC  is not working for this. Any help would be highly appreciated.

**Comment by jhouserizer** [comment]
@bhatrohit85   is the machine/jvm it is running on set to IST as its default timezone?

**Comment by jhouserizer** [comment]
No word, can't reproduce.
