### ISSUE TITLE
Add support for Mongo JDBC as JobStore

### ISSUE THREAD

**Issue by erikrz** [quartz-scheduler/quartz#875]
Hello, 

Recently Mongo has released a JDBC driver for their Atlas Services.

This is the reference site for the mongo JDBC driver: [www.mongodb.com/docs/atlas/data-federation/query/sql/drivers/jdbc/connect](https://www.mongodb.com/docs/atlas/data-federation/query/sql/drivers/jdbc/connect/)

This is the maven artifact: https://search.maven.org/artifact/org.mongodb/mongodb-jdbc

For the latest version, which at the time of writing this issue is version 2.0.1, the driver Class Name is: **com.mongodb.jdbc.MongoDriver**

Can you add support for this driver? i.e. create a suitable SQL file here? https://github.com/quartz-scheduler/quartz/tree/master/quartz-core/src/main/resources/org/quartz/impl/jdbcjobstore

Any help provided is appreciated. Thanks in advance,
Erik

**Comment by mp911de** [comment]
This support doesn't make sense as the Atlas SQL API is read-only. Instead, having JobStore with a proper MongoDB client implementation would be useful.

**Comment by jhouserizer** [comment]
Contributions are welcome. 😉
