### ISSUE TITLE
Support namespace concept in microservices with same db scene

### ISSUE THREAD

**Issue by QuantumXiecao** [quartz-scheduler/quartz#879]
I have one PR to support namespace concept which is useful for  microservices with same db scene.
Welcome to discuss and I am not sure whether or not this PR require review?

**Comment by jhouserizer** [comment]
Sure, make a PR or share more info some other way. It's not entirely clear from your brief description what problem you're solving.   There's already a feature for distinguishing schedulers using the same database by the scheduler name - and it almost sounds like you're describing the same thing.
