### ISSUE TITLE
Question: Is Quartz exposing Prometheus  metrics?

### ISSUE THREAD

**Issue by bkkite** [quartz-scheduler/quartz#880]
We are thinking of using Quartz as our framework for scheduling tasks. One of the requirements we have is that the system has to expose metrics to Prometheus. Does quartz export metrics to Prometheus?,  In case not is this planned in somehow?

**Comment by jhouserizer** [comment]
No it does not, and it is not a planned feature.   Contributions are always welcome. 😉
