### ISSUE TITLE
Consultation on the next version 2.4.0 of Quartz

### ISSUE THREAD

**Issue by simpleyoung129** [quartz-scheduler/quartz#885]
Hello, I see that the latest version of Quartz is four years ago. I want to ask when the next version 2.4.0 can be released and what plans do you have? :)

**Comment by jhouserizer** [comment]
Next version will likely be "2.5.0" and the "major" plans for it are updating to use Jakarta namespace and updating 3rd party library usage in general.   Hope to be completed in april.
