### ISSUE TITLE
Add a method to return true when the QuartzSchedulerThread is actually paused

### ISSUE THREAD

**Issue by nithril** [quartz-scheduler/quartz#89]
Hello,

Actually `QuartzScheduler#standby` call `schedThread.togglePause(true);` which set `paused` to true. Consequently:
- `QuartzScheduler#isInStandbyMode` returns true even if jobs are running or triggers are in the process of being executed.
- `QuartzScheduler#isInStandbyMode` calls `QuartzSchedulerThread#isPaused` which is not synchronized, thus `paused` field changes may not be visible

Thus an external process could not `standby` the scheduler **and wait until all job completes**. For example:
```
    scheduler.standby();
    while (!scheduler.isInStandbyMode() || !scheduler.getCurrentlyExecutingJobs().isEmpty()) {...}
```

I wonder if it possible to: 
- change the behaviour to:  `QuartzScheduler#isInStandbyMode` returns true when `QuartzSchedulerThread` reached the pause handling code.
- In order to do not modify the current behaviour, add a new method to return this information

Thanks,

Nicolas

**Comment by nithril** [comment]
I could submit a PR if you need

**Comment by jhouserizer** [comment]
A proposal of change (addition) would be welcome.   Though isInStandbyMode() is really only meant to tell whether that mode has been enabled, not when it is fully in effect.  So an additional method would likely be the correct addition.   Though you also mention a probably thread safety issue, so a fix for that would also be welcome.

Thanks for your interest.

**Comment by nithril** [comment]
I propose this implementation:
- A boolean `QuartzSchedulerThread#standby` will be set to true when the scheduler is actually paused, eg. in the pause loop
- A new method `QuartzScheduler#isStandby` will return the actual pause state whereas `isInStandbyMode` return the mode.

Regarding the thread safety issue, I propose to add the volatile keyword to the `QuartzSchedulerThread#paused` field
