### ISSUE TITLE
Daily Interval Scheduler Misbehaving

### ISSUE THREAD

**Issue by bhatrohit85** [quartz-scheduler/quartz#890]
I have a windows application in .Net 6 ( C# ) which adds Schedules using Quartz 3.6.2 . The schedules misbehave erratically , sometimes , it fires the job at same time multiple times or fires at wrong interval. we are passing UTC time and have used cron expression builder.  Our requirement is simple to run a job between any start and end time during a day and also between some dates  e.g 
1. Daily between  5 am till 11 pm with interval of 19 mins starting from 20 Feb 2023 till 31 Apr 2023
2. Daily between 7 am till 9 pm with interval of 5 mins starting from 20 Feb 2023 till 31 Apr 2023
3. Daily between  12:05 pm till 11:55 pm with interval of 60 mins starting from 20 Feb 2023 till 31 Apr 2023
4. Daily between 9 am till 9 pm with interval of 150 mins starting from 20 Feb 2023 till 31 Apr 2023

Following is the code snippet.

var trigger = TriggerBuilder.Create()
                                      .WithIdentity(triggerName, null)
                                      .ForJob(jobName)
                                      .StartAt(DateTime.SpecifyKind(scheduleInfo.DailyStartTime.Value, DateTimeKind.Utc))
                                      .EndAt(DateTime.SpecifyKind(endDate, DateTimeKind.Utc))
                                      .WithCronSchedule($"0 */{scheduleInfo.DailyInterval} * ? * *", action => action
                                      .WithMisfireHandlingInstructionDoNothing().InTimeZone(TimeZoneInfo.Utc).Build())
                                      .Build();

Please respond quickly as this issue is impacting our Client Deliverables . This has created risk and i am not getting any solution from any article . I have to get the solution asap as this is impacting timeline . Any help soon would be highly appreciated.

**Comment by zy1263188600** [comment]
Java Quartz has the same problem
This is my code
```java
    public static void main(String[] args) {
        String cron = "0 */9 * * * ?";
        CronExpression cronExpression = new CronExpression(cron);
        Date date = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").parse("2023-03-30 00:00:00");
        for (int i = 0; i < 10; i++) {
            date = cronExpression.getNextValidTimeAfter(date);
            System.out.println(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(date));
        }
    }
```
```log
2023-03-30 00:09:00
2023-03-30 00:18:00
2023-03-30 00:27:00
2023-03-30 00:36:00
2023-03-30 00:45:00
**2023-03-30 00:54:00**
**2023-03-30 01:00:00**
2023-03-30 01:09:00
2023-03-30 01:18:00
2023-03-30 01:27:00
```

**Comment by jhouserizer** [comment]
@zy1263188600   that is working exactly as intended.   "*/9"  does NOT mean "every 9 minutes".  It means "starting at the 0th minute, turn on every 9th minute of the hour",  resulting in minutes 0,9,18,27,36,45,54 of every hour.

If you want "every 9 minutes" then you should use SimpleTrigger not CronTrigger.

**Comment by zy1263188600** [comment]
@jhouserizer Thank you for your answer

**Comment by shafi-sha** [comment]
@zy1263188600 if you give the expression like this 0 9 * ? * * , then it will work by every 9 minutes. It won't start every 0th minute of an hour.
