### ISSUE TITLE
Set cronExpression properties of CronTrigger to * /22 * * * ? but it also run at the Hour point  （sharp）too ？

### ISSUE THREAD

**Issue by PaulFang** [quartz-scheduler/quartz#90]

**Comment by jhouserizer** [comment]
Yes, that's the expected behavior.   /22 means starting at minute "00" run every 22nd minute of the hour.   So the expected fire times would be like:   10:00, 10:22, 10:44, 11:00, 11:22, 11:44, 12:00, 12:22, ...
