### ISSUE TITLE
Worker service with Quartz -Scheduler

### ISSUE THREAD

**Issue by danies8** [quartz-scheduler/quartz#900]
Hi, I'm using Quartz -Scheduler in worker service. When user close the service, how i recognize it happened in Quartz -Scheduler level ? Thanks in advance,

**Comment by jhouserizer** [comment]
What do you mean by "worker service" ?

**Comment by danies8** [comment]
Service in.NET called worker service (template).

**Comment by jhouserizer** [comment]
Sorry, no idea how to give help for that.  Please inquire with the quartz .NET community.  (this is the original java-based Quartz community).
