### ISSUE TITLE
What releases ACQUIRED triggers on scheduler shutdown?

### ISSUE THREAD

**Issue by bradical** [quartz-scheduler/quartz#905]
I have a situation with an every 5s trigger running in a clustered environment where a container in my cluster is shutting down with the trigger still in an ACQUIRED state and never releases it back for other nodes to pick up. Thus, it is stuck in ACQUIRED with a next fire time in the past until yet another node starts up which will re-persist it and release its ACQUIRED status:

```
023-04-10 10:36:54,485 INFO  [LocalDataSourceJobStore] ClusterManager: ......Freed 2 acquired trigger(s).
```

What's a little odd is that we have a listener looking for `triggerComplete` events that seems to indicate the trigger in question did complete (forgive the misspellings in our logging):

```
2023-04-10 10:36:53,755 DEBUG [TriggerLogger] Firied Trigger: Publish Request Check at Mon Apr 10 10:36:53 EDT 2023 (scheduled fire time was Mon Apr 10 10:36:53 EDT 2023)
2023-04-10 10:36:53,758 DEBUG [TriggerLogger] Trigger complete: Publish Request Check, Next fire time: Mon Apr 10 10:36:58 EDT 2023
```

... but it's still marked as ACQUIRED in the database with an outdated `NEXT_FIRE_TIME` as though it were interrupted exactly between sending that listener `triggerComplete` event and wherever it sets the STATE back to `WAITING`.

I'm looking for some specific logging or anything in the code that indicates how a container shutting down and holding a trigger as ACQUIRED is supposed to release it if it is supposed to. Would this be code in the QuartzScheduler or elsewhere? Or is this the responsibility of remaining nodes to notice that an ACQUIRED trigger has effectively misfired?

Admittedly, we're on a much older version of Quartz (1.8.3) and we're trying to upgrade. Though in either case (with 1.8.x or 2.x), we're trying to figure out how Quartz is supposed to be handling this sequence in its design.

**Comment by jhouserizer** [comment]
It should work pretty much the same way in 1.8.3 and 2.x versions.

For non-clustered schedulers triggers that were in ACQUIRED state when the scheduler "wen't down" are released when the scheduler is next initialized.

For clustered schedulers (which it sounds like you have), ACQUIRED triggers should be released from that state by other cluster members ("scheduler nodes" or "instances") when they notice that the scheduler that had it ACQUIRED is gone.  The amount of time this takes depends upon your configuration (the cluster check-in interval).   You should be able to find this happening in JobStoreSupport.java in the clusterRecover() method.  In current head revision that's here: https://github.com/quartz-scheduler/quartz/blob/main/quartz/src/main/java/org/quartz/impl/jdbcjobstore/JobStoreSupport.java#L3539

**Comment by bradical** [comment]
Thanks @jhouserizer! Ill look for some equivalent code in 1.8.x. We're clustered in that we're using:

```
org.quartz.jobStore.isClustered = true
org.quartz.jobStore.txIsolationLevelReadCommitted = true
```

though we don't seem to be using any kind of cluster check-in interval and based on experience here it doesn't seem like the remaining nodes are recovering these ACQUIRED triggers. I'll poke around. 

Thank you!

**Comment by jhouserizer** [comment]
Ah, the individual nodes need to have unique instanceId, or it won't work.

**Comment by jhouserizer** [comment]
Try  "org.quartz.scheduler.instanceId = AUTO" as a way to get unique ones.

Also mind that the clocks on the machines are all synchronized (e.g. with ntp).

https://www.quartz-scheduler.org/documentation/quartz-2.3.0/configuration/ConfigJDBCJobStoreClustering.html

**Comment by bradical** [comment]
Thank you! I was not aware of that AUTO option. We'll try that now.

**Comment by bradical** [comment]
By the way in confirmed that giving each node a unique instance id allowed recovery to work seamlessly for the remaining modes. 

Thanks again for your help!

**Comment by bradical** [comment]
One other question related to this: where would I look for the code that executes between when listener triggerComplete executes and when a trigger is updated from ACQUIRED back to waiting?

I was trying to figure out why/where the node shutting down is failing to release the trigger itself.
