### ISSUE TITLE
Typo in JobStoreCMT.

### ISSUE THREAD

**Issue by oleghailenko** [quartz-scheduler/quartz#91]
Method `executeInLock` requires lock name as a parameter.
It obtains lock `lockName`, executes callback, and than releases lock with name `LOCK_TRIGGER_ACCESS`.
See https://github.com/quartz-scheduler/quartz/blob/master/quartz-core/src/main/java/org/quartz/impl/jdbcjobstore/JobStoreCMT.java#L248

I think it is just a typo, and not sure is it could be problem.

**Comment by zemian** [comment]
Yep, I think that's oversight. Thanks for pointing this out @oleghailenko !

**Comment by zemian** [comment]
It's fixed now.
