### ISSUE TITLE
In Quartz cluster mode, after instance A is stopped, tasks are not running on instance A

### ISSUE THREAD

**Issue by MiahLuo** [quartz-scheduler/quartz#914]
Quartz in cluster mode, instances A and B run simultaneously. When instance A is stopped, the instance is running on instance B, but when instance A is restarted, the task is not running on instance A. If instance B is stopped, only instance A remains and the task is not running. Example A prints the following two lines of logs. The task is not running, but its state is normal. What is the reason

2023-04-27 13:38:27.897  INFO 8 --- [39442_ClusterManager] o.s.s.q.LocalDataSourceJobStore         (3644) : ClusterManager: detected 1 failed or restarted instances.
2023-04-27 13:38:27.897  INFO 8 --- [39442_ClusterManager] o.s.s.q.LocalDataSourceJobStore         (3503) : ClusterManager: Scanning for instance "trustasiadeMBP.lan1682566311912"'s failed in-progress jobs.

The configuration is as follows：
spring:
  quartz:
      job-store-type: jdbc
      jdbc:
        initialize-schema: never
      #相关属性配置
      properties:
        org:
          quartz:
            scheduler:
              instanceName: MyClusteredScheduler
              instanceId: AUTO
            jobStore:
              # 升级 springboot 版本，注释 class 属性
              class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
              #driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
              driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
              tablePrefix: QRTZ_
              isClustered: true
              clusterCheckinInterval: 10000
              useProperties: false
            #            dataSource: quartzSource
            threadPool:
              class: org.quartz.simpl.SimpleThreadPool
              threadCount: 10
              threadPriority: 5
              threadsInheritContextClassLoaderOfInitializingThread: true

**Comment by jhouserizer** [comment]
I'm sorry, I do not quite follow what you are describing as the problem scenario.

My only guess from what I understand is that instance A is not being started with the scheduler.start() method, and that perhaps only the scheduler.initialize() is being called.   There should be clear logging about start() being called, if it is being called.

**Comment by jhouserizer** [comment]
Haven't heard back, sounds like a usage issue.
