### ISSUE TITLE
Quartz Scheduler with CORN not working after the deployment 

### ISSUE THREAD

**Issue by vijaysahu12** [quartz-scheduler/quartz#916]
Hello Team, 
I have successfully implement the quart scheduler for my .NET Core API Project also I am able to run the scheduler for my .NET API based on the given CORN config (every 20 seconds). 

But I have noticed that there is no trigger occured when I am deploying/publishing the build to window server (IIS Server). 

Could you please help me to understand why the same scheduler working in debug mode but not after the deployment on server. 

Regards,
Vijay Sahu

**Comment by jhouserizer** [comment]
Hi,  this project is for the original Java version of Quartz.   .NET port of quartz is supported elsewhere.
