### ISSUE TITLE
Getting timeout issue: org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: Lock wait timeout exceeded; try restarting transaction

### ISSUE THREAD

**Issue by maheshd-atulsia** [quartz-scheduler/quartz#919]
When using quartz in Wildfly after certain period of time we are getting a timeout issue
`org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: Lock wait timeout exceeded; try restarting transaction`

After restarting the Wildfly server it works fine for 3-4 hours and then again we get the same issue.

Is any permanent solution available to fix the issue?

**Comment by jhouserizer** [comment]
That's obviously not normal at all.  Can you provide more details:  what database?  what datasource?  full quartz.properties, etc.
