### ISSUE TITLE
Trigger maximum of N jobs per time period

### ISSUE THREAD

**Issue by kidmeke** [quartz-scheduler/quartz#92]
Is there a way to restrict job triggering such that a maximum of N jobs per time period are triggered? I am using quartz to fire off jobs that call a third party web service which imposes a limit on the number of times it can be called in a minute.

Thanks for any help

**Comment by zemian** [comment]
Hi, you can try write your own TriggerListener implementation and register in the scheduler limit job invocation once it reach a limit. 

Please use the quartz forum to ask usage question. This is for tracking quartz bug issues only.

**Comment by zemian** [comment]
Closing question
