### ISSUE TITLE
QRTZ_SCHEDULER_STATE - Manually clearing or is there a routine.

### ISSUE THREAD

**Issue by s3YwCf2ZbfJG4SHAfjQMAjtsf** [quartz-scheduler/quartz#926]
- Can I programmatically delete an entry from this table?
    -   Or can I just stop my application, clear the table, and then restart and get a new instance?
- Is there anyway to tell which job ran on which instance by looking at the tables?  
    - I have the Crystal Quartz Dashboard, I am not sure if that indicates anything.

We thinking we are seeing issues of jobs being routed to a no longer present instance.   Also, triggers are being created with WithMisfireHandlingInstructionDoNothing so I suspect it isn't logging these situations.

Example table: 
![image](https://github.com/quartz-scheduler/quartz/assets/784740/e68fd1dd-a43b-4bef-9096-6e65d4e99e56)

**Comment by jhouserizer** [comment]
You can certainly delete entries in that table if you want to (with schedulers shut down).

I'm not sure what problem you're really chasing though.   "We thinking we are seeing issues of jobs being routed to a no longer present instance" - this can't be the case - jobs are not "routed" to schedulers.  Instead, running schedulers "claim" triggers to fire (and execute the related job).

**Comment by s3YwCf2ZbfJG4SHAfjQMAjtsf** [comment]
-- unning schedulers "claim" triggers to fire -- 

Ah Thank you, that helps.  

Yes, I want to delete some entries.   Still in dev for new functionality and the instance name using the guid turned into a bad idea.

Thanks!
