### ISSUE TITLE
Should Quartz allow key words as schedule pattern

### ISSUE THREAD

**Issue by SYThomasNordmeyer** [quartz-scheduler/quartz#929]
I am working with Quarkus which uses Quartz as scheduler. Quarkus allows environment dependent configuration in its application.properties file, like 
`schedule.hubject.pullEvseStatus=0 */5 * ? * *`
When I want to disable the schedule in "test" environment, I have to do this via workaround like 
`%test.schedule.hubject.pullEvseStatus=0 0 0 1 1 ? 2099`
assuming this will not be executed in 2099.

Wouldn't it be better to have this configurable more explicit like
`%test.schedule.hubject.pullEvseStatus=NEVER`

**Comment by konopka** [comment]
You are looking at this problem from wrong point of view, why would you create a job that should be never scheduled/executed?
I think you should:
1. do not create such job at all
2. if you still want the job to exist, you can pause it
3. or you can place simple logic in job execute method that will just return when your on/off property is set

**Comment by SYThomasNordmeyer** [comment]
Hi @konopka your point of view is not wrong. But please try to understand mine: Configurations in Quarkus may be parameterized by runtime environment. In production i would use a regular cron timed schedule but test environments some jobs I don't want ever to be invoked. Currently I am using cron schedules starting in 2099 as described above. But it's not very clear that in fact "NEVER" is meant.
