### ISSUE TITLE
Default value for `sched_name` column

### ISSUE THREAD

**Issue by Eccenux** [quartz-scheduler/quartz#931]
The migration guide was added in v2.3:
https://github.com/quartz-scheduler/quartz/blob/quartz-2.3.x/docs/migration-guide.adoc

It mentioned adding `sched_name` with a default value:
```
alter table qrtz_blob_triggers add column sched_name varchar(120) not null DEFAULT 'TestScheduler';
alter table qrtz_calendars add column sched_name varchar(120) not null DEFAULT 'TestScheduler';
alter table qrtz_cron_triggers add column sched_name varchar(120) not null DEFAULT 'TestScheduler';
alter table qrtz_fired_triggers add column sched_name varchar(120) not null DEFAULT 'TestScheduler';
alter table qrtz_job_details add column sched_name varchar(120) not null DEFAULT 'TestScheduler';
...
```

However, SQL for creating DB is different and doesn't have `DEFAULT` for `sched_name` columns:
https://github.com/quartz-scheduler/quartz/blob/quartz-2.3.x/quartz-core/src/main/resources/org/quartz/impl/jdbcjobstore/tables_postgres.sql

So is that default required? There are other differences, but I'll report that separately.

**Comment by Eccenux** [comment]
Still true

**Comment by jhouserizer** [comment]
When created new tables (e.g. what the tables_postgres.sql etc. are for) there is no need for a default value.   When altering existing tables with existing rows, when the column is added it needs to have a value for the existing rows, so the migration guide is suggesting to provide one.
