### ISSUE TITLE
Documentation links are broken on website

### ISSUE THREAD

**Issue by geertschuring** [quartz-scheduler/quartz#938]
On http://www.quartz-scheduler.org/documentation/ the links to the documenation of most versions higher then 2.2.2 are broken.

**Comment by ruanwenjun** [comment]
And I find the website can't open.
<img width="1907" alt="image" src="https://github.com/quartz-scheduler/quartz/assets/22415594/8d2566c9-7a0a-4356-bf90-970fbd3d27ab">

**Comment by geertschuring** [comment]
Yes this is still relevant. I don't know how to fix this myself.

**Comment by jhouserizer** [comment]
Thanks. See #1195  The broken links have been fixed and/or removed (different cases).  When 2.4.0 and 2.5.0 are GAd soon those links will be added.
