### ISSUE TITLE
Getting two instances that is of autorun and misfired once resume the job after pausing.

### ISSUE THREAD

**Issue by newujwalagit** [quartz-scheduler/quartz#939]
I have paused and resumed the schedule. after resuming a schedule using jobScheduler.resumeJob(new JobKey(schedule.getName(), groupId))  I am getting two entries i.e. one of autorun and one of misfired  even though there were number of triggers available between pause and resume. I already tried updating the start time and nextFireTime. So what can be the solution to resolve this issue, so that I must get the nextFireTimeTriggers only which are after the current time?

**Comment by geertschuring** [comment]
Hi @newujwalagit, I am not a developer of this project (just a user like you) but could you edit your issue so that it has a short title and a descriptive description? Thank you!

**Comment by yy-am** [comment]
I have the same problem. Have you solved it
