### ISSUE TITLE
Any plan for 2.4.0 release ?

### ISSUE THREAD

**Issue by gauravdeshmukh612** [quartz-scheduler/quartz#942]
Hi Team,

we are using quartz schedular dependency in our project, any plan to release 2.4.0 final version?

Thanks,
Insights

**Comment by AndreasIgelCC** [comment]
Same question by me.

**Comment by SakuruLIU** [comment]
Same question by me.

**Comment by SakuruLIU** [comment]
Same question by me.

**Comment by hesha0809** [comment]
Same question by me.

**Comment by Shoothzj** [comment]
Same question by me.

**Comment by opparwat** [comment]
any plan to release 2.4 or 2.5?

**Comment by lihulanxx** [comment]
any plan to release 2.4 or 2.5?

**Comment by jhouserizer** [comment]
https://github.com/quartz-scheduler/quartz/discussions/1166
