### ISSUE TITLE
How to create multiple SchedulerFactoryBeans with multiple datasources

### ISSUE THREAD

**Issue by gopalsyngen** [quartz-scheduler/quartz#951]
I tried to create multiple SchedulerFacatoryBean objects and while starting the application getting below error
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method quartzEndpoint in org.springframework.boot.actuate.autoconfigure.quartz.QuartzEndpointAutoConfiguration required a single bean, but 4 were found:
	- quartzScheduler: defined by method 'quartzScheduler' in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class]
	- IN: a programmatically registered singleton	- ID: a programmatically registered singleton	- PK: a programmatically registered singleton

**Comment by jhouserizer** [comment]
This is a Spring question, not a quartz question.
