### ISSUE TITLE
Java version compatibility 

### ISSUE THREAD

**Issue by knurff** [quartz-scheduler/quartz#955]
"Quartz 2.4.0 RC1 now requires minimum Java version of Java 8" - from release notes, but I got "class file has wrong version 55.0, should be 52.0" error that means I should use minimum Java 11. Same for Quartz 2.5.0 RC1. Сould you please clarify this point?

https://stackoverflow.com/questions/9170832/list-of-java-class-file-format-major-version-numbers

**Comment by aadrian** [comment]
Also 2.5.0 RC1 does not seem to be present on the Release Page :(  https://github.com/quartz-scheduler/quartz/releases

**Comment by vrozkovec** [comment]
It is present in maven repositories though: https://central.sonatype.com/artifact/org.quartz-scheduler/quartz/2.5.0-rc1/overview

Here's a comparison: https://github.com/quartz-scheduler/quartz/compare/v2.4.0-rc2...v2.5.0-rc1

Seems that project is heading towards javax -> jakarta for 2.5.x

**Comment by gsaviane** [comment]
Quartz 2.5.0-rc1 is indeed compiled with minimal JDK target version 11. It cannot be used anymore in JDK 8 projects.
If that is the intention, the manifest in the jar file should not state

> Manifest-Version: 1.0
Implementation-Title: quartz
Implementation-Version: 2.5.0-rc1
Built-By: jenkins-slave
Implementation-Vendor-Id: org.quartz-scheduler
**Built-JDK: 1.8.0_322**
