### ISSUE TITLE
When the MySQL isolation level is set to Repeatable Read, and then Quartz is started within the current transaction, it can lead to a deadlock.

### ISSUE THREAD

**Issue by JamesSmith888** [quartz-scheduler/quartz#957]
**Code snippet for reproducing the issue:**
```java
@Component
@AllArgsConstructor
public class A {

    private B b;

    @Transactional(rollbackFor = Throwable.class)
    public void a() {
        // ...
        b.quartzStart(...);
    }
}

@Component
@AllArgsConstructor
public class B {
    private Scheduler scheduler;

    public void quartzStart(...) {
        // ...

        try {
            scheduler.scheduleJob(jobDetail, getTrigger(...));
            if (scheduler.isShutdown()) {
                log.warn("scheduler is shutdown");
                return;
            }

            scheduler.start();
        } catch (SchedulerException e) {
            log.error("run plan error", e);
            throw new RuntimeException(e);
        }
    }

    private Trigger getTrigger(...) {
        // ...
    }
}
```
1. When executing the `a()` method, a transaction is initiated. At this point, the transaction isolation level is set to Repeatable Read, and relevant records in the database are locked at the row level.
2. When the code reaches `scheduler.start();`, Quartz executes this SQL statement in an attempt to acquire a lock: `SELECT * FROM QRTZ_LOCKS WHERE SCHED_NAME = 'MyScheduler' AND LOCK_NAME = 'TRIGGER_ACCESS' FOR UPDATE`. However, since the transaction initiated by the `a()` method has not yet ended, the row locks imposed by it are not released. As a result, the preceding `SELECT` SQL statement is unable to acquire the lock indefinitely.

**Database related pictures：**
SELECT * FROM INFORMATION_SCHEMA.INNODB_TRX;
![image](https://github.com/quartz-scheduler/quartz/assets/38931512/2738646b-c948-463e-b4fa-b33412a874c7)
![image](https://github.com/quartz-scheduler/quartz/assets/38931512/afec90b2-8df5-4f88-a209-947f242d8dbe)

**Temporary workaround:**
* Exclude the `b.quartzStart(...)` method from the `a()` method.
* Exclude the current transaction from `quartzStart(...)`:
    ```java
    @Transactional(rollbackFor = Throwable.class, propagation = Propagation.NOT_SUPPORTED)
    public void quartzStart(...) {
        // ...
    }
    ```
* Lower the transaction isolation level to Read Committed.

**Comment by jhouserizer** [comment]
Yes, Quartz very much requires READ_COMMITTED given its implementation.
