### ISSUE TITLE
Support obsidian-excalidraw-plugin

### ISSUE THREAD

**Issue by uPagge** [quartz-scheduler/quartz#959]
For Obsidian there is a great plugin that allows you to integrate excalidraw into the knowledge base: [obsidian-excalidraw-plugin](https://github.com/zsviczian/obsidian-excalidraw-plugin). It allows you to insert excalidraw drawings directly into the note. However, such notes are very poorly converted into quartz. It would be nice to either completely delete the parts that the plugin adds to the note, or make a link to the file to download the scheme.

**Comment by MaelImhof** [comment]
Hi,

I believe you mistook this repository for [this other one](https://github.com/jackyzha0/quartz/) with the same name.

Furthermore, a similar issue exist on the original repository, see [this issue](https://github.com/jackyzha0/quartz/issues/1043).

**Comment by melloware** [comment]
@jhouserizer this ticket is invalid and can be closed.
