### ISSUE TITLE
I created 4 tasks of the same type Job, but at the same time there were only 3 tasks running

### ISSUE THREAD

**Issue by ruanzy** [quartz-scheduler/quartz#96]
I created 4 tasks of the same type Job, but at the same time there were only 3 tasks running

**Comment by zemian** [comment]
Hello @ruanzy, that should not happen. Can you please create a Unit test to proof this? It's hard to go on without any tests.

**Comment by zemian** [comment]
Closing outdated, unresolved issues. Please, reopen if still relevant.
