### ISSUE TITLE
Add separate misfireThreshold for trigger

### ISSUE THREAD

**Issue by pavelstackoverflow** [quartz-scheduler/quartz#962]
For short time jobs it would be helpfull to have individual misfireThreshold time for each trigger
Use case:
2 group of jobs. First group - 10 minutes, Second - 20 minutes 
In each group thousand jobs, that need to execute in group interval. If jobs not execute in interval time triggerMisfired need to occur. 
So, 1000 jobs from first group start at same time, but could executed during 10 minutes, 1000 jobs from second group start at same time, but could executed during 20 minutes.
Now we have one common threshold for any trigger. If we set 10 minutes misfireThreshold, in this case second group jobs could be fire misfireTrigger if not done before 10 minutes. If set 20 minutes misfireThreshold, in this case first group jobs will be wait 20 minutes without misfireTrigger.

**Do you have any plans to realize this feature?**
Thanks

**Comment by jhouserizer** [comment]
No plans for this.  It has be considered in the past, but it makes the trigger acquisition selection tricky and non-performant.  A proposal for an implementation approach that is reasonable would be considered.
