### ISSUE TITLE
Quartz Table "QUARTZ_SIMPLE_TRIGGERS" column 'TIMES_TRIGGERED' is behaving incorrectly for JOBS more than 200.

### ISSUE THREAD

**Issue by NiteshSopra** [quartz-scheduler/quartz#97]
When we schedule more than 200 jobs in a quartz with certain repeat count(Ex: 10000)  then after certain time interval 'TIMES_TRIGGERED' column value for some jobs moved to 0.
Steps to reproduce:

1)Create 300 jobs and trigger them with a interval of 2 seconds with a repeat count of 10000.
2)After some time (30 min appx.)  value of 'TIMES_TRIGGERED' column of some jobs is getting updated as 0 which is wrong.
3)As a side effect value in column 'REPEAT_COUNT' is getting decreased which should be keep decreasing with job execution count,But the decrements is not correctly updated afterwards.
4)Same behavior is occurred randomly in case we schedule jobs with infinite repeat count.

Please find the 2 attached classes:
One to schedule a job and another to create a task.
[Quartz Classes.zip](https://github.com/quartz-scheduler/quartz/files/684122/Quartz.Classes.zip)

**Comment by zemian** [comment]
Hello @NiteshSopra ,

What you described is not reproducible, and we can test your code with custom job like that. Perhaps you might have started multiple standalone schedulers that corrupting your data. Try isolate your problem with single scheduler with clear configuration properties and a simple job.

**Comment by zemian** [comment]
Closing outdated, unresolved issues. Please, reopen if still relevant.
