### ISSUE TITLE
Why it is blocked when I try to call "Scheduler.getTriggerGroupNames()"?

### ISSUE THREAD

**Issue by linsongze** [quartz-scheduler/quartz#98]
"resin-port-9007-1484" daemon prio=10 tid=0x00007f6ef8074800 nid=0x1410 waiting for monitor entry [0x00007f6f6026e000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.quartz.simpl.RAMJobStore.getTriggerGroupNames(RAMJobStore.java:815)
	- waiting to lock <0x00000007890586c0> (a java.lang.Object)
	at org.quartz.core.QuartzScheduler.getTriggerGroupNames(QuartzScheduler.java:1354)
	at org.quartz.impl.StdScheduler.getTriggerGroupNames(StdScheduler.java:516)

    public String[] getTriggerGroupNames(SchedulingContext ctxt) {
        String[] outList = null;

        synchronized (lock) {
            outList = new String[triggersByGroup.size()];
            int outListPos = 0;
            Iterator keys = triggersByGroup.keySet().iterator();
            while (keys.hasNext()) {
                outList[outListPos++] = (String) keys.next();
            }
        }

        return outList;
    }

**Comment by linsongze** [comment]
Then I found the deadlock .

Found one Java-level deadlock:
=============================
"resin-port-9007-1558":
  waiting to lock monitor 0x00007f6e04001a38 (object 0x00000007890586c0, a java.lang.Object),
  which is held by "scheduler_Worker-2"
"scheduler_Worker-2":
  waiting to lock monitor 0x00007f6e34004a78 (object 0x0000000788fc1a68, a java.lang.Object),
  which is held by "scheduler_QuartzSchedulerThread"
"scheduler_QuartzSchedulerThread":
  waiting to lock monitor 0x00007f6e04001a38 (object 0x00000007890586c0, a java.lang.Object),
  which is held by "scheduler_Worker-2"

**Comment by zemian** [comment]
Hi @linsongze, looks like you have a custom job that holding up the lock. Ensure your job is clean and not blocking the scheduler itself.

If you still think this is a bug, please provide a Unit test to show the problem.

Thanks!
