### ISSUE TITLE
getPreviousFireTime is wrong

### ISSUE THREAD

**Issue by ahu0605** [quartz-scheduler/quartz#99]
I invoke the method ,but I get the current time that is not the last time , Can u help me ?

**Comment by ahu0605** [comment]
how to use trigger.getPreviousFireTime()

**Comment by zemian** [comment]
Hello @ahu0605 , this is not a bug. Please user quartz mailing list for questions. 

The trigger.getPreviousFireTime() is working per each Trigger implementation. Usually you can trigger reference inside your Job implementation. See Job#execute(JobExecutionContext); and JobExecutionContext#getTrigger().

**Comment by ahu0605** [comment]
ok，I know that I had implemented the method with myself,thanks a lot

**Comment by ahu0605** [comment]
ok，I know that I had implemented the method with myself,thanks a lot.
